### ISSUE TITLE
homebrew install for ToT broken - locating header_clean

### ISSUE THREAD

**Issue by paulirish** [so-fancy/diff-so-fancy#101]
Taking the issue from https://github.com/Homebrew/homebrew/pull/49712 here:

error:

```
==> /usr/local/Cellar/diff-so-fancy/0.5.2/bin/diff-so-fancy
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
/usr/local/Cellar/diff-so-fancy/0.5.2/bin/diff-so-fancy: line 74: /usr/local/Cellar/diff-so-fancy/0.5.2/bin/libs/header_clean/header_clean.pl: No such file or directory
Error: diff-so-fancy: failed
```

@scottchiefbaker it's failing to find the header_clean script. 

we're reusing the exact same logic as diff-highlight... however.. diff-highlight is [added as a global binary](https://github.com/stevemao/homebrew/blob/diff-so-fancy-0.5.2/Library/Formula/diff-so-fancy.rb#L9-L12) in the homebrew install, so diff-so-fancy never has to locate the script via the `third_party` folder path.

**Comment by paulirish** [comment]
@OJFord AFAICT, the homebrew install discards the rest of the tarball except for the two files, `diff-so-fancy` and `diff-highlight`.

![image](https://cloud.githubusercontent.com/assets/39191/13479115/a46ec29c-e089-11e5-8472-6502db291107.png)

The bug here is basically the same as "how do we do this homebrew install without making `diff-highlight` be installed globally?"

In this case, we want to retain the third_party files.. I suppose that goes into some `lib` folder?

**Comment by OJFord** [comment]
That's correct, it's `lib.install`. However, this reopens a relative addressing issue solved as a side effect of the global binary install.

```sh
% diff-so-fancy
/usr/local/bin/diff-so-fancy: line 81: /usr/local/Cellar/diff-so-fancy/0.5.2/bin/third_party/diff-highlight/diff-highlight: No such file or directory
/usr/local/bin/diff-so-fancy: line 74: /usr/local/Cellar/diff-so-fancy/0.5.2/bin/libs/header_clean/header_clean.pl: No such file or directory
```

The trivial solution would be a symlink `bin/third_party` -> `lib/third_party`. I have a feeling the Homebrew folk won't like that. I think the best way is:
```ruby
 def install
    prefix.install Dir["third_party", "libs", "diff-so-fancy"]
    bin.install_symlink prefix/"diff-so-fancy"
  end
```

**Comment by paulirish** [comment]
@OJFord yeahhhh that sounds right to me.. with that, [get_script_dir](https://github.com/so-fancy/diff-so-fancy/blob/master/diff-so-fancy#L5-L12) should sort out diff-highlight's location already. 

I don't entirely grok the diff between ` bin.install_symlink prefix/"diff-so-fancy"` and ` bin.install "diff-so-fancy"`. But I guess you're telling me the difference is worthwhile.... :)

**Comment by paulirish** [comment]
@OJFord btw how do you try out these formulas locally?

**Comment by OJFord** [comment]
For `bin.install` think `mv`; `bin.install_symlink` think `ln -s`. In both cases the target is the on-`$PATH` `/usr/local/Cellar/{formula-name}/{formula-version}/`directory.

I've been testing just by `brew reinstall diff-so-fancy`. Not sure if there's a better way.

**Comment by paulirish** [comment]
that all makes sense. sounds good.

@stevemao ollie's got a commit above that sorts out our bump to 5.0.2 ... can you use that in the homebrew pr?

**Comment by OJFord** [comment]
@paulirish I did open a PR stevemao/homebrew#1 actually, on the same branch as Homebrew PR, so it should bubble through if I did that right.

**Comment by paulirish** [comment]
Nice work!

**Comment by paulirish** [comment]
closing as 5.0.2 is now published. 

thx for the work, ollie. btw feel free to close issues on your own if you like. :)

**Comment by OJFord** [comment]
No worries; sorry about that I thought the commit message had closed it.
