### ISSUE TITLE
Files are considered to be renamed with `diff.mnemonicprefix`

### ISSUE THREAD

**Issue by blueyed** [so-fancy/diff-so-fancy#103]
% git -c diff.mnemonicprefix=true-c pager.diff=diff-so-fancy diff
    …
    renamed: i/luaa.c to w/luaa.c
    …

That's because it's only looking for `a` and `b` there, but should discard the first path segment altogether probably.

**Comment by paulirish** [comment]
fascinating. didn't know `mnemonicprefix` existed. Do you use it by default?

**Comment by blueyed** [comment]
Yes, and I hit corner cases all the time.. :)

**Comment by blueyed** [comment]
See also 29a88893d2a23484b745b099c6c139b471dae6b0.

**Comment by scottchiefbaker** [comment]
@blueyed I didn't know this was a thing... Can you give me the RAW diff output with `mnemonicprefix` enabled (and diff-so-fancy disabled) so I can see it, and work around it?

    git diff --color | base64

**Comment by blueyed** [comment]
@scottchiefbaker 
It's just that it uses different prefixes from "a" and "b":

       diff.mnemonicPrefix
           If set, git diff uses a prefix pair that is different from the
           standard "a/" and "b/" depending on what is being compared. When this
           configuration is in effect, reverse diff output also swaps the order
           of the prefixes:

           git diff
               compares the (i)ndex and the (w)ork tree;

           git diff HEAD
               compares a (c)ommit and the (w)ork tree;

           git diff --cached
               compares a (c)ommit and the (i)ndex;

           git diff HEAD:file1 file2
               compares an (o)bject and a (w)ork tree entity;

           git diff --no-index a b
               compares two non-git things (1) and (2).

**Comment by scottchiefbaker** [comment]
Ahhhhh... so file names can be:

1. a/foo.txt
2. b/foo.txt
3. i/foo.txt
4. w/foo.txt
5. c/foo.txt
6. o/foo.txt

Did I miss any? We can work around those in the regexp pretty easily.

**Comment by scottchiefbaker** [comment]
Ok I think I fixed this (and added some tests) on this branch: https://github.com/scottchiefbaker/diff-so-fancy/tree/mnemonic_prefix

The easiest way to test is to download this file: https://github.com/scottchiefbaker/diff-so-fancy/blob/mnemonic_prefix/libs/header_clean/header_clean.pl and overwrite the one in your `libs/header_clean/`

It "works-for-me", can you confirm it works for you. If it does I'll get a PR request to get it included in the main codeline

**Comment by blueyed** [comment]
@scottchiefbaker 
It WFM, too - thanks!

I suggest just matching `./` (regexp) instead (see https://github.com/scottchiefbaker/diff-so-fancy/commit/a3092aca66897e48e342341bd961d41382b7bef9#commitcomment-16575405).

**Comment by scottchiefbaker** [comment]
Good work team! PR submitted
