### ISSUE TITLE
No inline changes

### ISSUE THREAD

**Issue by vanniktech** [so-fancy/diff-so-fancy#112]
I can't see inline changes anymore. I'm using ohmyzsh terminal on Mac 10.11.2.

<img width="725" alt="screen shot 2016-03-06 at 13 07 06" src="https://cloud.githubusercontent.com/assets/5759366/13554004/66a1e6f4-e39c-11e5-9409-f687a086598e.png">

Git configuration looks like this:

```
[core]
	autocrlf = input
	ignorecase = false
[color]
	ui = always
[color "diff"]
	meta = yellow bold
	commit = green bold
	frag = magenta bold
	old = red bold
	new = green bold
	whitespace = red reverse
[color "diff-highlight"]
	oldNormal = red bold
	oldHighlight = "red bold 52"
	newNormal = "green bold"
	newHighlight = "green bold 22"
[color "branch"]
	current = red
	local = yellow
	remote = green
[color "status"]
	added = yellow
	changed = green
	untracked = cyan
[pager]
	diff = diff-so-fancy | less --tabs=4 -RFX
	show = diff-so-fancy | less --tabs=4 -RFX
```

This is the git diff output

> [1;33mdiff --git a/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.groovy b/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.groovy[m
[1;33mindex a8cde25..32284ef 100644[m
[1;33m--- a/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.groovy[m
[1;33m+++ b/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.groovy[m
[1;35m@@ -51,7 +51,7 @@[m [mclass CodeQualityToolsPluginExtension {[m
         boolean enabled = true[m
 [m
         /** @since 0.2.0 */[m
[1;31m-        String toolVersion = '6.14.1'[m
[1;32m+[m[1;32m        String toolVersion = '6.16.1'[m
 [m
         /** @since 0.2.0 */[m
         String configFile = 'code_quality_tools/checkstyle.xml'[m

I installed the initial version of `diff-so-fancy` with `npm` and therefore installed gnu-sed manually since it was required in version 0.1.0 (I don't know if I need it anymore or not). Later I changed to homebrew.

`brew info diff-so-fancy` gives me:

> diff-so-fancy: stable 0.5.2
Good-lookin' diffs with diff-highlight and more
https://github.com/so-fancy/diff-so-fancy
/usr/local/Cellar/diff-so-fancy/0.3.0 (4 files, 11.8K)
  Built from source
/usr/local/Cellar/diff-so-fancy/0.4.0 (4 files, 12.2K)
  Built from source
/usr/local/Cellar/diff-so-fancy/0.4.1 (4 files, 12.2K)
  Built from source
/usr/local/Cellar/diff-so-fancy/0.5.0 (4 files, 12.3K)
  Built from source
/usr/local/Cellar/diff-so-fancy/0.5.1 (4 files, 12.4K)
  Built from source
/usr/local/Cellar/diff-so-fancy/0.5.2 (6 files, 20.1K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/diff-so-fancy.rb

I also uninstalled `diff-so-fancy` from npm with `npm uninstall -g diff-so-fancy`.

What could cause the issue that I don't see inline replacements?

**Comment by paulirish** [comment]
hey thanks for the super detailed bug report. :) good stuff.

i"m not seeing anything in your screenshot that looks wrong.  what do you expect to see differently?

can you paste your output from `git --no-pager diff` ?

**Comment by vanniktech** [comment]
Well it could also be that I was confused while creating that issue but should not be the change `4` to `6` be in one line since they are both the same line?

The requested output from `git --no-pager diff`:

> [1;33mdiff --git a/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.groovy b/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.groovy[m
[1;33mindex a8cde25..32284ef 100644[m
[1;33m--- a/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.groovy[m
[1;33m+++ b/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.groovy[m
[1;35m@@ -51,7 +51,7 @@[m [mclass CodeQualityToolsPluginExtension {[m
         boolean enabled = true[m
 [m
         /** @since 0.2.0 */[m
[1;31m-        String toolVersion = '6.14.1'[m
[1;32m+[m[1;32m        String toolVersion = '6.16.1'[m
 [m
         /** @since 0.2.0 */[m
         String configFile = 'code_quality_tools/checkstyle.xml'[m

**Comment by scottchiefbaker** [comment]
@vanniktech github really mangled that output. Can you either:

1. Send the output to a file and post the file
2. Repost it in base64: `git --no-pager diff | base64`

**Comment by vanniktech** [comment]
Diff: http://pastebin.com/krXqkyuX
Diff without pager: http://pastebin.com/fwnKSQy0

Oddly there are the same :/

**Comment by scottchiefbaker** [comment]
@vanniktech ok much better output. 

Looking at this I don't see any issues with the output on this. From what I can tell diff-so-fancy is doing what it should be here. What were you expecting that you're not seeing?

**Comment by vanniktech** [comment]
Well it could also be that I was confused while creating that issue but should not be the change 4 to 6 be in one line since they are both the same line?

**Comment by paulirish** [comment]
@vanniktech what you're asking for is the output of `git diff --color-words`. it's an option for diff, so we can't set it. and TBH, it is only superior for certain sorts of diffs.. prose/readmes in particular. code, less so much

either way.. it's actually compatible with DSF. :)

![image](https://cloud.githubusercontent.com/assets/39191/13621583/761f3304-e54d-11e5-9d1f-356de2bf1c46.png)

**Comment by paulirish** [comment]
@vanniktech if you want to add this as a protip to the readme, hook us up with a PR!

**Comment by vanniktech** [comment]
Alright then sorry for the confusion. I don't think it's necessary as a pro tip to the readme since it's git specific. Anyway thanks :+1:
