### ISSUE TITLE
sed: RE error: illegal byte sequence

### ISSUE THREAD

**Issue by stribor** [so-fancy/diff-so-fancy#113]
sed: RE error: illegal byte sequence

I get this error trying to use diff-so-fancy.
text file it chokes at is iso latin encoded and has some umlauts (ü ö ..) in and and some special characters like {} % | / [ ]

**Comment by paulirish** [comment]
@stribor can you give us an example diff? 

> git --no-pager diff > illegal.diff

thx

**Comment by scottchiefbaker** [comment]
You probably want to force color. If you redirect to a file it may strip out the ANSI codes. I know on my dev box it does.

    git --no-pager diff --color > /tmp/illegal.diff

or even better (preserve non-latin chars)

    git --no-pager diff --color | base64 > /tmp/illegal.diff

**Comment by stribor** [comment]
The commit was converting text file character encoding from iso latin to utf-8, I extracted small portion of it to show the problem

[diff.txt](https://github.com/so-fancy/diff-so-fancy/files/164029/diff.txt)

in iso latin version ü was encoded as 0xFC and in utf-8 version as 2 bytes: 0xC3 0xBC

might be of interest: [Specials (Unicode block)](https://en.wikipedia.org/wiki/Specials_%28Unicode_block%29)

**Comment by scottchiefbaker** [comment]
I understand why this bug would be occurring, but I can't reproduce it with my dev environment. If I pass the diff you posted through d-s-f I don't get any sed errors.

```
bakers@yellow(~/github/diff-so-fancy)
:sed --version
sed (GNU sed) 4.2.2
```

What version of sed are you running, and on what OS?

**Comment by scottchiefbaker** [comment]
Perl has a regexp modifier `/u` to force unicode mode. Maybe we need to use that in our sed calls also? Or maybe we need to move more of the logic in to Perl to avoid some of this.

**Comment by stribor** [comment]
I'm on OS X, which has BSD sed,
from man page bugs section (I added bold as wild guess) :
     Multibyte characters containing a byte with value 0x5C (ASCII `\') may be incorrectly treated as line continuation characters in arguments to the ``a'',
     ``c'' and ``i'' commands.  **Multibyte characters cannot be used as delimiters with the ``s'' and ``y'' commands.**

**Comment by scottchiefbaker** [comment]
I don't have OS X to test against, but I'm pretty sure @paulirish does. Are you able to reproduce this @paulirish?

**Comment by paulirish** [comment]
I fell back to an earlier version and can reproduce this:
![image](https://cloud.githubusercontent.com/assets/39191/13621372/1473ef74-e54c-11e5-929a-8b4e392173d6.png)


however on v0.5.2 and v0.6.0 (which is now our primary release), it's not erroring:

![image](https://cloud.githubusercontent.com/assets/39191/13621399/3f15097a-e54c-11e5-858d-96e2c5cf4905.png)


so.. update to the latest and it wont be broken, at least. :)

we can file a separate issue for fixing any rendering of particular encodings, though i'm mostly out of my depth there.

**Comment by stribor** [comment]
I still get it with latest version (also had it with v0.5.2) under mac os 10.11
![screen shot 2016-03-09 at 8 12 35 am](https://cloud.githubusercontent.com/assets/1141923/13628000/ebafc31e-e5ce-11e5-84b0-1a1df0d4f286.png)

**Comment by paulirish** [comment]
we're now at 0.6.2.  homebrew is a bit behind our npm distribution.

**Comment by stribor** [comment]
same thing still happens with 0.6.2
