### ISSUE TITLE
perl critic in CI

### ISSUE THREAD

**Issue by paulirish** [so-fancy/diff-so-fancy#118]
we have shellcheck running against our bash, which is great.

I think we should also make sure perlcritic exits without error in our tests. probably can help catch issues.

I've found a few projects that do this.
* [ack2/.travis.yml](https://github.com/petdance/ack2/blob/ec4909776b21ac22546275480770a1cbc800c4ec/.travis.yml) installs from cpan without tests (seems good). the makefile is pretty wild though.
* [binary-com/perl-VolSurface-Utils](https://github.com/binary-com/perl-VolSurface-Utils/commit/5e42217f40df9ee5c8a7f86d54c7eef694d4cae1) added things in one go.

we're in no rush for this, but it'll be cool moving forward.

**Comment by scottchiefbaker** [comment]
:+1:

**Comment by maxnordlund** [comment]
I think this is done.
