### ISSUE TITLE
Use of uninitialized value $new_offset in addition (+) at /GitHub/diff-so-fancy/libs/header_clean/header_clean.pl line 75, <> line 63.

### ISSUE THREAD

**Issue by stevemao** [so-fancy/diff-so-fancy#119]
In this repo, do

```
git  show  74804e377d4a54d1173d4393827d4e4b27e4d5d0
Use of uninitialized value $new_offset in addition (+) at /GitHub/diff-so-fancy/libs/header_clean/header_clean.pl line 75, <> line 63.
Use of uninitialized value $new_offset in addition (+) at /GitHub/diff-so-fancy/libs/header_clean/header_clean.pl line 75, <> line 63.
```

`git --no-pager show 74804e377d4a54d1173d4393827d4e4b27e4d5d0 | base64`
Y29tbWl0IDc0ODA0ZTM3N2Q0YTU0ZDExNzNkNDM5MzgyN2Q0ZTRiMjdlNGQ1ZDAKTWVyZ2U6IDNmYjdjZDcgNTlhZWJiZApBdXRob3I6IFBhdWwgSXJpc2ggPHBhdWwuaXJpc2hAZ21haWwuY29tPgpEYXRlOiAgIFR1ZSBNYXIgOCAxNTo1Njo0OSAyMDE2IC0wODAwCgogICAgTWVyZ2UgcHVsbCByZXF1ZXN0ICMxMTAgZnJvbSBwYXVsaXJpc2gvaHVua3N0YXJ0bGluZWZpeAogICAgCiAgICBDaGFuZ2UgaHVuayBsaW5lIHBvc2l0aW9uOiBvcmlnaW5hbCAtLT4gcmVzdWx0IGxvY2F0aW9uCgpkaWZmIC0tY2MgbGlicy9oZWFkZXJfY2xlYW4vaGVhZGVyX2NsZWFuLnBsCmluZGV4IGU4YmNkOTIsNTk3MDU4MC4uYWUyNzlkMAotLS0gbGlicy9oZWFkZXJfY2xlYW4vaGVhZGVyX2NsZWFuLnBsCisrKyBsaWJzL2hlYWRlcl9jbGVhbi9oZWFkZXJfY2xlYW4ucGwKQEBAIC0xMDUsMTMgLTEwNCwyMSArMTA0LDIzIEBAQCBmb3IgKG15ICRpID0gMDsgJGkgPD0gJCNpbnB1dDsgJGkrKykgCiAgCX0KICB9CiAgCisgIyBDb3VydGVzeSBvZiBnaXRodWIuY29tL2dpdC9naXQvYmxvYi9hYjVkMDFhL2dpdC1hZGQtLWludGVyYWN0aXZlLnBlcmwjTDc5OC1MODA1Cisgc3ViIHBhcnNlX2h1bmtfaGVhZGVyIHsKKyAgICAgbXkgKCRsaW5lKSA9IEBfOworICAgICBteSAoJG9fb2ZzLCAkb19jbnQsICRuX29mcywgJG5fY250KSA9CisgICAgICAgICAkbGluZSA9fiAvXkBAIC0oXGQrKSg/OiwoXGQrKSk/IFwrKFxkKykoPzosKFxkKykpPyBAQC87CisgICAgICRvX2NudCA9IDEgdW5sZXNzIGRlZmluZWQgJG9fY250OworICAgICAkbl9jbnQgPSAxIHVubGVzcyBkZWZpbmVkICRuX2NudDsKKyAgICAgcmV0dXJuICgkb19vZnMsICRvX2NudCwgJG5fb2ZzLCAkbl9jbnQpOworIH0KKyAKICBzdWIgc3RyaXBfZW1wdHlfZmlyc3RfbGluZSB7CiAtCW15ICRmb28gPSBzaGlmdCgpOyAjIEFycmF5IHBhc3NlZCBpbiBieSByZWZlcmVuY2UKICsJbXkgJGFycmF5ID0gc2hpZnQoKTsgIyBBcnJheSBwYXNzZWQgaW4gYnkgcmVmZXJlbmNlCiAgCiAgCSMgSWYgdGhlIGZpcnN0IGxpbmUgaXMganVzdCB3aGl0ZXNwYWNlIHJlbW92ZSBpdAogLQlpZiAoZGVmaW5lZCgkZm9vLT5bMF0pICYmICRmb28tPlswXSA9fiAvXlxzKiQvKSB7CiAtCQlzaGlmdCgkZm9vKTsKICsJaWYgKGRlZmluZWQoJGFycmF5LT5bMF0pICYmICRhcnJheS0+WzBdID1+IC9eXHMqJC8pIHsKICsJCXNoaWZ0KEAkYXJyYXkpOyAjIFRocm93IGF3YXkgdGhlIGZpcnN0IGxpbmUKICAJfQogKwogKwlyZXR1cm4gMTsKICB9CmRpZmYgLS1jYyB0ZXN0L2hlYWRlcl9jbGVhbi5iYXRzCmluZGV4IDc4OWM0NTEsNjU5ZWNjMS4uYTAwZDM1ZAotLS0gdGVzdC9oZWFkZXJfY2xlYW4uYmF0cworKysgdGVzdC9oZWFkZXJfY2xlYW4uYmF0cwpAQEAgLTQ4LDEwIC00OCwxMCArNDgsMTUgQEBAIG91dHB1dD0kKCBsb2FkX2ZpeHR1cmUgImZpbGUtbW92ZXMiIHwgJAogIEB0ZXN0ICJSZXdvcmtlZCBodW5rcyAobm9wcmVmaXgpIiB7CiAgCW91dHB1dD0kKCBsb2FkX2ZpeHR1cmUgIm5vcHJlZml4IiB8ICRkaWZmX3NvX2ZhbmN5ICkKICAJYXNzZXJ0X291dHB1dCAtLXBhcnRpYWwgJ0Agc2V0dXAtYS1uZXctbWFjaGluZS5zaDozMyBAJwotIAlhc3NlcnRfb3V0cHV0IC0tcGFydGlhbCAnQCBzZXR1cC1hLW5ldy1tYWNoaW5lLnNoOjIxOCBAJworIAlhc3NlcnRfb3V0cHV0IC0tcGFydGlhbCAnQCBzZXR1cC1hLW5ldy1tYWNoaW5lLnNoOjIxOSBAJworIH0KKyAKKyBAdGVzdCAiUmV3b3JrZWQgaHVua3MgKGRlbGV0ZWQgZmlsZXMpIiB7CisgCW91dHB1dD0kKCBsb2FkX2ZpeHR1cmUgImRvdGZpbGVzIiB8ICRkaWZmX3NvX2ZhbmN5ICkKKyAJYXNzZXJ0X291dHB1dCAtLXBhcnRpYWwgJ0AgZGlmZi1zby1mYW5jeTozIEAnCiAgfQogKwogK0B0ZXN0ICJtbmVtb25pY3ByZWZpeCBoYW5kbGluZyIgewogKwlvdXRwdXQ9JCggbG9hZF9maXh0dXJlICJtbmVtb25pY3ByZWZpeCIgfCAkZGlmZl9zb19mYW5jeSApCiArCWFzc2VydF9vdXRwdXQgLS1wYXJ0aWFsICdtb2RpZmllZDogdGVzdC9oZWFkZXJfY2xlYW4uYmF0cycKICt9Cg==

[output.txt](https://github.com/so-fancy/diff-so-fancy/files/164775/output.txt)

**Comment by scottchiefbaker** [comment]
@paulirish #122 does fix this issue. Also, all the existing tests pass with that fix also.

Should be pretty simple to add a test for:

 `@@@ -105,13 -104,21 +104,23 @@@` parsing to `@ header_clean.pl:107 @`

**Comment by paulirish** [comment]
reopening until we have a test added.

**Comment by stevemao** [comment]
Hmmm.. I actually wanted #126 to be fixed. Linking the issue for posterity :)
