### ISSUE TITLE
Changing the "meta" color reverts the divider to the default style

### ISSUE THREAD

**Issue by scottchiefbaker** [so-fancy/diff-so-fancy#12]
I'm using the suggested defaults (see below) and I wanted to change the `meta` color to just yellow (not bold). Setting it to `yellow` gives me a brownish color, so I used `11` instead. This gives me the color I want, but reverts the style of the header to the old raw diff style.

```
[color "diff"]
    meta = yellow bold
    commit = green bold
    frag = magenta bold
    old = red bold
    new = green bold
    whitespace = red reverse
[color "diff-highlight"]
    oldNormal = red bold
    oldHighlight = red bold 52
    newNormal = green bold
    newHighlight = green bold 22
```

**Comment by paulirish** [comment]
before/after screenshots plz?

**Comment by aziz** [comment]
Did you try to put qoutes around it 
```
whitespace = "red reverse"
```
It still does not fix the issue completely but that's another story
<img width="387" alt="screen shot 2016-02-09 at 9 12 55 pm" src="https://cloud.githubusercontent.com/assets/3202/12929227/e9bafe0c-cf71-11e5-8d1b-3eb73aad9512.png">

**Comment by scottchiefbaker** [comment]
With `meta = yellow bold`

![one](https://cloud.githubusercontent.com/assets/3429760/12930578/f2308758-cf2d-11e5-883d-d63da1eaf222.png)

With `meta = 11`

![two](https://cloud.githubusercontent.com/assets/3429760/12930577/f19d13c4-cf2d-11e5-9fa0-3dbc9fb0c01f.png)

**Comment by mhinz** [comment]
Yea, it seems to only take color numbers 0 - 8 into account.

**Comment by paulirish** [comment]
Gotcha. This is a good bug, and something we can now add a test for. 

If anyone wants to take a look, you're more than welcome!

**Comment by cht8687** [comment]
@scottchiefbaker 
I am not sure if it is only me, but in my Terminal, I didn't experience the issue which you got: ( only difference is the line changed to dash line)

with `meta = yellow bold`

![image](https://cloud.githubusercontent.com/assets/4587603/13074377/4dadb194-d4f8-11e5-85d2-b9751fe9195e.png)



with `meta = 11`

![image](https://cloud.githubusercontent.com/assets/4587603/13074370/497ee048-d4f8-11e5-8edd-65245444c6b1.png)

**Comment by mhinz** [comment]
FWIW, on master (642dd24) everything is working for me now.

Tested config:

```
[color]
    branch      = auto
    diff        = auto
    interactive = auto
    status      = auto
    ui          = auto

[color "diff"]
    frag       = 104
    func       = 74
    meta       = 11
    new        = 114
    old        = 167
    plain      = 240
    whitespace = 24 24

[color "status"]
    header = 240
    branch = yellow
```

**Comment by scottchiefbaker** [comment]
Master does indeed fix this issue. Not sure what commit, but it's fixed. Good work everyone.

**Comment by OJFord** [comment]
>  Setting it to yellow gives me a brownish color, so I used 11 instead.

Note also that the ANSI colour 'yellow' (etc.) actually is, is terminal-defined. In some (most?) cases you'll be able to change this in settings; so if you don't like the brown-ish colour, or wouldn't recognise it as being yellow when used elsewhere, you can (and maybe should) change it.
