### ISSUE TITLE
Should diff-so-fancy work on non-colored diffs?

### ISSUE THREAD

**Issue by scottchiefbaker** [so-fancy/diff-so-fancy#124]
Before I go too far down this rabbit hole... are we supporting diffs that are not colored? I found a bug in a black and white diff that I might look at fixing, if we support that.

**Comment by paulirish** [comment]
Good question. 

it looks like we mostly work right now even when there's no color.

if colors are forced to "never", diff-highlight does a b/w job: 

![image](https://cloud.githubusercontent.com/assets/39191/13648435/6ccbd532-e5ed-11e5-8dd9-6438a2c2d95a.png)

but default is that there are colors, just not shared into pipes. pipes needs "always"

I don't think it's worth it to support uncolored output.

Maybe a nice solution is that we sniff for if color was enabled.. and if it wasn't we quit DSF entirely.

**Comment by stevemao** [comment]
@scottchiefbaker what is the bug exactly? I think we should only process whatever diff-highlight outputs.

**Comment by scottchiefbaker** [comment]
I was wrong... the bug was three-way merge, not black and white. I'll close this for now, but it's something we should consider in the future.
