### ISSUE TITLE
Support 3-way merge commits

### ISSUE THREAD

**Issue by paulirish** [so-fancy/diff-so-fancy#126]
Currently DSF doesn't correctly format output when viewing 3-way merge commits. There shouldn't be errors, but we misformat the diff, as there can be an extra layer of indentation.

Example: 
<a href="https://cloud.githubusercontent.com/assets/39191/13648024/a3fbad72-e5eb-11e5-8921-7dc211648209.png"><img src="https://cloud.githubusercontent.com/assets/39191/13648024/a3fbad72-e5eb-11e5-8921-7dc211648209.png" height=400></a>

## Impact
* **`git show` on merge commits**
 * example: `git show 74804e377` in the DSF repo.
* **`git diff` across a merge commit (sometimes)**
  * example: ` git diff 91bc769c02  59aebbd379 `  or just `git diff 59aebbd379` 
* **NOT `git diff` on (unstaged) changes**
  * afaik, impossible. So our exposure to this bug is limited.

We discussed this a bit more over in scott's fork: https://github.com/scottchiefbaker/diff-so-fancy/pull/1#issuecomment-194506753 

06b9421b814d80216d7f8a74621aba4b4979a1db provides a test we can use once we're ready to fix this.

<hr>

Currently, we've decided to defer and address this bug later.

**Comment by lode** [comment]
As far as I know this more commonly happens with:

- `git diff` after ending up in a merge conflict
- `git diff` after ending up in a stash pop conflict

**Comment by stevemao** [comment]
Just to summarise the discussion in scott's fork, there might be an n-way merge :) So all we need to do is to count how many number sequences in the header between `@@@`s

Git is really crazy... I wonder how many people actually cares about n-way merge and count the beginning spaces. lol

**Comment by lode** [comment]
But how do you want to solve it? It is not really nice to remove the +/- signs as we do with normal diffs.
Maybe DSF should even revert to removing them at all for n-way merges? So by default they are hidden, and for n-way merges, all are shown as normal.

**Comment by paulirish** [comment]
git doesn't support 4 way merge, so the 3 way is the most complex we'll
have to deal with.

**Comment by scottchiefbaker** [comment]
If there is a three way merge, will the entire diff be a three-way merge? Or is is possible to have ONE file be a three way merge, and another file just be a two-way merge? I'm going to tackle this today, shouldn't be too gnarly.

**Comment by paulirish** [comment]
scott is this good to close now?
