### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by ephexeve** [so-fancy/diff-so-fancy#127]
For those interested, I have created a package for Debian (currently tested on the current Testing version). You can find the package [here](https://code.benmezger.nl/?p=deb-packages.git;a=tree;f=misc/diff-so-fancy;h=bccfd5f3ebbd54b87736cf8dde52932b8586fd01;hb=HEAD)

**Comment by scottchiefbaker** [comment]
:+1:

**Comment by stevemao** [comment]
Nice. @ephexeve Can you add installation guide here?
Thanks

**Comment by ephexeve** [comment]
Sure!

To install the package I created:
1. Make sure you verify the git commit using my [PGP public key](http://hkps.pool.sks-keyservers.net/pks/lookup?op=get&search=0xF2403AC05942EE08) doing a `git log --show-signature` (in case of laziness: `shasum 256: 745bb25bcb00aa00b837be678942332448fef877df522b011d367efed1f9a01d`) 
2. run `sudo dpkg -i diff-so-fancy_0.6.3.deb`

To build your custom package:
1. `cd src/` and run `dpkg-deb --build diff-so-fancy_0.6.3`
2. `sudo dpkg -i diff-so-fancy_0.6.3.deb`

Currently I am building the packages according to newer tag release.
I've submit a request on Debian asking if `diff-so-fancy` can be accepted in their repository database, I will keep you guys updated on how that goes, but I doubt it they will accept it :(.

Meanwhile, I am wondering if we can put this `.deb` package to the [readme.md](https://github.com/so-fancy/diff-so-fancy/blob/master/readme.md) install guide for Debian (I am also assuming this works on any Ubuntu version, but someone would have to test that out and let me know if it does!).

**Comment by stevemao** [comment]
@ephexeve I pull-request would be great :)
