### ISSUE TITLE
Whole diff is not displayed (it's cut off)

### ISSUE THREAD

**Issue by adzenith** [so-fancy/diff-so-fancy#133]
I have a diff that's 117,038 lines (adding an SDK). Diff-so-fancy cuts out mid-file after line 4312, which in this case works out to 258,737 characters. Any ideas?

**Comment by scottchiefbaker** [comment]
There is not automatic cut-off. If anything it would just be really slow parsing all that raw text. My guess would be that there is some of content that's making dsf barf near that line. Is the diff something that you can post so we can look at it?

**Comment by adzenith** [comment]
I can post the output of `git-show`—would that be useful?

**Comment by scottchiefbaker** [comment]
Can you disable d-s-f and then do a `git show --color > broken-diff.raw` and then post that somewhere I can look at it. That will preserve the ansi-codes so I can see it all together.

**Comment by adzenith** [comment]
https://www.dropbox.com/s/yecq9n79xdffroo/broken-diff.raw?dl=0

**Comment by scottchiefbaker** [comment]
Is this run through `diff-highlight` or something similar it doesn't look like raw `git show` output. The diff headers are blue/gray?

**Comment by scottchiefbaker** [comment]
That diff is 131451 lines raw. If I pass it through d-s-f it takes 3.82 seconds and outputs 131969 lines. All of that seems normal to me. In other words "it's not breaking for me". Can you tell me more about your platform? Can you give us the versions of: OS, Perl, Bash, and Git?

**Comment by stevemao** [comment]
@adzenith Can you run the command provided in https://github.com/so-fancy/diff-so-fancy#reporting-bugs?

**Comment by adzenith** [comment]
Hey! Sorry I lost track of this. Here's the file it created:
https://www.dropbox.com/s/eevcyikl1dly2sk/diff.txt?dl=0
The output in that file appears to have more of the diff than shows when I run the command myself in the terminal: https://www.dropbox.com/s/xh0aefk68zpnnux/terminal.png?dl=0

OS: OS X 10.11.4 Beta (15E61b)
Perl: v5.18.2
Bash: 3.2.57(1)-release
Git: 2.7.4

**Comment by scottchiefbaker** [comment]
It looks like your running pretty modern tools (that's good). I don't think your tool versions are the issue.

I'm unable to recreate this failure, is anyone else able to recreate?

**Comment by adzenith** [comment]
Sadly this is still happening to me :( Any other details that might help?

**Comment by paulirish** [comment]
Can't repro. :/


```sh
# download the diff.txt

cat diff\ \(1\).txt | diff-so-fancy | less --tabs=4 -RFX

hit G to jump to to end.
```

![image](https://cloud.githubusercontent.com/assets/39191/15259188/a33e7bb6-1904-11e6-8817-409c538ecdc5.png)

##### software:
* os x 10.11.4 (15E65)
* perl v5.18.2
* bash 4.3.42(1)-release
* git 2.7.2

Also tested with fish version 2.2.0-436-gef67fc7. same experience.

**Comment by adzenith** [comment]
How strange... I'll let you know if I figure anything else out!

**Comment by scottchiefbaker** [comment]
@adzenith looks like you're just special :)

What is your use case for wanting d-s-f when you're adding this much text? Are you really going to read it all, or is this just to see if it works?

**Comment by adzenith** [comment]
Aw I'm special! 🌟  :)

I had d-s-f set up as my default pager, so whenever I view any amount of text it was being processed through it. This particular diff was updating an SDK so it was quite large. Most of the time d-s-f is amazing, but every once in a long while I get really confused when a search through a diff doesn't produce any results because it was cut off.

**Comment by stevemao** [comment]
screenshots? @adzenith

**Comment by adzenith** [comment]
I put up a screenshot on Mar 22— https://www.dropbox.com/s/xh0aefk68zpnnux/terminal.png?dl=0. Anything else in particular I could show?

**Comment by stevemao** [comment]
Oh Sorry didn't see it :) I'll post it here.
![image](https://cloud.githubusercontent.com/assets/6316590/15307428/36382df4-1c16-11e6-9ac6-845ac09ae618.png)

**Comment by scottchiefbaker** [comment]
@adzenith is this still an issue? I wonder if it's related to #165

**Comment by adzenith** [comment]
Yes it is related! I just tried again with my old version 0.9.x and got this same problem. After upgrading to 0.10.0 I'm able to view the whole diff. It barfs messages like:
`"\x{0092}" does not map to utf8 at /usr/local/Cellar/diff-so-fancy/0.10.0/libexec/diff-so-fancy.pl line 150, <> line 14081.`
but it still shows me everything. Back to using `diff-so-fancy`! Thanks so much!

**Comment by scottchiefbaker** [comment]
Ok great news. That was a weird bug, I'm glad we finally narrowed it down.

**Comment by adzenith** [comment]
Thanks! 👍
