### ISSUE TITLE
Failed to parse this diff, error is fileparse(): need a valid pathname

### ISSUE THREAD

**Issue by lilydjwg** [so-fancy/diff-so-fancy#137]
```diff
diff -r 62e478a3f1c8 -r 47aeb87ce9cd doc/manual.xml.head
--- a/doc/manual.xml.head
+++ b/doc/manual.xml.head
@@ -8352,7 +8352,7 @@
 <row><entry>-a</entry><entry>attach a file to a message</entry></row>
 <row><entry>-b</entry><entry>specify a blind carbon-copy (BCC) address</entry></row>
 <row><entry>-c</entry><entry>specify a carbon-copy (Cc) address</entry></row>
-<row><entry>-d</entry><entry>log debugging output to ~/.muttdebug0 if mutt was complied with +DEBUG; it can range from 1-5 and affects verbosity (a value of 2 is recommended)</entry></row>
+<row><entry>-d</entry><entry>log debugging output to ~/.muttdebug0 if mutt was compiled with +DEBUG; it can range from 1-5 and affects verbosity (a value of 2 is recommended)</entry></row>
 <row><entry>-D</entry><entry>print the value of all Mutt variables to stdout</entry></row>
 <row><entry>-E</entry><entry>edit the draft (-H) or include (-i) file</entry></row>
 <row><entry>-e</entry><entry>specify a config command to be run after initialization files are read</entry></row>
```

colordiff can do with it, but diff-so-fancy fails with:

```
Use of uninitialized value $_[0] in substitution (s///) at /usr/share/perl5/core_perl/File/Basename.pm line 341, <> line 14.
fileparse(): need a valid pathname at /usr/share/diff-so-fancy/diff-so-fancy.pl line 74.
```

**Comment by scottchiefbaker** [comment]
It's because of this diff header:

    diff -r 62e478a3f1c8 -r 47aeb87ce9cd doc/manual.xml.head

What git command did you run to get a diff header like that? Our detection looks like this:

https://github.com/so-fancy/diff-so-fancy/blob/master/lib/diff-so-fancy.pl#L28

**Comment by scottchiefbaker** [comment]
@paulirish, @stevemao is diff-so-fancy git specific? Should we look at supporting standard `diff -u` diffs at some level? I have a minor fix queued that addresses this issue, as well as `diff -u` as well. I'm not sure if it's within the scope of this project.

It's a minor 13 line fix if we want to support/work around this non-standard diff output.

**Comment by lilydjwg** [comment]
It's not from git, it's from a maillist. Maybe it's generated by hg. It's not easy to find where the difference is so I tried diff-so-fancy.

**Comment by stevemao** [comment]
I don't understand. So the `.diff` file is not generated by git? I don't think we should support any arbitrary `.diff` files

**Comment by lilydjwg** [comment]
Sorry, I didn't think diff-so-fancy is a git only tool, as I didn't encounter a diff that colordiff, wdiff, patch or git apply don't support.

**Comment by stevemao** [comment]
@lilydjwg in short, we only supports things that `diff-highlight` supports. Nothing more :)
cc @paulirish

**Comment by scottchiefbaker** [comment]
I think we can modify d-s-f to support raw diffs pretty easily. I think "officially" this is a git tool, but unofficially it could be used on standalone diffs. @lilydjwg has the perfect use case for this type of application.

Unless there are any specific objections, I think I'll land the fix for this use case tomorrow.

**Comment by stevemao** [comment]
@scottchiefbaker if so, we should probably split `lib/diff-so-fancy.pl` into smaller modules.
