### ISSUE TITLE
'trailing spaces warning' looks like deletion

### ISSUE THREAD

**Issue by OJFord** [so-fancy/diff-so-fancy#145]
By default (?) whitespace on an otherwise blank line is highlighted red.

Though this may well be a slightly different colour (indeed it is with git and DSF defaults), it's easy to confuse with a deletion.

Suggestion: colour it green - it's an addition after all!
Problem: suggestion indistinguishable from present newline representation when only one space.

This could perhaps be solved by inserting characters to represent the whitespace? Slightly breaks the copy-paste ability, but then I'm not sure when this errant whitespace would actually be desirable.

**Comment by scottchiefbaker** [comment]
If you do

    git show 22b045fbfa871e6a86ef4e72164e009754ea7d56

On the diff-so-fancy repo that should contain "added" empty lines, and they should be highlighted green. Is that what you're trying to report.

**Comment by OJFord** [comment]
@scottchiefbaker No - an _added_ line with trailing whitespace has _red_ highlighted whitespace (as a warning that you probably didn't mean to do this) by git.

This is similar enough to `diff-highlight`s red (and could be identical if so configured) that it could be confused for _deleted_ whitespace.

I'm not sure if there's a way to override this, or if the best we could do would be to advise users to change the colour in config. If it's possible to do so though, my suggestion would be to make it consistent with other additions; green.

**Comment by scottchiefbaker** [comment]
Can you give us an example screen shot? One with raw `git diff --color` and another one piped through d-s-f?

**Comment by stevemao** [comment]
@OJFord 
Is it the same as #85?
Does Jeff's answer make sense to you?

**Comment by OJFord** [comment]
@stevemao Ah, probably the same cause - I was seeing it on otherwise empty lines so I didn't make the connection.

@scottchiefbaker 
![spaces](https://cloud.githubusercontent.com/assets/3946014/14311374/e9763396-fbde-11e5-8a19-b04aa479d46a.png)
(Excuse the odd symbols, haven't fixed the font on this machine yet!)

With/out DSF is no different, since git does this. My point in opening the issue was that alongside other behaviour (actually diff-highlight's) it's quite confusing: I've _added_ whitespace, not deleted it.

There's perhaps a config option for the colour of this specifically, in which case the fix would be as simple as to encourage setting that the same as rm highlighting, but I haven't had a chance to look into that.

**Comment by OJFord** [comment]
@stevemao Actually yes, re-reading that - it's exactly the same and that makes sense.

It's a shame, but it makes sense.
