### ISSUE TITLE
Recognize PGP signature block

### ISSUE THREAD

**Issue by wzyboy** [so-fancy/diff-so-fancy#148]
Signed tags contain PGP blocks, which start with `-----BEGIN PGP SIGNATURE-----` . With diff-so-fancy enabled, the one of the five dashes (and lines starting with `+`s) would be mis-recognized as a part of diff:

![screenshot_2016-04-06_15-33-10](https://cloud.githubusercontent.com/assets/459384/14309155/30d28ec8-fc0d-11e5-8eaf-42e423b8b571.png)

In the screenshot above, the header and footer of the signature block, as well as a line starting with `+` (`+z9g14nh[...]`) are mis-recognized as diffs.

**Comment by wzyboy** [comment]
Ah, I see this was fixed in https://github.com/so-fancy/diff-so-fancy/commit/c3a141b7e60c597a38426fa709b6a0e3bd7fe766 . Updated and everything works! Sorry for bothering.

**Comment by scottchiefbaker** [comment]
Glad we could help!

@blueyed you solved a problem I didn't know we were having.
