### ISSUE TITLE
Show JSON diffs for JSON files

### ISSUE THREAD

**Issue by mohsen1** [so-fancy/diff-so-fancy#150]
JSON diff is easier to digest than text diff for JSON files.

### Text diff
![screen shot 2016-04-12 at 1 48 23 pm](https://cloud.githubusercontent.com/assets/543633/14475145/5270b77e-00b5-11e6-8c31-58ea1dbe2b71.png)

### JSON Diff
![screen shot 2016-04-12 at 1 48 13 pm](https://cloud.githubusercontent.com/assets/543633/14475149/58e561ea-00b5-11e6-9c46-118b7f2bcdfe.png)

Can diff-so-fancy detect JSON files and uses a JSON diff for them instead?

I used this differ for my example: 
https://github.com/benjamine/jsondiffpatch

**Comment by stevemao** [comment]
I didn't know `jsondiffpatch` before. Thanks for the recommendation :) I think we could add a link to that and add a script how you can use it with our module to README.

**Comment by paulirish** [comment]
Hey man! Good to see you around these parts. :)

I actually find this diff harder to read.. The version bumps in partially

**Comment by paulirish** [comment]
Amended comment
