### ISSUE TITLE
add documentation for gitconfig

### ISSUE THREAD

**Issue by paulirish** [so-fancy/diff-so-fancy#151]
Now that https://github.com/so-fancy/diff-so-fancy/pull/141 is landed, lets get the docs added to the readme, so people know how to use it!  

```
diff-so-fancy.changeHunkIndicators
diff-so-fancy.stripLeadingSymbols
diff-so-fancy.markEmptyLines
```

they are all true by default, should be set to false to disable.

**Comment by stevemao** [comment]
Hi @paulirish , I've added some docs on this. Feel free to suggest changes :) thanks.

**Comment by paulirish** [comment]
well done! lgtm
