### ISSUE TITLE
These two doesn't work properly for me

### ISSUE THREAD

**Issue by stevemao** [so-fancy/diff-so-fancy#157]
![screen shot 2016-05-22 at 11 48 10 pm](https://cloud.githubusercontent.com/assets/6316590/15454282/c2aebd1a-2077-11e6-8923-682cc8d609bb.png)

all configs are default.

Z2l0IGRpZmYKZGlmZiAtLWdpdCBpbmRleC5jc3MgaW5kZXguY3NzCmluZGV4IDkzYWFjMjYuLjc0NzZjMjAgMTAwNjQ0Ci0tLSBpbmRleC5jc3MKKysrIGluZGV4LmNzcwpAQCAtMSArMSwyIEBACiBmZXdmZXdpam9mb2V3amZpb2V3amZpb3dlZmppb3dlamZpZXdvagorZmV3ZmV3ZmV3ZmV3ZgpkaWZmIC0tZ2l0IGluZGV4Lmh0bWwgaW5kZXguaHRtbAppbmRleCBlNjlkZTI5Li4xOTBhMTgwIDEwMDY0NAotLS0gaW5kZXguaHRtbAorKysgaW5kZXguaHRtbApAQCAtMCwwICsxIEBACisxMjMKCgoKZ2l0IGRpZmYgLS1jb2xvcgobWzE7MzNtZGlmZiAtLWdpdCBpbmRleC5jc3MgaW5kZXguY3NzG1ttChtbMTszM21pbmRleCA5M2FhYzI2Li43NDc2YzIwIDEwMDY0NBtbbQobWzE7MzNtLS0tIGluZGV4LmNzcxtbbQobWzE7MzNtKysrIGluZGV4LmNzcxtbbQobWzE7MzVtQEAgLTEgKzEsMiBAQBtbbQogZmV3ZmV3aWpvZm9ld2pmaW9ld2pmaW93ZWZqaW93ZWpmaWV3b2obW20KG1szMm0rG1ttG1szMm1mZXdmZXdmZXdmZXdmG1ttChtbMTszM21kaWZmIC0tZ2l0IGluZGV4Lmh0bWwgaW5kZXguaHRtbBtbbQobWzE7MzNtaW5kZXggZTY5ZGUyOS4uMTkwYTE4MCAxMDA2NDQbW20KG1sxOzMzbS0tLSBpbmRleC5odG1sG1ttChtbMTszM20rKysgaW5kZXguaHRtbBtbbQobWzE7MzVtQEAgLTAsMCArMSBAQBtbbQobWzMybSsbW20bWzMybTEyMxtbbQpnaXQgY29uZmlnIHBhZ2VyLmRpZmYKZGlmZi1zby1mYW5jeSB8IGxlc3MgLS10YWJzPTEsNSAtUkZYCmdpdCBjb25maWcgcGFnZXIuc2hvdwpkaWZmLXNvLWZhbmN5IHwgbGVzcyAtLXRhYnM9MSw1IC1SRlgK

Z2l0IHNob3cgSEVBRApjb21taXQgMDI4NzkwNmEyNzQ3ZWYzNWZmZDVlY2ZkNjQ0ZTQ5NGMxYzQwZTk2MQpBdXRob3I6IFN0ZXZlIE1hbyA8bWFvY2hlbnlhbkBnbWFpbC5jb20+CkRhdGU6ICAgU3VuIE1heSAyMiAyMzozNjoxMCAyMDE2ICsxMDAwCgogICAgZWRpdCBhZ2FpbgoKZGlmZiAtLWdpdCBhLnBkZiBhLnBkZgppbmRleCBkZjliNWQyLi41OWZlYmZkIDEwMDY0NApCaW5hcnkgZmlsZXMgYS5wZGYgYW5kIGEucGRmIGRpZmZlcgoKCgpnaXQgc2hvdyBIRUFEIC0tY29sb3IKG1szM21jb21taXQgMDI4NzkwNmEyNzQ3ZWYzNWZmZDVlY2ZkNjQ0ZTQ5NGMxYzQwZTk2MRtbbQpBdXRob3I6IFN0ZXZlIE1hbyA8bWFvY2hlbnlhbkBnbWFpbC5jb20+CkRhdGU6ICAgU3VuIE1heSAyMiAyMzozNjoxMCAyMDE2ICsxMDAwCgogICAgZWRpdCBhZ2FpbgoKG1sxOzMzbWRpZmYgLS1naXQgYS5wZGYgYS5wZGYbW20KG1sxOzMzbWluZGV4IGRmOWI1ZDIuLjU5ZmViZmQgMTAwNjQ0G1ttCkJpbmFyeSBmaWxlcyBhLnBkZiBhbmQgYS5wZGYgZGlmZmVyCmdpdCBjb25maWcgcGFnZXIuZGlmZgpkaWZmLXNvLWZhbmN5IHwgbGVzcyAtLXRhYnM9MSw1IC1SRlgKZ2l0IGNvbmZpZyBwYWdlci5zaG93CmRpZmYtc28tZmFuY3kgfCBsZXNzIC0tdGFicz0xLDUgLVJGWAo=

**Comment by scottchiefbaker** [comment]
Are these still issues with the latest version?

**Comment by scottchiefbaker** [comment]
Ping @stevemao

**Comment by stevemao** [comment]
Sorry, I'll have a look

**Comment by scottchiefbaker** [comment]
@stevemao can you test this with v1.2.0?

**Comment by stevemao** [comment]
I don't have the original diff but I tried to replicate this https://github.com/stevemao/diff-so-fancy-test/commit/38c4609990d382314de9ba7144b75bc3a19ebc6f
Looks working now. Thanks!

**Comment by scottchiefbaker** [comment]
Another bug bites the dust!
