### ISSUE TITLE
encoding problems diffing latin1 text

### ISSUE THREAD

**Issue by adagios** [so-fancy/diff-so-fancy#165]
Hey, I'm getting `utf8 "\xE9" does not map to Unicode at /usr/local/Cellar/diff-so-fancy/0.9.3/libexec/diff-so-fancy.pl line 33, <> line 7.` when trying to diff a file with a single latin1 `é` caracter.

To reproduce:

```
mkdir test
cd test
git init
vim test.txt # add a single é character and save with :w!++enc=latin1
git add test.txt
git diff
```

installed via homebrew (stable 0.9.3)

**Comment by scottchiefbaker** [comment]
I can confirm this is an issue. I'm not really sure how to fix it though. The problem is easily solved by saving the file as UTF8. I'm 99% sure the problem is that we assume all input is utf8, and this isn't. 

We'd have to detect the encoding of the input (STDIN), but you can't really do that unless you open it first, and we open it in UTF8 mode.

https://github.com/so-fancy/diff-so-fancy/blob/master/lib/diff-so-fancy.pl#L8

I'm open to suggestions, but this seems like a pretty obscure corner case, and may not end up getting solved cleanly.

**Comment by scottchiefbaker** [comment]
The more I think about it... this may be a **CANTFIX**. If your diff output incldues `utf8` *and* `latin1` output (from two different files) there is no way for d-s-f to know that. All d-s-f gets is raw `git diff` output, which every file's diff concatenated together. I hate to say it, but it's 2016 so we may have to default `utf8` as it's the only sane default in a world of varied encodings.

Alternately we could allow a user a one-off to *force* the encoding/decoding (not assume utf8) but that only works if all your input is the **same** encoding.

**Comment by paulirish** [comment]
+1 on taking a utf-8-only stance here.

**Comment by stevemao** [comment]
Can we warn user in such case? Or adding an option (flag)?

**Comment by adagios** [comment]
I'm perfectly fine with assuming UTF8. But I don't think it's acceptable to fail when finding an unexpected character.

Don't detect another encoding, that's difficult and impossible to do with absolute certainty. But don't error out, substitute the failing character with a placeholder one.

I was converting a single file between encodings, and the diff aborted. The regular git diff works as expected, showing garbled chars on the non-UTF8 side.

**Comment by adagios** [comment]
On the other hand, there are perfectly valid reasons to use a non-UTF8 encoding, and you should consider supporting them. Java properties files must be iso-8859-1 for example.

**Comment by scottchiefbaker** [comment]
The more I think about it... the more I think we have to assume utf8. With mixed encoding diffs there is no good way to handle all the different encodings.

I'll look in to a better error, but I'm not real hopeful. This is pretty low level Perl file access, I'm not sure if there is a way to get at it, at that level.

**Comment by scottchiefbaker** [comment]
The good news is for a one-off type of solution we can simply disable utf8 on input by commenting out line 8. Unfortunately that's a `use` statement so it's not something that can be easily modified at runtime.

**Comment by scottchiefbaker** [comment]
I did some more research and I found a way that we can disable `UTF8` at runtime. Theoretically we could then have a config option `UTF8Input = false` to disable it in specific cases? Unfortunately I can't catch the above error to give a better error message without a ton of manual decoding that would add a **lot** of overhead.

From what I can tell this bug ONLY manifests if the source code is in `latin1` **and** uses extended (above 127) characters. If it is `latin1` (iso-8859-1) but only uses ASCII chars (less than 127) we're fine. If the data is in `UTF8` we're fine also. This seems like a pretty corner case to me. I wish we had a better solution, but I can't find one.

I'm open to suggestions. How do we feel about adding a config option to disable UTF8 input?

**Comment by adagios** [comment]
I've got only rudimentary knowledge of perl, so take this as-is.

I've read a bit and found that just by adding
```perl
no warnings 'utf8';
```
I've got the expected output:
```
13:31 - [diff-so-fancy] git diff --cached
──────────
added: test.txt
──────────
@ test.txt:1 @
+<E9>
```

The char is not correctly shown, but at least it shows something.
If I commit this version of the file and then change the encoding to utf-8 I get:
```
13:33 - [diff-so-fancy] git diff
────────
modified: test.txt
────────
@ test.txt:1 @
-<E9>
+é
```

which is also fine by me.

**Comment by adagios** [comment]
> From what I can tell this bug ONLY manifests if the source code is in latin1 and uses extended (above 127) characters. If it is latin1 (iso-8859-1) but only uses ASCII chars (less than 127) we're fine

That is always true, the "normal" characters (bellow 127) are always equal in all encodings. We are always only interested in the characters that are different :)

**Comment by scottchiefbaker** [comment]
@adagios can you test #168 and see if it solves the problem for you?

**Comment by adagios** [comment]
@scottchiefbaker I've tested and it works great, thanks!
