### ISSUE TITLE
Git can now show fancy diffs now

### ISSUE THREAD

**Issue by derhuerst** [so-fancy/diff-so-fancy#166]
[Git 2.9 can do this](https://github.com/blog/2188-git-2-9-has-been-released). Does diff-so-fancy more than Git?

**Comment by scottchiefbaker** [comment]
@derhuerst that page is referencing `diff-highlight` which we use for this project, and then expand on it. Yes we can do the things on that page, AND more.

**Comment by derhuerst** [comment]
Ok, thanks!

**Comment by stevemao** [comment]
> And if you really want to go nuts, check out the diff-so-fancy project, which plugs in in the same way. These diffs are so fancy, you'll pop your monocle.

It is actually mentioned in the blog :)
