### ISSUE TITLE
Diff not showing all files

### ISSUE THREAD

**Issue by samiraguiar** [so-fancy/diff-so-fancy#176]
Maybe this is the same as #133, but as I'm not sure I'm opening a new issue.

I'm running the following command:
`git dsf origin/master...HEAD <directory>`
So I can get the diff restricted to a single dir.

The problem is that not all files are being listed and the diff is cut off. If I remove the directory argument, the whole diff is shown but still not all files under that dir that were changed are there.

I've run the `report-bug.sh` script. At first it complained about the `--color` option, so I removed it and it worked. I created [a gist](https://gist.github.com/samiraguiar/5cc2d52f06b6258c86b78834fb5d4d49) with the output.

I got this error twice though:
`utf8 "\xE7" does not map to Unicode at /c/Users/samir.aguiar/AppData/Roaming/npm/node_modules/diff-so-fancy/lib/diff-so-fancy.pl line 33, <> line 50.``

I'm running diff-so-fancy on Windows with msysgit.

**Comment by scottchiefbaker** [comment]
Aha... `utf8 "\xE7" does not map to Unicode` means you probably have `latin1` input text. This crashed d-s-f until checkin 2a7590b10e6186eda185310037e258b2d9508bb2. Are you running the latest master? That bug was fixed eight days ago :)

See #165 for more details.

**Comment by samiraguiar** [comment]
Crap, I downloaded dsf the day before the release :sweat: 
Thanks, that fixed it.
