### ISSUE TITLE
gitconfig error: adding dsf alias to gitconfig causes error

### ISSUE THREAD

**Issue by shasum** [so-fancy/diff-so-fancy#178]
Adding a `dsf` alias to `~/.gitconfig` as per Readme causes error when running Git commands.

Env: OS X, Bash
```
[user]
        email = someone@example.com
[core]
        excludesfile = ~/.gitignore

### diff-so-fancy
git config --global alias.dsf '!f() { [ -z "$GIT_PREFIX" ] || cd "$GIT_PREFIX" && git diff --color "$@" | diff-so-fancy | less --tabs=4 -RFX; }; f'
```
>$ git status
>fatal: bad config file line 7 in /Users/zzz/.gitconfig

Appreciate any pointers to make this work. Thanks.

**Comment by stevemao** [comment]
You should run `git config --global alias.dsf '!f() { [ -z "$GIT_PREFIX" ] || cd "$GIT_PREFIX" && git diff --color "$@" | diff-so-fancy | less --tabs=4 -RFX; }; f'` and `~/.gitconfig` will be updated.

**Comment by shasum** [comment]
@stevemao thanks a lot, works 👍  ( and thanks for submitting a Readme enhancement as well )
