### ISSUE TITLE
Document how to used it with vi

### ISSUE THREAD

**Issue by markelog** [so-fancy/diff-so-fancy#183]
Currently, it's documented how to use this with `less` pager, can you document it how to use it with `vi`?

Thank you

**Comment by stevemao** [comment]
Unless `vi` is very common, we can't document everything. Thoughts?

**Comment by scottchiefbaker** [comment]
I don't think vi/vim is a common pager. It should be pretty straight forward though. It should just be ` | vim -` I think. I'm not an expert on vim as a pager.

I think officially we support `less` and other pagers are up to the user to figure out?

**Comment by scottchiefbaker** [comment]
Oooopps. I didn't mean to click "comment and close". If you feel we should re-open this let us know.

**Comment by markelog** [comment]
Nuh, that's fine, it was stupid of me to ask, thanks
