### ISSUE TITLE
Diff for line prepends

### ISSUE THREAD

**Issue by marekhrabe** [so-fancy/diff-so-fancy#184]
I have just installed this (really nice tool!) and quickly noticed this output:

<img width="180" alt="screen shot 2016-07-15 at 00 04 34" src="https://cloud.githubusercontent.com/assets/156676/16857395/bf412e16-4a1f-11e6-9f19-a9b32a685004.png">

I mean it's not wrong and it gets the job done well, but there is obviously a much better thing to highlight than `turn re`. Is improving something like this in the scope of this package?

**Comment by scottchiefbaker** [comment]
The intra line/word highlighting is handled by [diff-highlight](https://github.com/git/git/tree/master/contrib/diff-highlight). This should would be a good thing to address with them.

We (d-s-f) wrapper the output of `diff-highlight` and make it more human readable.

**Comment by paulirish** [comment]
closing as its technically a diff-highlight bug.
