### ISSUE TITLE
clarify the license; add copyright statement

### ISSUE THREAD

**Issue by onlyjob** [so-fancy/diff-so-fancy#194]
"MIT" is not a reliable license identifier. [MIT](https://opensource.org/licenses/mit-license.php) license id [is ambiguous](https://en.wikipedia.org/wiki/MIT_License#Various_versions) (there are [too many licenses](https://fedoraproject.org/wiki/Licensing:MIT) known as _MIT_) and FSF recommends to refer to it as [Expat](https://directory.fsf.org/wiki/License:Expat).

As very minimum proper licensing should include canonical URL to the text of the license:

 * https://opensource.org/licenses/mit-license.php
 * https://directory.fsf.org/wiki/License:Expat

or better (to avoid any doubts) commit full text of the license to `LICENSE` file.

---

Also please add copyright statement -- a something like

    Copyright 2015-2016 John Smith <john@smith.com>

Thanks.

**Comment by scottchiefbaker** [comment]
Good call. I'm all for including `LICENSE` in the repo. The licenses you listed are correct, would you like to submit a pull request adding a `LICENSE` file?

**Comment by onlyjob** [comment]
> would you like to submit a pull request adding a LICENSE file?

No, sorry, too little time... Besides it would be better if one of main contributors could craft the commit...

**Comment by scottchiefbaker** [comment]
No worries. Thought you'd want credit. Closed via 224db6aae69f3174bf0d883a748c716e1704442d

**Comment by vanniktech** [comment]
@scottchiefbaker you may wanna go and fix `Copyright (c) <year> <copyright holders>`

**Comment by scottchiefbaker** [comment]
Good call, I clarified that.

**Comment by onlyjob** [comment]
Thanks. :)
