### ISSUE TITLE
diff-so-fancy stopped working on windows 10 after installing bash

### ISSUE THREAD

**Issue by ingro** [so-fancy/diff-so-fancy#197]
Hello! I was using diff-so-fancy just fine until I updated windows 10 with the anniversary update and installed bash.

Now when I launch the command `git diff --color | diff-so-fancy` I only get:

`Error: 0x80070057`

While trying to launch diff-so-fancy stand alone result in this error:

`/bin/bash: C:\Users\Ingro\AppData\Roaming\npm\node_modules\diff-so-fancy\diff-so-fancy: File or directory not found` while the file is indeed there.

I suspect that windows is trying to execute the script through bash but the path don't match there (it should be /mnt/c/User/Ingro and so on).

Any idea or workaround to fix this? Thanks.

**Comment by scottchiefbaker** [comment]
I don't think we have a lot of users on Windows + Bash (yet). Error: 0x80070057 seems to be a REALLY generic error message. I can't help much with that.

I can only guess that bash isn't able to find d-s-f, but I don't have any idea why. I'm open to suggestions/patches because I don't have much Windows experience.

**Comment by ingro** [comment]
I made futher tests and if I install d-s-f in bash environment all is working just fine, but if I launch it in windows env gives me that error.

So in some way windows detect that it's a bash script and launch it through bash, but there the path didn't match and so it throws an error. I tried to comment the `#!/usr/bin/env bash` comment at the top of the script but nothing changed though :/

**Comment by stevemao** [comment]
> So in some way windows detect that it's a bash script and launch it through bash, but there the path didn't match and so it throws an error

Sounds like your setting is wrong

**Comment by giggio** [comment]
I am also having problems. This is the generated `diff-so-fancy.CMD`:

````cmd
@IF EXIST "%~dp0\bash.exe" (                                                    
  "%~dp0\bash.exe"  "%~dp0\node_modules\diff-so-fancy\diff-so-fancy" %*         
) ELSE (                                                                        
  @SETLOCAL                                                                     
  @SET PATHEXT=%PATHEXT:;.JS;=;%                                                
  bash  "%~dp0\node_modules\diff-so-fancy\diff-so-fancy" %*                     
)                                                                               
````

I do have bash from the Windows Subsystem for Linux installed, so I do have bash in my Path.

Just as an example, this is the generated `gulp.cmd`:

````cmd
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\gulp\bin\gulp.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\gulp\bin\gulp.js" %*
)
````

This is what is happening. `bin`  on `package.json`  points to the executable. In gulp, that file has `#!/usr/bin/env node` as the hashbang, while diff-so-fancy has `#!/usr/bin/env bash`. This is causing the search for bash, which does not exist on Windows.

`diff-hightlight` suffers from the same problem.

**Comment by josteink** [comment]
I'm getting the following when trying to use it on Windows with the Windows Subsystem For Linux (WSL):

````
C:\> diff-so-fancy.cmd
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

In order to use this feature you must have Developer Mode enabled.
````

My guess would be that some part of the script uses extension-less access to other commands, causing the WSL equvalents to be invoked.

**Comment by giggio** [comment]
The problem is that when the file expansion happens, this is what ends up getting called:

````cmd
bash 'C:\Program Files\nodejs\node_modules\diff-so-fancy\diff-so-fancy'
````

WSL Bash does not know about `C:`. On WSL, it is mounted on `/mnt/c`. If you use cygwin (I am using it from the git install), it works:

````cmd
git diff | . 'C:\Program Files\Git\bin\bash.exe' 'C:\Program Files\nodejs\node_modules\diff-so-fancy\diff-so-fancy'
````

![image](https://cloud.githubusercontent.com/assets/334958/24758501/e25d7866-1ae2-11e7-9c48-2c03c8193858.png)

So, I am not sure how to fix the generated .cmd, as diff-so-fancy is a bash program. Either call it directly, as I did above, or set the pager like so:

````cmd
git config --global core.pager "'C:\Program Files\Git\bin\bash.exe' 'C:\Program Files\nodejs\node_modules\diff-so-fancy\diff-so-fancy'"
````

Then it works:

![image](https://cloud.githubusercontent.com/assets/334958/24758737/89813380-1ae3-11e7-9df7-692f2a9c53eb.png)

I hope this helps.

@scottchiefbaker maybe add this to the README? Windows 10 version 1703 was just released today, and WSL has evolved a lot in this version. I guess many developers will start using it.

**Comment by josteink** [comment]
Thanks for the feedback!

I currently have both Cygwin and WSL installed, but for some reason WSL seems to take presedence in the path. I assume this is what causes issues.

But the workaround you offer seems reasonable enough. I definitely agree that documenting it would make the life of Windows-users much simpler :)

For a more generic approach, where paths are resolved properly, the following worked for me:

````batch
REM one off
git diff | "C:\Program Files\Git\bin\bash.exe" "%APPDATA%\npm\node_modules\diff-so-fancy\diff-so-fancy"

REM as pager
git config --global core.pager "'C:\Program Files\Git\bin\bash.exe' '%APPDATA%\npm\node_modules\diff-so-fancy\diff-so-fancy'"
````

**Comment by scottchiefbaker** [comment]
@giggio We should probably start a Windows readme. I don't have a Windows box to even test with, so I'd have to rely on the community for all of that. If you send me a PR with any Windows specific documentation you want I'll **gladly** accept it.

**Comment by scottchiefbaker** [comment]
Where do we stand on this issue?

**Comment by giggio** [comment]
I am not sure this is still a problem, as dsf is not using bash anymore, but perl.

**Comment by scottchiefbaker** [comment]
I'm gonna close this for lack of activity. If it's still an issue let me know.
