### ISSUE TITLE
Branch autocompletion not working

### ISSUE THREAD

**Issue by R11T** [so-fancy/diff-so-fancy#200]
Hi and thanks for your tool (well named « fancy » :smile: ) !

I followed install process last night by setting `git dsf` alias in my `~/.gitconfig` : 

```
git config --global alias.dsf '!f() { [ -z "$GIT_PREFIX" ] || cd "$GIT_PREFIX" '\
'&& git diff --color "$@" | diff-so-fancy  | less --tabs=4 -RFX; }; f'
```

Unfortunately, when I type :

```
git dsf dev
```

and press tab for autocompleting my branch name, I receive error message (sorry, french) :

```
git dsf dev-bash: declare: « _git_[ » : identifiant non valable
```

I can do more tests if your need more informations.

Thanks !

Note : I have a vanilla bash.

**Comment by scottchiefbaker** [comment]
Paging @stevemao and @OJFord are either of you able to recreate this?

**Comment by OJFord** [comment]
Yes, I can reproduce this:

```shell
brew install bash bash-completion
bash
. /usr/local/etc/bash_completion
mkdir /tmp/repo
cd /tmp/repo
git init
git config alias.dsf '!f() { [ -z "$GIT_PREFIX" ] || cd "$GIT_PREFIX" && git diff --color "$@" | diff-so-fancy  | less --tabs=4 -RFX; }; f'
git branch second
git diff sec{tab->ond}
git dsf sec{tab->bash: declare: `_git_[': not a valid identifier

fatal: ambiguous argument 'f': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'}
```

**Comment by scottchiefbaker** [comment]
This sounds like a git issue then? Somehow git isn't getting the right information after hitting tab on an aliased command?

@peff any ideas what would confuse git with auto-completion in this scenario?

**Comment by OJFord** [comment]
Works fine with `git config alias.test checkout` and `git config alias.test '!f() { git checkout "$@"; }; f'`.

**Comment by peff** [comment]
I think that the bash completion isn't clever enough to peer through the alias. For non-shell aliases (like your `alias.test`, it trivially knows the command is `checkout`). For shell ones, it tries to guess. In either case, it will run the `_git_<command>` completion function. Normally if the guess is wrong that function just won't exist. But if it's syntactically invalid, then bash will complain.

You can report it upstream to the mailing list (see http://git-scm.com/community).

**Comment by peff** [comment]
(And in case it was not clear, no, I don't think this has anything at all to do with diff-so-fancy).

**Comment by OJFord** [comment]
Thanks for the explanation @peff.

@R11T Can you just use:
```shell
git config alias.dsf '!f() { git diff --color "$@" | diff-so-fancy | less --tabs=4 -RFX; }; f'
```

Bash completion works fine then; I'm not sure why you need to `cd` to the cwd anyway? I don't believe dsf's output will ever be different as a result. (@scottchiefbaker?)

**Comment by R11T** [comment]
I try it asap. 

> I'm not sure why you need to cd to the cwd anyway?

I followed « Usage » section in the readme. Do I have to propose a PR to update it if your command works ?

**Comment by OJFord** [comment]
>  I followed « Usage » section in the readme.

Hmm, looks like f547196887bdbb58ef0e91eeb317f9a552d92280 is responsible for that, which claims to fix #86, though that issue to me looks like it was the result of a typo.

> Do I have to propose a PR to update it if your command works ?

It certainly works as far as I've tested and am aware, but we should make sure that it doesn't regress on the above issue before proposing any change.

**Comment by R11T** [comment]
```
git config alias.dsf '!f() { git diff --color "$@" | diff-so-fancy | less --tabs=4 -RFX; }; f'
```

Works like a charm ! Thanks :+1:

**Comment by stevemao** [comment]
@paulirish could you have a look at this issue :)

**Comment by scottchiefbaker** [comment]
This sounds like a git issue, and not a d-s-f issue. If I'm wrong feel free to re-open.
