### ISSUE TITLE
Diff so fancy stopped working on win 7: random errors in perl script

### ISSUE THREAD

**Issue by Chiel92** [so-fancy/diff-so-fancy#202]
When diffing

```
$ git show 4c1d1d860fac
```

I can randomly get one of the following two errors:

```
Can't exec "tput": Invalid argument at /c/Users/Chiel.tenBrinke/AppData/Roaming/npm/node_modules/diff-so-fancy/libexec/diff-so-fancy.pl line 384, <> line 8.
Argument "" isn't numeric in repeat (x) at /c/Users/Chiel.tenBrinke/AppData/Roaming/npm/node_modules/diff-so-fancy/libexec/diff-so-fancy.pl line 402, <> line 8.
```

or 

```
Can't exec "uname": Invalid argument at /c/Users/Chiel.tenBrinke/AppData/Roaming/npm/node_modules/diff-so-fancy/libexec/diff-so-fancy.pl line 385, <> line 215.
```

I'm on windows 7, using git bash and never had any problems. After getting these errors, I updated to the latest version by running `npm update -g diff-so-fancy`, but no luck. I'm not sure what triggered this regression. Anyone known whats going on? I can give more information as necessary.

**Comment by Chiel92** [comment]
It seems that some diffs have more chance to fail than others; maybe this bug was always there and I was just lucky so far

**Comment by scottchiefbaker** [comment]
Do you have the `tput` and `uname` commands are part of your path? Those are very much Linux commands, but you're running Windows so it might be work double checking they were installed as part of your cygwin environment.

What are the outputs if you manually run `tput cols` and `uname -a`

**Comment by Chiel92** [comment]
```
chiel.tenbrinke@IM-Chiel-2015 MINGW64 ~
$ tput cols
80

chiel.tenbrinke@IM-Chiel-2015 MINGW64 ~
$ uname -a
MINGW64_NT-6.1 IM-Chiel-2015 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys
```

Btw, not cygwin, but mingw64

**Comment by scottchiefbaker** [comment]
I wonder if there are some situations where `tput` or `uname` don't run, or don't return appropriate information?

**Comment by Chiel92** [comment]
No idea. Weird thing is that the error isn't always there. So there must be some kind of race condition playing a role here.

**Comment by scottchiefbaker** [comment]
If you can figure out a rhyme or reason let us know. Otherwise it's going to be pretty hard to troubleshoot.

**Comment by Chiel92** [comment]
I can add another non-deterministic error to the list:

```
$ git show
/usr/bin/env: ‘perl’: Invalid argument
```

**Comment by Chiel92** [comment]
Great project btw!

**Comment by OJFord** [comment]
I don't think that's a Perl problem.

If it's still an issue, what's the output of `locale`?

**Comment by Chiel92** [comment]
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```

**Comment by OJFord** [comment]
What about `which env`, and `/usr/bin/env --version`?

**Comment by Chiel92** [comment]
```
$ which env
/usr/bin/env

$ /usr/bin/env --version
env (GNU coreutils) 8.25
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard Mlynarik and David MacKenzie.
```

**Comment by OJFord** [comment]
Bizarre. But I suppose you did say it's not consistently reproducible? Seems like a mingw problem to me.

**Comment by scottchiefbaker** [comment]
Is this still an issue?

**Comment by Chiel92** [comment]
I haven't seen it happen lately, and I can't reproduce at the moment. So I'll assume the issue has been resolved.
