### ISSUE TITLE
AVG AntiVirus detects Virus

### ISSUE THREAD

**Issue by alawatthe** [so-fancy/diff-so-fancy#208]
The current version of [AVG AntiVirus](http://www.avg.com/ww-en/avg-antivirus-for-mac) detects a virus in the ```test/fixtures/dotfiles.diff``` file.

<img width="1087" alt="avg" src="https://cloud.githubusercontent.com/assets/901391/21527893/c2e50bf4-cd2e-11e6-8567-027a0d80942d.png">

I'm not quite sure, what the reason for this is, but I thought I let you know.

**Comment by scottchiefbaker** [comment]
Doesn't really make sense... but thanks for the info. We'll chalk it up as a fluke.

**Comment by alawatthe** [comment]
I had a closer look at it, apparently the ```127.0.0.1 twitter.com``` part in line 7 is very evil 😆 

One thing which came to my mind was, that you could add a .npmignore file and tell it to ignore the test folder and a few things, which aren't needed in the npm package. Apart from AVG being happy, the npm module would be smaller, which makes everyone happy.

Thank you for the nice tool btw :-)

**Comment by OJFord** [comment]
AVG AV is the real evil here...

**Comment by Oxicode** [comment]
Lol. Hahah

**Comment by stevemao** [comment]
@alawatthe PR welcome to change it :)
