### ISSUE TITLE
Create and submit a brew formula

### ISSUE THREAD

**Issue by OJFord** [so-fancy/diff-so-fancy#21]
Repo more than meets the star/fork requirements. Most Mac users would probably prefer a pure-brew install than a brew+npm install.

`brew install gnu-sed --with-default-names && npm install -g diff-so-fancy` would become `brew install diff-so-fancy`. You could even include the `git config`uration in the formula.

**Comment by stevemao** [comment]
I think homebrew is already available but not pointing to this repo.

**Comment by OJFord** [comment]
Do you know the name? I don't get any results for `brew search diff-so-fancy`.

**Comment by paulirish** [comment]
yah i'm not seeing it either.

![image](https://cloud.githubusercontent.com/assets/39191/12935110/6c0988c4-cf8b-11e5-9d90-2c9bdba364ac.png)


I'm OK with having this available via homebrew, though i've never maintained a brew package before. seems likely higher friction pushing to npm.

**Comment by paulirish** [comment]
@OJFord i dont think we'd get the `default-names` applied if we set it as a dependency. So we'd have to rely on `gsed` and sniff for that first. Slightly more complicated, but probably fine.

**Comment by OJFord** [comment]
@paulirish Hmm, good point, I've never tried to do anything analagous so I couldn't say either way for sure.

As a workaround though, it could be done in the `install` block with a `system` call. I expect (hope) brew maintainers would be happy with that until an alternative exists though.

**Comment by OJFord** [comment]
Oh! I thought of a better solution: you could use [inreplace](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#inreplace) to change instances of `sed` in the script to `gsed`; then the dependency needs no flags, right?

**Comment by anshul** [comment]
Or something like this could work? - https://github.com/stevemao/diff-so-fancy/pull/25

**Comment by OJFord** [comment]
@anshul That might be more robust. If the brew install with default name flag doesn't alias `gsed` as well then I suppose my above suggestion fails if `gnu-sed` already installed.

**Comment by OJFord** [comment]
Closed via Homebrew/homebrew#49040.

**Comment by stevemao** [comment]
Thanks again @OJFord :smile:

**Comment by stevemao** [comment]
We need to add docs on how to install via Homebrew.

**Comment by OJFord** [comment]
@stevemao No worries :)

So for install instructions, I'd suggest just replacing the "on Mac, get `gnu-sed` with brew" with "on Mac, install via brew: `brew install diff-so-fancy`".

Can PR if you want, but if you'd prefer to just get the wording how you'd like it yourself rather than review mine that's :+1: too!
