### ISSUE TITLE
Add parameter to show line numbers of files

### ISSUE THREAD

**Issue by aserrallerios** [so-fancy/diff-so-fancy#211]
It may just copy what github does. Two columns, line numbers if apply. 

This would be a real improvement over the regular diffs IMO.

Sorry if this is out of scope of this project.

**Comment by OJFord** [comment]
It's certainly possible to do, but most of what d-s-f does is about removing clutter and focussing on the actual diff.

Have you tried one of the line-number solutions [here](http://stackoverflow.com/questions/24455377/git-diff-with-line-numbers-git-log-with-line-numbers) together with `diff-highlight`? You might find that's more what you're looking for.

**Comment by aserrallerios** [comment]
Not really into those solutions, too fragile, I'd rather use a maintained project that supports that feature.

Up to you to discuss! :)

**Comment by scottchiefbaker** [comment]
I think this may be slightly outside the scope of d-s-f. On of the main focuses of d-s-f is to remove excess clutter like the `-` and `+` line headers, and instead focus on making the output as HUMANLY consumable and copy-pasteable as possible. 

Plus we do parse out the diff line indicators so you should be able to see what/where each hunk is from.

```
@ unifi.inc:78 @
```

I'm going to mark this closed for now. If you feel strongly about it feel free to reopen it.

**Comment by alxmrtn** [comment]
Stopping by 8 years later to say that I personally think this would be a useful feature. I don't think having line numbers is at odds with humanly consumable diffs. For example, `bat` does this very well:

<img width="388" alt="Image" src="https://github.com/user-attachments/assets/b60eed82-de33-42f5-98d7-fe86cc2b4200" />

**Comment by OJFord** [comment]
For what it's worth `delta` supports it if it's important to you:
https://github.com/dandavison/delta?tab=readme-ov-file#line-numbers

**Comment by OJFord** [comment]
For what it's worth `delta` supports it if it's important to you:
https://github.com/dandavison/delta?tab=readme-ov-file#line-numbers

**Comment by scottchiefbaker** [comment]
FWIW you can configure git to use `bat` as your pager after d-s-f

```
pager = diff-so-fancy | bat
```

That gets you d-s-f highlighted lines, and `bat` paging with line numbers. The file modifier bars wrap because it thinks the screen is longer than it really is, but that's pretty minor.
