### ISSUE TITLE
Highlight diff in filename changes

### ISSUE THREAD

**Issue by stevemao** [so-fancy/diff-so-fancy#213]
I really like how gitlab shows the diff in filename changes:

![image](https://cloud.githubusercontent.com/assets/6316590/21967835/2b42bdc4-dbe2-11e6-8188-19dfe3b5f2d2.png)

Would be great if diff-so-fancy implements this. Cheers :)

**Comment by scottchiefbaker** [comment]
All the highlighting is done by `diff-highlight`, I'm not sure how we'd hook in to that for this request.

I like the idea, I'm just not sure how to implement this.

**Comment by scottchiefbaker** [comment]
@peff is this something that could be done in `diff-highlight`? I like the idea, if it's possible.

**Comment by peff** [comment]
Yeah. Probably it would involve recognizing the `rename from` and `rename to` lines from the input and feeding them to `highlight_pair`. I guess you'd need to teach it that the `from`/`to` difference isn't interesting, just the filename. I probably won't work on it anytime soon, but I'd be happy to review a patch.

**Comment by peff** [comment]
If you're already parsing these lines in d-s-f, I think you can do something like this (with the new diff-highlight module):

```
my ($old, $new) = DiffHighlight::highlight_pair('src/html/index.html', 'src/index.html');
print "$old\n";
print "$new\n";
```

**Comment by scottchiefbaker** [comment]
@stevemao how are we triggering a rename? Looking at this code I don't think we've ever tested it. Assuming we're doing `git mv file.txt file2.txt` there appropriate raw git output is:

```
diff --git a/Changes.new b/bin/Changes.new
similarity index 100%
rename from Changes.new
rename to bin/Changes.new
```

**Comment by scottchiefbaker** [comment]
It appears that file renames ALWAYS sort ot the top of the git output, regardless of what order the commits are around it. Using the logic that @peff provided I can get _close_ to what you want. 

We may need @peff to tweak his logic a little if you want it to look exactly like the github image you posted. 

![rename](https://user-images.githubusercontent.com/3429760/27714330-111272bc-5ce5-11e7-986a-a9ad75c804ac.png)

**Comment by scottchiefbaker** [comment]
If I flip it around the highlight is in the first file. I _think_ what we want for this feature is only the highlighted part (i.e. not the regular green/red background). 

@peff is there anyway to modify d-h to add an option to **only** highlight the changes? This is a special use case.

![rename2](https://user-images.githubusercontent.com/3429760/27743932-85023774-5d72-11e7-9f49-86079636141c.png)

**Comment by OJFord** [comment]
@scottchiefbaker Do you mean to have the path changes highlighted, and the rest uncoloured?

Your screenshot shows that only `bin/` is *highlighted*, `Changes.new` is coloured red/green but with no highlight. As I understand it, plain `git`'s `color` option is responsible for the red/green colouring; `diff-highlight` is already doing what you request.

Presumably plain colouring of the rest could be achieved by overriding the ASCII codes though.

**Comment by scottchiefbaker** [comment]
I think what we (OK maybe just me) want is something more like the github screenshot, where ONLY the parts that is changing is colored. I've submitted a small patch to @peff that I think accomplishes this.

![rename3](https://user-images.githubusercontent.com/3429760/27753505-c456851a-5d9a-11e7-8c91-4da88a0383c8.png)

If @peff is OK with the patch I'll publish my feature branch.

**Comment by OJFord** [comment]
I like that a lot, don't get me wrong, I just didn't think diff-highlight was responsible for it. :slightly_smiling_face:

**Comment by scottchiefbaker** [comment]
I don't have the brain power to figure out all the diff logic, so we're borrow a function from DiffHighlight to handle that. Currently d-h colors all line changes, which in this example is the whole filename, and that's not appropriate for this use case.

**Comment by scottchiefbaker** [comment]
This should be handled... future discussion on this issue should be done in #242

**Comment by stevemao** [comment]
Tried `next` branch. Looks awesome!
