### ISSUE TITLE
diff-so-fancy install error

### ISSUE THREAD

**Issue by sundylink** [so-fancy/diff-so-fancy#215]
`npm install diff-so-fancy -g  ` or `brew install diff-so-fancy` all error:

Error: No available formula with the name "diff-so-dancy"
==> Searching for similarly named formulae...

**Comment by OJFord** [comment]
If the error output is correctly copy pasted, then the commands likely
weren't entered as they appear here ;)

**Comment by stevemao** [comment]
@sundylink have you done `brew update` before installing anything?

**Comment by scottchiefbaker** [comment]
Appears to be a typo.
