### ISSUE TITLE
`git reset -p` no visual difference between context and patch-to-apply

### ISSUE THREAD

**Issue by thetrompf** [so-fancy/diff-so-fancy#216]
I have staged all my modified files and will partially unstage something in a single file,
as you can see in the screenshot:

1. I said `no` to unstage the first chunk.
2. I pressed `split` to the second chunk.
3. I see almost the same after I have `split` the chunk
    except the positive part of the part I thought I had "split away".

The negative part of the chunked I "split away" is still present, but it is not a part of the patch,
it is only present because it is context to the patch, but there is no visual difference.

4 . When I press split again, I correctly get warned that the chunk cannot be split.
5. When I enter edit mode to manually fix the patch and then return, I got prompted for the last chunk, I thought was part of the previous one.

![screen shot 2017-02-16 at 9 31 51 am](https://cloud.githubusercontent.com/assets/1430118/23013423/ca223f2c-f42a-11e6-944c-d13adc38d79a.png)

I don't know if this is only a problem with `git reset -p`, but I think it is also a problem with `git add -p` too.

**Comment by OJFord** [comment]
That's very odd, but I don't see that it can possibly be diff-so-fancy's fault - could you post a matching output (or this again too if you can't easily reproduce the same diff) with `git --no-pager ...`?

**Comment by henrahmagix** [comment]
This is indeed an issue with diff-so-fancy when used for `--patch` operations: see https://github.com/so-fancy/diff-so-fancy/issues/35#issuecomment-324202023
>It works with the caveats of off by one (which makes parts of diff not in the current chunk appears) ...

I'm not sure if it's recorded elsewhere. I made a repo detailing this: https://github.com/henrahmagix/diff-so-fancy-interactive-bug-example

**Comment by henrahmagix** [comment]
An explanation of the "off by one" error is here: https://github.com/so-fancy/diff-so-fancy/issues/35#issuecomment-199640833
>The diff header has 4 lines (`diff --git...`, the `index` line, and the `---`/`+++` lines), but your fancy output only has 3 (the two border lines, and the filename). So everything it shows is off-by-one...

**Comment by scottchiefbaker** [comment]
Unfortunately this is a result of #35 which you pointed out. As of right now #35 is a CANTFIX because of the way git mangles the output **after** d-s-f does it's magic. I still don't have a good work around for #35, so for now our advice is not to use d-s-f for `--patch`
