### ISSUE TITLE
Install using a curlable bash script

### ISSUE THREAD

**Issue by arichiardi** [so-fancy/diff-so-fancy#217]
Hello folks!

Great job with this nice little tool. I was wondering if there is a way to curl in and execute an sh script, like [the nvm install script](https://github.com/creationix/nvm#install-script).

Thanks a lot.

**Comment by OJFord** [comment]
There's not really any installation necessary - just `curl`/`wget` the script to somewhere on your `$PATH` if this is your preferred method.

**Comment by arichiardi** [comment]
Ok great thanks, I will leave this open if you don't mind as a simple script could automate even a mere 5 steps ;)

**Comment by OJFord** [comment]
Sure, a good outcome would be simplifying that process to something nearer the `brew install diff-so-fancy` macOS users can do, even if that's not `curl ... | sh` exactly, which I'm not sure is something any project should be promoting.

There is a package.json, which makes me wonder if at some point in time `npm install` worked (?) - but it doesn't do anything with the `libexec` directory, so I don't believe that can be working correctly at the moment.

From the brew formula, it appears that `npm install` can be used with a name of a directory though, and it does provide `bin` dirs - I'm not particularly familiar with npm, but it appears you should be able to do:
```sh
git clone git@github.com:so-fancy/diff-so-fancy
cd diff-so-fancy
npm install
npm install libexec
```

It might be possible to get that down to just `npm install`, or maybe that works already - if so, the instructions in the readme should probably be similarly simplified! (Or at least, the option added for npm users.)

**Comment by arichiardi** [comment]
Agree that `npm` might work at this point but you basically need to install node for it to work. Ideally `sh` should suffice. I know I know we don't live in an ideal world but still :D

That is why I would like to keep this open: maybe some linux user here, or myself indeed, could contribute this five lines of code.

**Comment by OJFord** [comment]
> Agree that npm might work at this point but you basically need to install node for it to work. Ideally sh should suffice.

Agreed, I just figured from your nvm link that that would be acceptable for you :slightly_smiling_face:

> maybe some linux user here, or myself indeed, could contribute this five lines of code

I'm sure that, or packages for other distros, would be more than welcome.

If you don't get a chance though I'm happy to have a look at this soon - having looked at the brew formula again I'd quite like to cut the node dependency from it, there's really no need for that. :+1:

**Comment by arichiardi** [comment]
Awesome then, I am happy I triggered some positive wave here, I am having a look at it right now and I will basically push some basic script quite soon :)

**Comment by arichiardi** [comment]
In the command:

```
git config --global alias.dsf '!f() { [ -z "$GIT_PREFIX" ] || cd "$GIT_PREFIX" '\
'&& git diff --color "$@" | diff-so-fancy  | less --tabs=4 -RFX; }; f'
```

what is `$GIT_PREFIX` again?

**Comment by OJFord** [comment]
`$GIT_PREFIX` will be set to the diff between the parent of the git directory (typically, i.e. in a non-bare repo, the 'project root' or `.git/..`). (cf. [git-scm docs](https://git-scm.com/docs/git-config#git-config-alias))

**Comment by arichiardi** [comment]
Great thanks a lot I did not know that!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by avivey** [comment]
`curl <something from internet> | bash` is a terrible security practice. It teaches people that it's ok to just download stuff of the internet and run it. That's how you get STD.
I've also seen `curl | sudo bash` somehere. brr.
</unrelated rant>

**Comment by OJFord** [comment]
@avivey If you refer to the first comment (mine) in this thread, in which I suggest obtaining the script via `curl` and storing it somewhere on `$PATH`, I mean from the github releases page, and I didn't suggest piping it to execute directly.

How and whether someone checks the contents of the program before running it is no different whether it is obtained with `curl` or by 'manually' downloading it with a web browser.

**Comment by scottchiefbaker** [comment]
Now that the d-s-f is a single script, I don't think we really need an install script. I'm going to close this for now. If you feel strongly let me know and we can discuss, but I think this is overkill.
