### ISSUE TITLE
Added/removed lines are not highlighted at all.

### ISSUE THREAD

**Issue by ashb** [so-fancy/diff-so-fancy#219]
Just came across this project and it seems like an interesting idea. I installed it via homebrew (`diff-so-fancy: stable 0.11.2 (bottled)`) and I found something slightly odd. Adding a line and it's not highlighted at all, but a changed line is.

<img width="437" alt="screen shot 2017-02-19 at 18 20 52" src="https://cloud.githubusercontent.com/assets/34150/23105022/7761b828-f6d0-11e6-9048-039d4e0e43d0.png">

The config options I have set are these:

```
git config --global color.diff-highlight.oldNormal "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"
git config --bool --global diff-so-fancy.stripLeadingSymbols false
```

(That last one was just to highlight the added/removed lines. Same behaviour of not colouring those lines without that setting)

**Comment by OJFord** [comment]
This is the expected behaviour: the highlighting shows intra-line change.

Pure additions/deletions should have a different foreground colour though - I assume red/green text in other settings works correctly in the same terminal emulator? (i.e. it's not that the codes for red, green, foreground are mapped to the same colour)

**Comment by ashb** [comment]
Yeah, normal red and green work colour codes work, i.e. `echo -e '\x1b[32;1mhi\x1b[0m'` prints hi in green.

**Comment by scottchiefbaker** [comment]
Try add this to your ~/.gitconfig

```
[color "diff"]
        meta = 227
        frag = magenta bold
        commit = 227 bold
        old  = 9
        new  = 10
```

**Comment by ashb** [comment]
No luck. I tried moving my `~/.gitconfig` out of the way to see if that would help too afterwards, no difference.

**Comment by ashb** [comment]
Oh, _ahem_. It helps if you provide `--color` to the first git command. As you were, and thanks for all the prompt help!

**Comment by OJFord** [comment]
Ha, glad you sorted it. Makes sense since the intra-line colouring is done separately by diff-highlight.

You can configure that to be default, with `color = always` if memory serves me correctly.
