### ISSUE TITLE
Diff-so-fancy needs usage output

### ISSUE THREAD

**Issue by scottchiefbaker** [so-fancy/diff-so-fancy#223]
@stevemao wrote

> make diff-so-fancy as a standalone cli command sounds great. Would like to see at least some information printed when running it instead of justing hanging there.

I actually just figured out how to detect that status of (or lack of) STDIN in Perl, so this is very doable. What would like d-s-f to output if it's run as raw from the command line?

**Comment by stevemao** [comment]
I was just talking about `diff-so-fancy --files file1 file2` raised in https://github.com/so-fancy/diff-so-fancy/issues/220
If you just run `diff-so-fancy` it should print help? Similar to what https://github.com/so-fancy/diff-so-fancy/pull/218 is printing.

**Comment by scottchiefbaker** [comment]
Good point... I clarified the name of the issue. I just need standard usage for calling `diff-so-fancy` without any `STDIN`.

Do we just want to output a chunk of the readme?

**Comment by OJFord** [comment]
Somewhat related to help output, it'd be nice to have `-v/--version` work.

**Comment by scottchiefbaker** [comment]
I could probably do both at the same time. The only problem with `--version` is that we have to maintain the version number inside of `d-s-f`.

**Comment by scottchiefbaker** [comment]
I mocked up a sample that handles both `--version` and calling d-s-f without any arguments.

**Comment by scottchiefbaker** [comment]
Closing via #242
