### ISSUE TITLE
Integrate diff-highlight inline into d-s-f 

### ISSUE THREAD

**Issue by scottchiefbaker** [so-fancy/diff-so-fancy#226]
> @scottchiefbaker Yes, I wrote it. There were a few minor fixes from other people, but nothing really substantial[1]. So as far as licensing goes, I'm happy for you to take whatever bits of it you'd like.
>
> [1] git blame can tell you, or git log --invert-grep --author=peff -p contrib/diff-highlight

**Comment by scottchiefbaker** [comment]
@peff I'm creating a new issue for this to follow up the conversation over in #224.

I'd really like to make d-s-f a one-stop-shop for fancifying diffs. That would include all the cool magic that `diff-highlight` does. Today we shell out to `diff-highlight` for the line level formatting and then let d-s-f clean up the headers and other stuff.

If possible I'd like to put `diff-highlight` inline inside of d-s-f as either a set of function calls, or as a full blown  inline module. Would you be willing to assist in that? I've looked at the code and it's not too crazy, but it does seem a little over my head.

**Comment by peff** [comment]
I'm happy to answer questions about the code, but I'm not really interested in leading the effort. I think d-s-f is a neat project, but I don't actually use it myself, and I have loads of actual git bugs and features I'd rather be spending my time on.

**Comment by scottchiefbaker** [comment]
Paging: @stevemao @OJFord @peff @paulirish

I believe I may have an initial version of this complete. Can you please test out this new version (1.1.0) and let me know if it works for you. With the integration of `diff_highlight` I've been able to get d-s-f down to a **single** fatpacked script.

Source branch: https://github.com/scottchiefbaker/diff-so-fancy/tree/intergrate_diff_highlight
Executable: https://www.perturb.org/tmp/diff-so-fancy

This should greatly simplify installation and probably offer better Windows support at the same time.

**Comment by scottchiefbaker** [comment]
This should help @arichiardi and #218 which I've been meaning to get back to but haven't had time.

**Comment by stevemao** [comment]
I had problem with `npm link` and sent you a PR. @scottchiefbaker If you want, you could always push to a feature branch here so that we don't have to add another remote and I think it's more visible as well :) Thanks!

**Comment by scottchiefbaker** [comment]
I'm gonna close this for now. This is handled by version 1.1.0 and #242. I think we're pretty close to a release on that branch so let's move discussion there.
