### ISSUE TITLE
Syntax error trying to run Perl 5.26

### ISSUE THREAD

**Issue by Xanuthatusu** [so-fancy/diff-so-fancy#236]
I get the following syntax error when trying to run diff-so-fancy. 

```Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/^((?^:(\e\[([0-9]{1,3}(;[0-9]{1,3}){0,3})[mK])?))[ +-]{ <-- HERE -1}/ at /usr/share/diff-so-fancy/diff-so-fancy.pl line 364, <> line 6.```

In perl v5.22, using a literal `{` in a regular expression was deprecated, and will emit a warning if it isn't escaped: `\{`. In v5.26, this won't just warn, it'll cause a syntax error.

EDIT: Issue is not present after manual installing, but is present the arch Linux and the npm package.

**Comment by scottchiefbaker** [comment]
This was fixed in #233, but we haven't released an official version after that yet.

**Comment by OJFord** [comment]
@scottchiefbaker Perhaps that should be a priority?

Anyone using a package manager and keeping their system up to date will currently get versions of Perl and dsf that are not compatible...

**Comment by scottchiefbaker** [comment]
Sounds good to me... it's easy enough to release a new version. I've never been involved in that process though, I just write the code. How do we do that?

**Comment by OJFord** [comment]
`git tag v0.11.5 && git push --tags` should do it for you. (I haven't either though, no commit access, I just comment on the issues :laughing:)

I think npm might use the latest from the releases page here, (which will pick up the tag) brew needs an update to SHA and version number [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/diff-so-fancy.rb) which is now dependent on npm for some reason.

The AUR package is maintained by @felixonmars.

**Comment by felixonmars** [comment]
Arch package diff-so-fancy 1.0.0-1 released.
