### ISSUE TITLE
Pager does not support scrolling via trackpad

### ISSUE THREAD

**Issue by ahmetb** [so-fancy/diff-so-fancy#246]
I am using MacBook trackpad to scroll up and down the pages in the pager applications, such as `less` while viewing content that does not fit my terminal height.

Prior to configuring `diff-so-fancy`, I was able to run `git diff` and scroll through the diff using the trackpad. It does not work anymore after installing and configuring diff-so-fancy. It basically scrolls up to the output of prior programs by scrolling up the terminal. It should not be doing that.

Is it not working due to the diff-so-fancy's pager implementation, its piping to `less`, or because some configuration key is missing? 

Here is my config:

```
credential.helper=osxkeychain
core.pager=diff-so-fancy | less --tabs=4 -RFX
color.ui=true
color.diff-highlight.oldnormal=red bold
color.diff-highlight.oldhighlight=red bold 52
color.diff-highlight.newnormal=green bold
color.diff-highlight.newhighlight=green bold 22
color.diff.meta=227
color.diff.frag=magenta bold
color.diff.commit=227 bold
color.diff.old=red bold
color.diff.new=green bold
color.diff.whitespace=red reverse
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
```

**Comment by ahmetb** [comment]
As mentioned in #26, removing `X` from `diff-so-fancy | less --tabs=4 -RFX` actually solves this problem. If that's the recommended way to resolve it, it probably should be the recommended installation method?

**Comment by scottchiefbaker** [comment]
Does it work properly with `less --tabs=4 -RFX` if you use the keyboard. Specifically the trackpad implementation is weird on OSX when using `-X`?

**Comment by ahmetb** [comment]
Keyboard up/down arrow keys work fine. It seems to be mouse issue. I am using trackpad and don't have access to a mouse right now but I'm confident it would be the same behavior on the mouse with -X, too.

**Comment by scottchiefbaker** [comment]
My best guess is that this is a bug in less? I'm not really sure what the interaction with the trackpad should be? The `-X` helps reset some other ansi issues, so it's definitely "recommended" but maybe not appropriate in 100% of cases. Perhaps we should modify the documentation somehow.

**Comment by scottchiefbaker** [comment]
I'd accept a pull request if you want to change the documentation in `pro-tips.md` to reflect this. I'm sure someone else will run in to it.

**Comment by ahmetb** [comment]
I'm more interested in finding out why is this causing an issue. This is somewhat major... I just confirmed this is not only trackpad but mouse scrolling wheel, too.

This doesn't only impact `git diff`. As far as I can tell, it exposes the same bug on `git blame`, `git log` and many other commands using the pager, too. Many people scroll up and down in their `git commit` window, `git log` output etc.

If we definitely need `-X`, we should probably figure out what else we need to do, to make sure scrolling works. 

Were you able to repro this? FWIW I am using GNU less v458 (not BSD) on macOS with iTerm2.

**Comment by ahmetb** [comment]
`find /etc/ | less -RFX` reproes the problem and removing `-X` solves it. In my `less --help`, I see that:

      -X  ........  --no-init
                      Don't use termcap init/deinit strings.

Similarly, Apple's BSD less also says:

```

       -X or --no-init
              Disables sending the termcap initialization and  deinitialization  strings  to  the  terminal.
              This  is  sometimes  desirable if the deinitialization string does something unnecessary, like
              clearing the screen.
```

I'm not closely familiar but it sounds like we should be avoiding `-X` to get the screen cleared and initialized. It might be good to pull in people with more expertise in this area.

**Comment by scottchiefbaker** [comment]
I'm going to close this... but if you'd like to submit a PR for doc fixes I'm open to that.

**Comment by OliverJAsh** [comment]
I was curious why `-X` was broke scrolling, when the flag appears to have nothing to do with scrolling. Answer here: https://superuser.com/a/972232/165804

**Comment by jcrengifoa** [comment]
I finally figured it out!, go to preferences -> advanced -> mouse and modify the following options:
· Scroll on any wheel movement, no matter how small? -> yes
· Scroll wheel sends arrow keys when in alternate screen mode -> yes

![Screen Shot 2020-06-29 at 11 23 18](https://user-images.githubusercontent.com/8794284/86018091-3d9f4780-b9fb-11ea-9b1c-5d3785604b11.png)

**Comment by chenxiaochun** [comment]
@jcrengifoa , Thanks very much, resolve my problem

**Comment by david-mears-2** [comment]
This was fixed for me by following [this comment](https://askubuntu.com/questions/803486/can-i-scroll-to-new-lines-using-mouse-wheel-inside-git-diff?newreg=5b68dd9767674d57ba8e0ef0d14fdb24#comment2247497_1269951) on askubuntu (though I'm using a Mac): include `--mouse` after the `less --tabs=4 -RFX`
