### ISSUE TITLE
Save ~/.gitconfig before changes

### ISSUE THREAD

**Issue by Blaisorblade** [so-fancy/diff-so-fancy#248]
I accepted the suggested changes, looked at the result, and immediately had problems (I'll file a separate issue on those) so wanted to revert.
Sure, *I* should have made a backup, but maybe `diff-so-fancy` could be more careful than me.

And I don't want to be That Guy Who Hates Change (tm) (https://xkcd.com/1172/), but restoring old configs seems a reasonable request unless the customization is always perfect.

Of course, `~/.gitconfig` means "whatever `git config --global` updates", haven't checked if it's always that path.

**Comment by Blaisorblade** [comment]
(in this case, the issues I ran into with automatic configuration were #249 and #174), though I think this one is orthogonal. If you don't mind either way, feel free to say "OK if somebody sends a PR"—in that case I'll try to.

**Comment by scottchiefbaker** [comment]
There was general dislike to suggesting/setting colors. I'm going to remove this feature all together and just make it a suggestion to use non-default colors.
