### ISSUE TITLE
Recommended colors assume dark background

### ISSUE THREAD

**Issue by Blaisorblade** [so-fancy/diff-so-fancy#249]
Something in the recommended colors (the lines with 227, apparently) appears to use yellow.
Not good on a white background.
Other colors appear fine. For now I've disabled the 227 lines (`meta` and `commit`).

![image](https://user-images.githubusercontent.com/289960/28252497-611a239c-6a94-11e7-80d2-8c53db15d71b.png)

**Comment by OJFord** [comment]
@scottchiefbaker IMO it might be worth dropping the colour recommendations, given this and other issues?

The readme currently says "the default colours are not the best", but as far as I'm aware - please correct me if I'm wrong - the defaults are whatever the user has configured for their terminal emulator.

That is, the default is removals are `red`, additions are `green`, et al., but to exactly what `red`, `green`, et al. refer is defined by the terminal emulator configuration, or else _its_ defaults.

I don't personally think d-s-f should recommend overriding that; certainly not as strongly as in the readme's present incarnation.

**Comment by Blaisorblade** [comment]
Other changes are still expressed in terms of "high-level colors"—`red bold` should be safe for instance, and I honestly like it.

> That is, the default is removals are red, additions are green, et al., but to exactly what red, green, et al. refer is defined by the terminal emulator configuration, or else its defaults.

:+1:
- maybe d-s-f could use `yellow` instead of 227? That might be the only offender I noticed. (I don't get what `22` and `52` mean though—see below).
- if you want color schemes, you'll end up needing dark and light ones like Vim, Emacs, ... People go much crazier with their terminals, but those two seem the most supported choices.

Some other color might still make sense for white backgrounds—you're going for something high contrast.

On xterm I can indeed configure 16 base colors as @OJFord suggests, and d-s-f config mostly uses those. Only the lines with 227 are a problem—using `yellow` for 227 gives a slightly less bad result (I still don't recommend, but I have a chance of seeing what's shown with some effort).

Overall, this is what I'm using right now—it's d-s-f's suggestion minus the `227` lines:
```
[color "diff-highlight"]
        oldNormal = red bold
        oldHighlight = red bold 52
        newNormal = green bold
        newHighlight = green bold 22
[color "diff"]
        # meta = 227
        frag = magenta bold
        # commit = 227 bold
        old = red bold
        new = green bold
        whitespace = red reverse
```

> I don't personally think d-s-f should recommend overriding that; certainly not as strongly as in the readme's present incarnation.

It's not just the README—there's also a wizard. It defaults to not changing things, but it sounded safe and I trusted it.

```
$ diff-so-fancy
This appears to be the first time you've run diff-so-fancy, would you like to
configure git to use diff-so-fancy for all diff operations and use the
recommended color scheme (y/N)?
```

Now, doing this change on a deadline and then bothering to report a bug is *MY* choice—but "recommended colors" suggests it Just Works.

**Comment by Blaisorblade** [comment]
Linking to https://github.com/so-fancy/diff-so-fancy/issues/245#issuecomment-315517272 which discusses related color issues.

**Comment by scottchiefbaker** [comment]
I like the idea of have two color recommendations, one for light and one for dark backgrounds. I only really use a dark background so I don't know what people expect for light backgrounds. If you work up a recommendation for light backgrounds I'll include it.

**Comment by Blaisorblade** [comment]
:+1:, but I wouldn't wait for me. Maybe for now docs could point out the existing recommendation is for dark background?

**Comment by GloverDonovan** [comment]
Thanks for posting a solution. Changing `227` to `yellow` worked for me since it uses the yellow color defined in my color scheme.

From what I've seen only the hard-coded yellow is an issue. Would be great if a note about this was added to the readme.

**Comment by scottchiefbaker** [comment]
@Blaisorblade since you're a light background kind of guy will you please submit your config that works for a light background. I'll either add a `--light-background` option, or just update the docs to reflect the alternate choices.

It's been my experience that 80%+ of people use a dark background so that's what we've designed around.

**Comment by Blaisorblade** [comment]
@scottchiefbaker Presently using dark colors and can't find any such config, but apparently I mentioned one in https://github.com/so-fancy/diff-so-fancy/issues/249#issuecomment-315652101 ? Here's it again:

```
[color "diff-highlight"]
        oldNormal = red bold
        oldHighlight = red bold 52
        newNormal = green bold
        newHighlight = green bold 22
[color "diff"]
        # meta = 227
        frag = magenta bold
        # commit = 227 bold
        old = red bold
        new = green bold
        whitespace = red reverse
```

From what I wrote, this would be enough to close the issue (until somebody submits The Perfect Light Background Color Scheme (tm)).

**Comment by SebiTimeWaster** [comment]
what annoyed me the most is that i copied the color recommendation and now don't know how to go back to the standard (means more googling and copy/pasting).

and the color scheme from Blaisorblade hurts my eyes (sorry), i ended up with this:
```
[color "diff-highlight"]
	oldNormal = "#bb0000"
	oldHighlight = "#bb0000 reverse"
	newNormal = "#009900"
	newHighlight = "#009900 reverse"
[color "diff"]
	meta = "#0000cc"
	frag = "#333333 #dddddd"
	func = "#666666 #dddddd"
	old = "#bb0000"
	new = "#009900"
	whitespace = "#0000ff reverse"
```

**Comment by Blaisorblade** [comment]
> what annoyed me the most is that i copied the color recommendation and now don't know how to go back to the standard (means more googling and copy/pasting).

Is it enough to drop the lines from ~/.gitconfig work? Should the readme say that? I guess that should be a separate issue/PR.

----------

The original issue was probably fixed with @GloverDonovan's suggestion (quickly implemented). The lines I wrote are outdated (wasn't a careful design).

So I guess I should close this.
