### ISSUE TITLE
add or remove an empty file

### ISSUE THREAD

**Issue by stevemao** [so-fancy/diff-so-fancy#252]
Trying the `next` branch. when I add or remove an empty file, it doesn't display properly.

```
Z2l0IHNob3cgaGVhZApjb21taXQgYmIwMjcwYmE3MjVmMDg0NGFkMzcyNTJiZjFiZTcwNzY0NDIyZGFlYwpBdXRob3I6IFN0ZXZlIE1hbyA8bWFvY2hlbnlhbkBnbWFpbC5jb20+CkRhdGU6ICAgV2VkIEp1bCAxOSAxMjozODozOSAyMDE3ICsxMDAwCgogICAgUmV2ZXJ0ICJpIGRpZCBzb21ldGhpbmcgYXdlc29tZSEiCiAgICAKICAgIFRoaXMgcmV2ZXJ0cyBjb21taXQgODdlOWE1MDZmNDlmOTIzN2I1OTBhZjhmZDI5ZTkxYzJlYzQxZDM5Yi4KCmRpZmYgLS1naXQgYSBhCmRlbGV0ZWQgZmlsZSBtb2RlIDEwMDY0NAppbmRleCBlNjlkZTI5Li4wMDAwMDAwCgoKCmdpdCBzaG93IGhlYWQgLS1jb2xvcgobWzMzbWNvbW1pdCBiYjAyNzBiYTcyNWYwODQ0YWQzNzI1MmJmMWJlNzA3NjQ0MjJkYWVjG1ttCkF1dGhvcjogU3RldmUgTWFvIDxtYW9jaGVueWFuQGdtYWlsLmNvbT4KRGF0ZTogICBXZWQgSnVsIDE5IDEyOjM4OjM5IDIwMTcgKzEwMDAKCiAgICBSZXZlcnQgImkgZGlkIHNvbWV0aGluZyBhd2Vzb21lISIKICAgIAogICAgVGhpcyByZXZlcnRzIGNvbW1pdCA4N2U5YTUwNmY0OWY5MjM3YjU5MGFmOGZkMjllOTFjMmVjNDFkMzliLgoKG1sxOzMzbWRpZmYgLS1naXQgYSBhG1ttChtbMTszM21kZWxldGVkIGZpbGUgbW9kZSAxMDA2NDQbW20KG1sxOzMzbWluZGV4IGU2OWRlMjkuLjAwMDAwMDAbW20KZ2l0IGNvbmZpZyBwYWdlci5kaWZmCmdpdCBjb25maWcgcGFnZXIuc2hvdwo=
```

<img width="547" alt="screen shot 2017-07-19 at 12 38 32 pm" src="https://user-images.githubusercontent.com/6316590/28350209-baf61ba8-6c8a-11e7-801d-721b21463655.png">
<img width="654" alt="screen shot 2017-07-19 at 2 00 47 pm" src="https://user-images.githubusercontent.com/6316590/28350210-baf7ffc2-6c8a-11e7-914a-e6f67528ea08.png">

```
$ git --version
git version 2.13.1
hub version 2.2.9
```

The commits are on github :) https://github.com/stevemao/react-s3-uploader/commit/bb0270ba725f0844ad37252bf1be70764422daec

**Comment by scottchiefbaker** [comment]
Did it work before and it broke, or it's never worked properly?

**Comment by stevemao** [comment]
Not exactly sure. Just happened to see this yesterday...

**Comment by scottchiefbaker** [comment]
What should it do? You're expecting a red/green box to indicate the line?

**Comment by scottchiefbaker** [comment]
The input you supplied doesn't contain any line changes. 

Github says:  **Showing with 0 additions and 0 deletions**. 

I'm not sure what you're expecting.

**Comment by stevemao** [comment]
I think it should just say `added: newfile`
I don't think we should display red/green box since it's actually empty.
<img width="200" alt="screen shot 2017-07-20 at 2 28 37 pm" src="https://user-images.githubusercontent.com/6316590/28400633-ca565dba-6d57-11e7-92c7-fb011ad8d39e.png">

**Comment by scottchiefbaker** [comment]
Oh empty **FILE**... I misread this. Disregard I already implemented this on my local repo.

**Comment by scottchiefbaker** [comment]
But then it would be inconsistent? If you add a new file _with_ content it's green, but it you add an empty file it's yellow?

**Comment by stevemao** [comment]
are you saying green or yellow in the filename? I think the filename should be highlighted in green

**Comment by stevemao** [comment]
I don't think file content should have anything to do with the filename.
