### ISSUE TITLE
Should deleted and added files be highlighted too?

### ISSUE THREAD

**Issue by stevemao** [so-fancy/diff-so-fancy#253]
currently only renamed files are highlighted. Would it be better to highlight deleted and added files too?

A side note we should also update the screenshot to show highlighting in the filenames!

**Comment by scottchiefbaker** [comment]
Like make added files list in green, and deleted files in red?

**Comment by stevemao** [comment]
Yes

**Comment by scottchiefbaker** [comment]
Something like this?

![adddel](https://user-images.githubusercontent.com/3429760/28400488-453cc4be-6cc8-11e7-8d68-4a8c92989d4f.png)

**Comment by stevemao** [comment]
👍 
What do you think?

**Comment by scottchiefbaker** [comment]
I like it... it's consistent with file renames this way. These screen shots show how #252 will look.
