### ISSUE TITLE
How can I reset to the default color scheme

### ISSUE THREAD

**Issue by Jacksgong** [so-fancy/diff-so-fancy#259]
Hi, thanks for this tool, it's very useful but after I set the following configure:

```
git config --global color.ui true

git config --global color.diff-highlight.oldNormal "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"

git config --global color.diff.meta "227"
git config --global color.diff.frag "magenta bold"
git config --global color.diff.commit "227 bold"
git config --global color.diff.old "red bold"
git config --global color.diff.new "green bold"
git config --global color.diff.whitespace "red reverse"
```

I think the color is too light, I want to reset to the default color scheme first, is there any way to reset?

**Comment by OJFord** [comment]
If you'd never set them before, i.e. to actually get the git default, simply delete those entries from your `$XDGCONFIGHOME/git/config` (or `$HOME/.gitconfig`).

If you had set them to something else, and by 'default' you mean 'back' to before these commands, nope, if your config wasn't under version control then it's lost.

**Comment by Jacksgong** [comment]
@OJFord thank you, and I found `gitconfig` also can open with this way: `git config --global --edit`
