### ISSUE TITLE
generate a new screenshot with filename highlighted

### ISSUE THREAD

**Issue by stevemao** [so-fancy/diff-so-fancy#263]

**Comment by scottchiefbaker** [comment]
I think the "before" screenshot should be the default git colors, and the "after" should be our recommended colors.

**Comment by scottchiefbaker** [comment]
Using the old `git show 2c24b1d` we used for the previous screenshot I created this:

![d-s-f-ss2](https://user-images.githubusercontent.com/3429760/32387617-44c873da-c082-11e7-829c-6160b853adcb.png)

It's not perfect. 

I think @paulirish did the last one, cuz it looks better. Opinions on this new screenshot?

**Comment by stevemao** [comment]
Would be good if the screenshot includes renaming a file name
