### ISSUE TITLE
Better way to display indentation

### ISSUE THREAD

**Issue by sandrodz** [so-fancy/diff-so-fancy#264]
Often simple changes create a large patches because the only thing that changed was indentation, for example: adding a if/else loop and everything inside indented to the right.

Reviewing such a patch can be cumbersome because only line by line manual comparison can indicate if anything has essentially changed within the indented code. We may be speaking about a few lines of code only, or about dozens (or much more) of nested code. (I know: such an hypothetically large function would better be split into smaller functions, but that's beside the point).

while `git diff` has `-b` flag which mitigates this issue, it would be cool if diff-so-fancy could deal with this in an intelligent manner, instead of hiding indents with `-b` flag, it would actually display that only change is an indentation not the code itself.

**Comment by scottchiefbaker** [comment]
I'm a big fan of `git diff -w` for this type of thing. My first reaction is that this type of thing is outside the scope of d-s-f, but I might be wrong. Can you provide me a screenshot of the problem, and how `-b` fixes it.

**Comment by scottchiefbaker** [comment]
Any updates on this?

**Comment by scottchiefbaker** [comment]
Closing due to lack of input. Feel free to re-open if required.
