### ISSUE TITLE
minHunkLength

### ISSUE THREAD

**Issue by Dmole** [so-fancy/diff-so-fancy#266]
`git config --global diff-so-fancy.minHunkLength 3`

could help

my $change_**[hunk_indicators ](//:0)**    = 1;
my $change_**[chunk_indicators](//:0)**     = 1;

be shown as

my $change_hunk_indicators[_](//:0)    = 1;
my $change_[c](//:0)hunk_indicators     = 1;

and default to -1/null to maintain the original behavior.

(github formatting is failing me but look hard and you will understand)

**Comment by scottchiefbaker** [comment]
Can you elaborate? I'm really not understanding what you want to address/fix here.

**Comment by Dmole** [comment]
an option to only highlight the "c" and " " because "hunk_indicators" did not change.
regarding https://cloud.githubusercontent.com/assets/39191/13622719/7cc7c54c-e555-11e5-86c4-7045d91af041.png

**Comment by scottchiefbaker** [comment]
The intra-line highlighting it handled by [DiffHighlight.pm](https://github.com/git/git/blob/master/contrib/diff-highlight/DiffHighlight.pm), I don't know if they support a `minHunkLength` option. This suggestion is probably best run by them. Sometimes @peff lurks around here so he may have some feedback.

For now this is a CANTFIX issue because it's handled by an external library.

**Comment by Dmole** [comment]
**Not** "The best-lookin' diffs".
eclipse and vimdiff handle this scenario how I suggested.
There are a lot of other diff coloring tools maybe one has a better library that can be used.

**Comment by peff** [comment]
The highlighting done by diff-highlight (and which diff-so-fancy builds on) is not a true LCS diff between the lines. It just looks for common uninteresting bits near the edges, and then highlights the changed parts in the middle. So it can never produce an output with multiple highlights on the same line.

I've looked at doing a true diff, but you have to tokenize the lines in an intelligent way. Doing it byte-wise ends up with some pretty horrible results. See the "Bugs" section of https://github.com/git/git/blob/master/contrib/diff-highlight/README which discusses this. If you're interested, I can also dig up the discussions and experiments on the mailing list.

**Comment by Dmole** [comment]
peff, there is no need to experiment because other tools already do this (as already mentioned).

The setting for min length was requested to avoid "horrible" results and one could also use max diffs per line but basically it's not hard to make it better than it is without making it ridiculous. There is no fundamental issue.

**Comment by peff** [comment]
I'm open to using other heuristics in diff-highlight if they produce better results. But until somebody does the work to port the techniques used by other tools to diff-highlight, this discussion is pretty academic.

**Comment by Dmole** [comment]
As is everything that is not a pull request but this issue could be left open as a feature request.

**Comment by Dmole** [comment]
The other perl tool I was thinking of is https://github.com/git/git/tree/master/contrib/diff-highlight used like
`git diff --color=always | perl ~/scripts/imac/diff-highlight.pl`
