### ISSUE TITLE
Can't locate DiffHighlight.pm in @INC (you may need to install the DiffHighlight module)

### ISSUE THREAD

**Issue by stevemao** [so-fancy/diff-so-fancy#268]
With the head on the `next` branch, I got error

```
$ git show head
Can't locate DiffHighlight.pm in @INC (you may need to install the DiffHighlight module) (@INC contains: /Users/whitech/.nvm/versions/node/v6.10.3/bin/lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/whitech/.nvm/versions/node/v6.10.3/bin/diff-so-fancy line 11.
BEGIN failed--compilation aborted at /Users/whitech/.nvm/versions/node/v6.10.3/bin/diff-so-fancy line 11.
```

Works fine on commit 799e23a

I'm on the latest MacOS

**Comment by scottchiefbaker** [comment]
This may be related to #265 and/or #267. Can you try changing the line at the top to:

    use lib dirname(File::Spec->catdir($0)) . "/lib";   # Add the local lib/ to @INC

Is the d-s-f in your path a symlink?

**Comment by stevemao** [comment]
> Is the d-s-f in your path a symlink?

It is

**Comment by scottchiefbaker** [comment]
Interesting... this may be a MAC vs Windows vs Linux path substitution thing.

Did you try the above `use` line?

**Comment by stevemao** [comment]
I pulled and it works for me now. Maybe a78644d642180df5c873ffad71702a3f9ea6bc14 fixed this :)
