### ISSUE TITLE
Question: My diffs aren't as fancy as yours!

### ISSUE THREAD

**Issue by donifer** [so-fancy/diff-so-fancy#274]
So I followed the readme, installed with `brew` also added the colors from the readme section
>Improved colors for the highlighted bits

However my diffs look like this:
![image](https://user-images.githubusercontent.com/32689666/32386506-7df30686-c08f-11e7-9c9f-f60168384dc0.png)

I'm using iTerm and I'm sure this is 100% user error so I'm here asking for help. 

Can anyone help me out making my diffs fancier? Thanks!

**Comment by scottchiefbaker** [comment]
If you run `git config --list | grep color.diff` what do you see? Do the colors match what's in the suggested section of the README?

**Comment by donifer** [comment]
@scottchiefbaker I think so

```
❯ git config --list | grep color.diff
color.diff=auto
color.diff-highlight.oldnormal=red bold
color.diff-highlight.oldhighlight=red bold 52
color.diff-highlight.newnormal=green bold
color.diff-highlight.newhighlight=green bold 22
color.diff.meta=227
color.diff.frag=magenta bold
color.diff.commit=227 bold
color.diff.old=red bold
color.diff.new=green bold
color.diff.whitespace=red reverse
```

**Comment by scottchiefbaker** [comment]
Looks right to me... those colors assume a terminal that supports 256 colors. Is it possible your terminal doesn't support enough colors?

What platform/terminal are you using?

**Comment by donifer** [comment]
I'm using OSX with iTerm 3.1 with the proper `xterm-256color` flag.

<img width="569" alt="screen shot 2017-11-03 at 12 39 53 pm" src="https://user-images.githubusercontent.com/32689666/32388091-867f80cc-c094-11e7-9135-9d8a69cae5ab.png">

Not sure what I'm missing

**Comment by donifer** [comment]
Ahh figured out, I had custom colors in my iTerm preferences, I did a dumb, thanks!

**Comment by scottchiefbaker** [comment]
Ok glad it was easy.
