### ISSUE TITLE
Problems installing on Windows 10

### ISSUE THREAD

**Issue by UnderHeavyDevelopment** [so-fancy/diff-so-fancy#277]
I don't understand installation procedure. I did the following:
system: **Windows 10 + built-in bash**

```
$ cd ~
$ curl https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy -O
$ git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
$ cd my-git-repo
$ git diff
diff-so-fancy | less --tabs=4 -RFX: diff-so-fancy: command not found
```

What should I do to get it working?

**Comment by scottchiefbaker** [comment]
It looks like you put the script in `~`, which is probably not in your path? On Linux I usually put d-s-f in `~/bin/` but I'm not sure on Windows. You can check what directories are in your path with `echo $PATH`.

**Comment by UnderHeavyDevelopment** [comment]
Thank you for help. `echo $PATH` is contains couple more entries than Windows PATH variable. Then, I put `diff-so-fancy` inside `/c/Users/user/bin` directory, and it works (because this directory is listed when I do `echo $PATH`).
I created updated here https://github.com/so-fancy/diff-so-fancy/pull/282
