### ISSUE TITLE
Unable to quickly select a filename

### ISSUE THREAD

**Issue by lode** [so-fancy/diff-so-fancy#28]
When double clicking the filename the `a/` or `b/` is copied along. It would be great to remove that, or separate it with a space, or add the plain filename as a separate line as well, to be able to support this use case.

**Comment by stevemao** [comment]
I like the idea :)

**Comment by noscript** [comment]
There is an argument in `git diff`:
```
--no-prefix
           Do not show any source or destination prefix.
```

**Comment by stevemao** [comment]
Indeed. @lode does it work for you?

**Comment by paulirish** [comment]
@lode good usecase. i found myself using the click more and more often. :)

Since we already broke the patch format, there's no reason for us to preserve `a/` and `b/`, TBH. :)

Let's remove or improve it from our `format_diff_header` formatting.

**Comment by stevemao** [comment]
True, we are already hacking a lot. We'll just keep hacking I guess :)

**Comment by paulirish** [comment]
Cool. I'm preparing a short-term fix for this..  however

<hr>

Here's probably my ideal for these:

* If the two filenames are the same (the common case), then it doesnt need two lines. it could collapse and prefix with `modified: `
* If it's a new file we identify and denote that.
* etc.  

### Current behavior:
```sh

────────────────────────────────────────────────────────────────
-- a/.functions
++ b/.functions
────────────────────────────────────────────────────────────────
@@ -28,6 +28,19 @@ cdf() {  # short for cdfinder
…


new file mode 100644
────────────────────────────────────────────────────────────────
-- /dev/null
++ b/crontab
────────────────────────────────────────────────────────────────
@@ -0,0 +1,20 @@
```

### Proposed behavior:
```sh
────────────────────────────────────────────────────────────────
modified: .functions
────────────────────────────────────────────────────────────────
@@ -28,6 +28,19 @@ cdf() {  # short for cdfinder
…


new file mode 100644
────────────────────────────────────────────────────────────────
added: crontab
────────────────────────────────────────────────────────────────
@@ -0,0 +1,20 @@
```


how does this sound?

**Comment by noscript** [comment]
How will you handle renames:
```diff
 -- a/oldFile
 ++ b/newFile
```

Doesn't `--no-prefix` do the job?

**Comment by paulirish** [comment]
@noscript ideally, we do "moved: ". Certainly requires a few lines of work to pull it off.

`--no-prefix` is can only be applied on the  `git diff` command so it's not something we can do on our side. 

And I'm arguing that preserving `a/` and `/b/ in our output doesnt have value, and supporting cmd-click is more worthwhile. So we might as well translate these odd prefixes to something that makes sense.

**Comment by noscript** [comment]
> it's not something we can do on our side. 

I wonder if there really a need to do something that can be achieved out-of-the box by git.

Besides, messing with prefixes will break `git diff` output for those who do use `--no-prefix` already.

**Comment by paulirish** [comment]
Perhaps we should recommend setting `git config --global diff.noprefix true` to our users who are interested in this feature.

**Comment by lode** [comment]
I didn't know about the `--no-prefix`, that helps for sure. But, as you also noted @paulirish, the whole idea of two lines is a bit strange. When it can also be presented in a single line with a meaningful prefix like `added`, `moved`, etc.

**Comment by paulirish** [comment]
Sg. I think we can document the flag and global config for now. 

And then long-term work towards a clearer header with `added/moved/changed`. I hesitate to do that work without a more substantial parsing setup, though.

**Comment by paulirish** [comment]
@lode can you give us a PR for the `git config --global` line added to the readme?

**Comment by scottchiefbaker** [comment]
@paulirish I really like your suggestions here. The one line setup makes a lot more sense to me, and would save screen real estate also. This suggestion gets a +1 from me.

**Comment by scottchiefbaker** [comment]
@noscript I'm working on tests and I cannot get diff to show me the "rename" syntax you describe. If I do a `git mv foo.txt bar.txt` the diff output is to delete `foo.txt` and add `bar.txt`. Am I missing something on file renames?

If so, can you provide me with some `git diff` output I can put in my tests.

**Comment by paulirish** [comment]
I think the output you're dealing with is the same, yah.

**Comment by scottchiefbaker** [comment]
Now that #90 has landed I think we can close this.

**Comment by paulirish** [comment]
Yup and 90 is compatible with both `diff.noprefix true` and `diff.noprefix truediff.noprefix false`
