### ISSUE TITLE
Windows 10 + WSL + Hyper pb diff-highlight

### ISSUE THREAD

**Issue by tdurand** [so-fancy/diff-so-fancy#281]
Hi, 

I searched but I was unabled to find a similar issue, I get this coloring diff that makes me unable to see the diff-highlight:

![terminaldiff](https://user-images.githubusercontent.com/533590/35247265-887b453e-ffa8-11e7-80cd-d5474a6897f4.jpg)

I have this config:

```
[color "diff-highlight"]
        oldNormal = red bold
        oldHighlight = red bold 52
        newNormal = green bold
        newHighlight = green bold 22
```

Someone experienced a similar issue ?

Thanks

**Comment by scottchiefbaker** [comment]
That's really weird... those a pretty standard ANSI colors. They are in the 256 color spectrum, and not all terminals support that. Are you using `cmd.exe` or `powershell`? Does it do the same thing under both?

**Comment by tdurand** [comment]
I'm using bash via Windows Linux Subsystem : https://docs.microsoft.com/en-us/windows/wsl/install-win10 . I didn't install git on the windows side of things. It might be a bug of WSL but weird no one reported it.. I'm investigating

**Comment by tdurand** [comment]
Seems a bug of hyper : https://github.com/zeit/hyper/issues/1968 

Closing here, I'll update if I find a fix.

Thanks

**Comment by scottchiefbaker** [comment]
I'm guessing you're having problems with the `red bold 52` and `green bold 22`. 

That string format is: foreground-color / bold (optional) / background-color. Try changing the background-color to something else and see if the problem goes away. Something simple like 

```
[color "diff-highlight"]
        oldNormal = red bold
        oldHighlight = red bold blue
        newNormal = green bold
        newHighlight = green bold blue
```

Might shine more light on what the exact issue is.

**Comment by tdurand** [comment]
Yes, it is that, with "native" powershell it works, it's the https://hyper.is/ which doesn't support them

Thanks!
