### ISSUE TITLE
Removal of an empty line doesn't show red block

### ISSUE THREAD

**Issue by donileo** [so-fancy/diff-so-fancy#283]
In this first image you can see the change was the removal of an empty line:

This is with: git config --bool --global diff-so-fancy.stripLeadingSymbols false
<img width="680" alt="screen shot 2018-01-29 at 3 28 35 pm" src="https://user-images.githubusercontent.com/1881038/35532732-431fee70-0509-11e8-9e8a-c61154f86f5b.png">

With: git config --bool --global diff-so-fancy.stripLeadingSymbols true which is my preferred output the following shows:
<img width="736" alt="screen shot 2018-01-29 at 3 29 19 pm" src="https://user-images.githubusercontent.com/1881038/35532743-51664010-0509-11e8-888b-bf38f0c984ad.png">

What I'm expecting is that the removal of the empty line show a red block signifying the line was removed as the green block in the second image shows the addition of a new line.

Loving this project by the way!

**Comment by stevemao** [comment]
What version are you using? Can you paste the raw diff by following https://github.com/so-fancy/diff-so-fancy/blob/master/reporting-bugs.md

**Comment by donileo** [comment]
Here is the raw file:
[diff.txt](https://github.com/so-fancy/diff-so-fancy/files/1686717/diff.txt)

**Comment by scottchiefbaker** [comment]
The problem here is that this is NOT an empty line. It's a line with two spaces on it so it being treated as if it has actual content. The red deleted box only show for a line that is a single '\n' and is removed/added.

**Comment by donileo** [comment]
Thanks makes sense!
