### ISSUE TITLE
Support for color-moved?

### ISSUE THREAD

**Issue by brandonweiss** [so-fancy/diff-so-fancy#284]
I saw [this tweet](https://twitter.com/SmileyKeith/status/946554839944724480) and tried it out, but couldn't figure out why it wasn't working, and then realized it's probably because diff-so-fancy doesn't support it? Is that right? And if so, could it?

**Comment by OJFord** [comment]
Only by re-implementing the heuristic for moved lines; currently dsf doesn't do any diffing, just manipulates existing symbols in git's output. But in 'moved' lines we still see the usual `+` and `-` in the first column, nothing to indicate that it's 'moved' versus any other addition and deletion.

So: yes, you're right; yes, it could, but it's probably out of scope.

**Comment by brandonweiss** [comment]
Ah yeah, I get it now, that totally makes sense. Don't feel bad about closing this, if you want! I probably would not add this feature if it was my project. 😂

Also, thanks for your hard work on this!

**Comment by OJFord** [comment]
It would be nice, I agree, just quite a change from the current model.

> thanks for your hard work on this!

I take no credit whatsoever! 😆 (So maybe I _should_ promise the world...?)

**Comment by scottchiefbaker** [comment]
Two things:

1. I didn't even know this was a feature. It's really cool so I'm going setup my diff to use this by default
2. I did some tests with existing d-s-f and we already support this. See bellow:

![zebra](https://user-images.githubusercontent.com/3429760/35816254-20122a4c-0a4f-11e8-9828-10dc5718264c.png)

D-s-f doesn't do anything with the existing ANSI codes from Git, so in this case things "just worked". Git colors the moved lines differently and d-s-f just passes that through.

**Comment by scottchiefbaker** [comment]
@brandonweiss is this feature not working for you? What's not working?

**Comment by Mange** [comment]
It works for me too. I think this can be closed.

**Comment by brandonweiss** [comment]
Wow, this took me forever to figure out.

The issue was that I had `color.diff` set to `auto`. It seems to override `diff.colorMoved`–not sure why.

Sorry about that!
