### ISSUE TITLE
Not working correctly when there is a new-line

### ISSUE THREAD

**Issue by boris-petrov** [so-fancy/diff-so-fancy#286]
The title is a bit vague, but I don't know what to write. :) Check out the attached diff file to see the issue.

[diff.txt](https://github.com/so-fancy/diff-so-fancy/files/1716030/diff.txt)

**Comment by daften** [comment]
Do you mean individual characters aren't highlighted when there's a set of changes on multiple lines?

**Comment by boris-petrov** [comment]
@daften - yes, you can see that the first and the second changes are being displayed "correctly" - i.e. you can see what was removed. But for the last "big" change - it does not. And this is only because of line 50 in the diff file attached, which is a removed new line at the end of the file. If that change is removed, then the highlighting is correct. Can you see what I mean?

**Comment by daften** [comment]
Yes, I see what you mean :)
Seems like a bug, let's hope somebody fixes it (my perl skills are non-existent).

**Comment by scottchiefbaker** [comment]
Unless I'm missunderstanding it looks like this is fixed in the v1.2.5. If not please re-open this issue and I'll investigate.

**Comment by boris-petrov** [comment]
@scottchiefbaker - this new version is still not pushed on npm. :)

**Comment by scottchiefbaker** [comment]
paging @OJFord I think he handles the NPM stuff?

**Comment by OJFord** [comment]
@scottchiefbaker Nope, sorry!
