### ISSUE TITLE
Not possible to set 'func' color

### ISSUE THREAD

**Issue by szafranek** [so-fancy/diff-so-fancy#290]
git diff supports setting a `func` color, for the function name appearing in the hunk.

Unfortunately, after installing diff-so-fancy it's not possible to customize that color anymore via git config.

PS. I love this tool, thank you for making it!

**Comment by scottchiefbaker** [comment]
Can you provide a screenshot or some more details? I'm not aware of `func` color being a thing.

**Comment by szafranek** [comment]
It's documented here:
https://git-scm.com/docs/git-config#git-config-colordiffltslotgt
(for whatever reason, the docs don't highlight it, like they do with `hunk`)

Here's a test:
```
git config --global color.diff.func magenta
git --no-pager diff
```
![image](https://user-images.githubusercontent.com/152606/36912752-132bb7be-1e48-11e8-8aa1-2402c78f6f1f.png)

Unfortunately, it's not respected by diff-so-fancy:

```
git diff
```
![image](https://user-images.githubusercontent.com/152606/36912824-49d5d0ec-1e48-11e8-8d8e-0880ed91f199.png)

**Comment by scottchiefbaker** [comment]
I didn't even know that was a feature. 

I believe I just updated d-s-f to support this. Can you test the `next` branch and see if that fixes the issue for you?

**Comment by szafranek** [comment]
It took me a moment to notice you meant the `next` branch in your fork :).
But it does work, thank you!!!

**Comment by scottchiefbaker** [comment]
Oh... my bad. I did forgot to push it here :) Well you figured it out either way. At least it's working!
