### ISSUE TITLE
Bug in displaying procfile diff

### ISSUE THREAD

**Issue by AlexEvanczuk** [so-fancy/diff-so-fancy#291]
Diff won't display:
```
~/workspace/sensei - (master) $ cat Procfile
web: bin/hubot --adapter slack -n sensei
~/workspace/sensei - (master) $ g co ae-sensei-upgrade
Switched to branch 'ae-sensei-upgrade'
Your branch is up-to-date with 'origin/ae-sensei-upgrade'.
~/workspace/sensei - (ae-sensei-upgrade) $ cat Procfile
web: bin/hubot --adapter slack -n sensei_upgrade
~/workspace/sensei - (ae-sensei-upgrade) $ git --no-pager diff master
diff --git a/Procfile b/Procfile
index 8a3c3cc..a9aa9c2 100644
--- a/Procfile
+++ b/Procfile
@@ -1 +1 @@
-web: bin/hubot --adapter slack -n sensei
+web: bin/hubot --adapter slack -n sensei_upgrade

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: Procfile
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/^((?^:(\e\[([0-9]{1,3}(;[0-9]{1,3}){0,3})[mK])?))[ +-]{ <-- HERE -1}/ at /usr/local/lib/node_modules/diff-so-fancy/libexec/diff-so-fancy.pl line 344, <> line 6.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ Procfile:1 @
```

**Comment by scottchiefbaker** [comment]
Interesting... What version of Perl are you running?

Can you post the raw diff with out [bug reporting tool](https://github.com/so-fancy/diff-so-fancy/blob/master/reporting-bugs.md).

**Comment by AlexEvanczuk** [comment]
Actually the diff works when I use the bug reporting tool.  I'd rather not attach the full output since it contains a lot of proprietary code, but I can reproduce a smaller, non-proprietary version of the bug if necessary and use that tool, but it appears to be just the normal diff.

Here's my perl:
```
~/workspace/bot - (ae-bot-upgrade) $ perl -v

This is perl 5, version 26, subversion 0 (v5.26.0) built for darwin-thread-multi-2level

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by scottchiefbaker** [comment]
Looks like you're on a Mac with pretty modern Perl. I can only guess the diff is something we're not used to seeing and it's breaking the regexp. If you can simply the diff I'll gladly take a look at fixing things.

**Comment by AlexEvanczuk** [comment]
Thanks for the quick responses!  I posted the original file, new file, and diff above :)

**Comment by scottchiefbaker** [comment]
I don't see any new posts with diffs.

**Comment by AlexEvanczuk** [comment]
Sorry for the confusion. The original post has the diff.

**Comment by scottchiefbaker** [comment]
The issue here is that ANSI colors that git puts on the diff. That regexp is attempting to match the ANSI color codes. Can you do `git diff --color=always > /tmp/raw.txt` and post that somewhere?

**Comment by AlexEvanczuk** [comment]
```
~/workspace/sensei - (ae-diff-bug) $ git diff master --color=always > /tmp/raw.txt
~/workspace/sensei - (ae-diff-bug) $ cat /tmp/raw.txt
diff --git a/Procfile b/Procfile
index 8a3c3cc..e367df2 100644
--- a/Procfile
+++ b/Procfile
@@ -1 +1 @@
-web: bin/hubot --adapter slack -n sensei
+web: bin/hubot --adapter slack -n bot
```

**Comment by scottchiefbaker** [comment]
Still no ANSI codes on that... Something must be up with your git?

This looks like a pretty standard one line diff to me. When I run it through (without the ANSI colors) d-s-f I don't get any errors. Not sure what's going on here.

**Comment by AlexEvanczuk** [comment]
I'm not sure what I'm doing.  If it helps, here is some of my configuration around colors and d-s-f.

```
color.diff-highlight.oldnormal=red bold
color.diff-highlight.oldhighlight=red bold 52
color.diff-highlight.newnormal=green bold
color.diff-highlight.newhighlight=green bold 22
core.pager=diff-so-fancy | less --tabs=4 -RFX
```

Also, I run git diff with `-w` by default which strips whitespace, but I don't think that will affect this.

**Comment by scottchiefbaker** [comment]
If you just run `git diff` you see colored d-s-f output? But if you run `git diff master --color=always > /tmp/raw.txt` that file doesn't have any ANSI color in it? That's super weird. Maybe that's a Mac thing? I dunno what to tell you. Can you try using this [d-s-f](https://www.perturb.org/tmp/diff-so-fancy) and see if it solves your problem.

**Comment by scottchiefbaker** [comment]
Can you test with version 1.2.5? We expanded support for complex ANSI codes.

**Comment by scottchiefbaker** [comment]
I'm closing this due to staleness. If this is still an issue please re-open.
