### ISSUE TITLE
Color format of diff-highlight.oldHighlight 

### ISSUE THREAD

**Issue by rongi** [so-fancy/diff-so-fancy#292]
color.diff-highlight.oldHighlight "red bold **52**"

This **52** thing. Which color format is this?

**Comment by scottchiefbaker** [comment]
Standard [ANSI 256](https://github.com/scottchiefbaker/perl-git-prompt/blob/master/utils/term-colors.pl) color numbering.

**Comment by rongi** [comment]
Thank you
