### ISSUE TITLE
[git 2.17.0] fatal: mismatched output from interactive.diffFilter

### ISSUE THREAD

**Issue by boris-petrov** [so-fancy/diff-so-fancy#296]
I have the following in my `.gitconfig`:

```
[interactive]
	diffFilter = diff-so-fancy --patch-mode | less --tabs=4 -RFX
```

Doing a `git add -p` fails with this:

```
fatal: mismatched output from interactive.diffFilter
hint: Your filter must maintain a one-to-one correspondence
hint: between its input and output lines.
```

This didn't happen before git 2.17.0. Help! I cannot live without dsf, what do I do?!

**Comment by scottchiefbaker** [comment]
This is related to #35. D-s-f and patch mode are not currently compatible.

**Comment by boris-petrov** [comment]
But it was working (almost) fine up to now. Is there some workaround that I could use?

**Comment by scottchiefbaker** [comment]
@boris-petrov downgrade Git? Git decided to make that change to avoid people hitting bug #35. There may be a potential solution in some code to upstream git. That was recently mentioned in #35.

I'm going to close this for now. If you have further comments about working around this I think we should move them to #35.

**Comment by OJFord** [comment]
This also affects `diff-highlight` by the way, so it couldn't be fixed in dsf until also fixed there.

**Comment by vanniktech** [comment]
I ran into this once I added:

```
[diff]
	colorMoved = dimmed_zebra
```

and used `git add -p`

**Comment by jesstelford** [comment]
Downgrading git is no longer a viable strategy with the [remote code vulnerability in git <2.17.1](https://marc.info/?l=git&m=152761328506724&w=2).

@scottchiefbaker could we re-open this issue until it's fixed?

**Comment by scottchiefbaker** [comment]
@jesstelford I could re-open this... but the core issue is #35. I think maybe we move things over there?

I'm open to suggestions.

**Comment by jesstelford** [comment]
Apologies, I thought #35 was dead - 10months with no updates (on either side). Happy to leave the discussion there.

**Comment by scottchiefbaker** [comment]
It's only "dead" in the sense that we can't fix anything on the d-s-f side to make it work. We need some upstream work on Git done.

**Comment by HaleTom** [comment]
@scottchiefbaker where can we find the description of the required upstream work? Have the `git` devs been notified?

**Comment by adamtaylor13** [comment]
Even after removing this from my config I still can't use `git add -p`. Getting the same "fatal: mismatched output" error. Is this a larger problem with git itself? I even tried downgrading and I'm now on 2.17.1 and I cannot use `git add -p` at _all_. Pretty annoying. Any thoughts??

**Comment by dougpagani** [comment]
> Even after removing this from my config I still can't use `git add -p`. Getting the same "fatal: mismatched output" error. Is this a larger problem with git itself? I even tried downgrading and I'm now on 2.17.1 and I cannot use `git add -p` at _all_. Pretty annoying. Any thoughts??

@adamtaylor13 It's been about a half-year since you asked, but in case you still don't have a way of solving this, or in case someone else reads your comment and wishes for a quick & easy solution...

Git is trying to use `diff-so-fancy` as the `interactiveDiffFilter`. This can be frustrating to resolve, because if you configure it as a more general "filter" option, the config will still propagate down. It can come from global gitconfig (`~/.gitconfig`), local gitconfig (`./.git/config`), and in a few different filter options in different groupings. 

This solution is guaranteed to work, since it will mask any other config options declared in the multiple levels: **add `-c "interactive.diffFilter=less`** as an option to your `git` call:

_e.g._
```bash
git -c 'interactive.diffFilter=less' add -p README.md
```

**Comment by Pistos** [comment]
The `-c` workaround posted by @dougpagani can also be accomplished via `~/.gitconfig`:

```.gitconfig
[alias]                                                                                                              
  addp = -c 'interactive.diffFilter=less' add -p
```

**Comment by flypenguin** [comment]
so ... is this possible or not? the main page README says i can do it, yet I did and i get this error. i am confused. any info?

**Comment by tbjers** [comment]
> so ... is this possible or not? the main page README says i can do it, yet I did and i get this error. i am confused. any info?

It's been working for months and months, and now it no longer works again. 😅

**Comment by vraravam** [comment]
same with me - it stopped working a few weeks ago! I have the latest `git` and `diff-so-fancy`, both installed and updated via `homebrew`

**Comment by jm-janzen** [comment]
Previously I had `diff-so-fancy | less -RFX` globally as both my git pager and interactive diff, but suddenly I guess I can't do that anymore. I've just gone ahead and set `git config --global interactive.diffFilter less` and that seems to let me use `git add --patch` like before.

git version 2.43.0
Diff-so-fancy version 1.4.2

**Comment by scottchiefbaker** [comment]
With Git v2.43.5 this config works for me:

```
[core]
    pager = diff-so-fancy | less --tabs=4 -RF
[interactive]
    diffFilter = diff-so-fancy --patch
```

this is also recommended in the README.
