### ISSUE TITLE
setting diff-so-fancy as core.pager breaks git diff and git stash list

### ISSUE THREAD

**Issue by praveenpuglia** [so-fancy/diff-so-fancy#297]
Before setting diff-so-fancy as the `core.pager` everything seems to be working fine. But right after setting it as instructed in the readme, those functionalities break.

I see a flash of the content I should see after executing `git stash list` or `git diff` and then it comes back to prompt. 

Removing `~/.gitconfig` and trying the commands again make them work again. So I am thinking that this is diff-so-fancy issue.

Here's a gif showing the same.

Please let me know if you need anything else from me!

https://gfycat.com/gifs/detail/NervousArtisticIrukandjijellyfish

```sh
> diff-so-fancy --version
Diff-so-fancy: https://github.com/so-fancy/diff-so-fancy
Version      : 1.2.0
```

**Comment by scottchiefbaker** [comment]
The weird thing is that you're setting d-s-f as the `diff` tool, which has **nothing** to do with stash. My first thought is some sort of terminal/less conflict. Can you try running d-s-f via a pipe:

    git diff --color | diff-so-fancy

What OS, and terminal are you using?

**Comment by praveenpuglia** [comment]
Piping worked! 😮 !

Happens on any terminal. I have tried default Terminal app, iterm2 and the integrated terminal in VSCode.

Mac OS 10.13.4

**Comment by scottchiefbaker** [comment]
If piping worked that means it has nothing to do with d-s-f. The default config uses `less` (but not for single screens). Try removing the `-F` and see if that changes things? 

I'm 99% sure this is a `less` thing.

**Comment by praveenpuglia** [comment]
Wow! removing -F worked! But can you please explain to me why it worked?

**Comment by scottchiefbaker** [comment]
`-F` tells less NOT to use a pager if the output is less than one screen worth of data. My guess is there is some conflict between your terminal and less. I haven't heard of any OS X + less bugs, but obviously you just ran in to one. 

Congratulations?

**Comment by praveenpuglia** [comment]
Ha ha! Looks like I did. The hard part is not knowing whom to report it to and seems mysterious. Thanks for the resolution though. If I do find out anything, I'll come back here and update.

**Comment by scottchiefbaker** [comment]
👍
