### ISSUE TITLE
Congrats on 10k github stars!

### ISSUE THREAD

**Issue by paulirish** [so-fancy/diff-so-fancy#301]
![image](https://user-images.githubusercontent.com/39191/40879167-487f7260-669c-11e8-9dea-107913139838.png)

**Congrats to all the contributors!**

And also to @scottchiefbaker in particular who's done an excellent job maintaining this project.

🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by scottchiefbaker** [comment]
GO TEAM!
