### ISSUE TITLE
shareable pretty diff?

### ISSUE THREAD

**Issue by AlJohri** [so-fancy/diff-so-fancy#302]
this may be out of scope, but I would love to see the exact pretty diff on my terminal in a shareable way. particularly I really like the highlighted changed characters.

https://www.diffchecker.com/ does something similar but only in a split view, not a unified view. nifty cli tool though!

this tool gets close, but it doesn't bold highlight the changed characters https://github.com/scottgonzalez/pretty-diff

**Comment by scottchiefbaker** [comment]
You want a HTML version? If so, that may be out of the scope of this tool.

**Comment by AlJohri** [comment]
@scottchiefbaker yeah, I think so- honestly I'd be fine like a really long screenshot of the terminal diff if it was shareable... but I think you're right, this would probably end up being HTML.

**Comment by AlJohri** [comment]
Ah, I found that if I upload the previous and latest versions of a file to a gist consecutively and then click on Revisions, the diff is very nice and shareable. It even has a great split view.

I was previously uploading the content of `git diff` to a gist which had a less than ideal output.
