### ISSUE TITLE
Installation problem (Lack of Documentation)

### ISSUE THREAD

**Issue by Kartikkh** [so-fancy/diff-so-fancy#303]
How to install it globally for every repository?

**Comment by plgruener** [comment]
Maybe you could elaborate more on what did not work for you? Was it either
1) install and run it on your system?
  if so, what OS do you use? diff-so-fancy itself is a simple executable perl script, just try to download and run it manually if the packaged version does not work.
2) configuring git to use diff-so-fancy?
there is only one line in the readme under "usage", which explains it all, as well as the `--help` option:
just run `git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"`
the `--global` option should do exactly what you want.
alternatively, see the [pro tips](https://github.com/so-fancy/diff-so-fancy/blob/master/pro-tips.md)

**Comment by scottchiefbaker** [comment]
@plgruener looks to have provided a couple solutions so I'm closing this. If you're still having issues please re-open this.
