### ISSUE TITLE
suggestion: clarify that this is not a "diff" replacement

### ISSUE THREAD

**Issue by fleminra** [so-fancy/diff-so-fancy#306]
May I humbly suggest that somewhere prominently in README.md, you include text along the lines of "diff-so-fancy is a beautifying filter (or pager?) for the output of `git diff`". I had the initial impression that this tool was a drop-in `diff` replacement, similar to `colordiff`. Is diff-so-fancy specific to Git? I tried piping a normal `diff` invocation to it, and piping `hg diff` to it, but didn't see the expected beautification.

**Comment by scottchiefbaker** [comment]
If you check out the `next` branch we're working on support for both **Mercurial** and standard **diff** formats.

**Comment by fleminra** [comment]
Great! I'll look forward to it.

**Comment by scottchiefbaker** [comment]
I'm going to close this for now as it's a work in progress. Actually it's 95% already working, I probably just need to do a release of the `next` branch to get it out to people.
