### ISSUE TITLE
Setting -+X option for less

### ISSUE THREAD

**Issue by rronen** [so-fancy/diff-so-fancy#307]
Trying to configure diff-so-fancy to always open in full screen and then clear on exit, which generally is the default for less I believe (though not less in the context of git diff). It seems like the way to achieve this is:
```
git config --global core.pager "diff-so-fancy | less --tabs=4 -RF -+X"
```
Which generally gives the desired effect, except for when I am diff'ing a specific file, i.e.
```
git diff path/to/my/file.json
```
In this case the screen flashes for a second and nothing is shown at all.

Any ideas on how to make it (the `-+X` option) work in general?

I realize this may be more a question about git+less interaction, so would totally understand if you want to close and ignore. 

E.g., this also has the same problem
```
git config --global core.pager "less --tabs=4 -RF -+X"
```
whereas this just behaves normally:
```
git config --global core.pager "less --tabs=4 -RFX"
```

**Comment by scottchiefbaker** [comment]
Are you on OS X? What platform/terminal are you using?

**Comment by rronen** [comment]
OS X High Sierra 10.13.4 (17E199).  Terminal App.

**Comment by scottchiefbaker** [comment]
I think I recall that there was a bug with `less` and OS X. Have you tried an alternate terminal? I'll see if I can dig up the bug. 

In the end the "bug" was a `less` and the terminal. I don't think this is anything d-s-f can fix.

**Comment by scottchiefbaker** [comment]
I think maybe we're running in to #246 again.

**Comment by rronen** [comment]
Just to update on this: it indeed seems to be caused by the faulty `less` distributed with OS X. 

But happily a simple `brew install less` resolved it completely.

**Comment by rdsedmundo** [comment]
Installing a new `less` didn't work for me unfortunately. Removing the `-X` flag makes it work:

```
pager = diff-so-fancy | less --tabs=4 -RF
```
