### ISSUE TITLE
Windows doesn't have `\dev\null`

### ISSUE THREAD

**Issue by dmsul** [so-fancy/diff-so-fancy#311]
I am using Windows 10. When I set `d-s-f` as my pager I get the following output before the usual output after a diff or log:

```console
$ git diff HEAD^^ HEAD
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
# Normal output from here...

$ git log
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
# Normal output from here...
```

This happens whether I am running from git bash, cmd, or PowerShell (git and Strawberry perl are in the PATH of all).

I believe the problem is that Windows uses `nul` instead of `\dev\null`. See [here](https://github.com/dbuenzli/cmdliner/issues/10#issuecomment-56495035). If I replace every instance of `\dev\null` with `nul`, the "cannot find the path" error goes away. (However, it just change the colors so that anything but the default colors have backgrounds, but that's a separate issue.)

**Comment by scottchiefbaker** [comment]
I just tested with `git-bash` and d-s-f works just fine.

```
Scott Baker@DESKTOP-TACE3DQ MINGW64 ~/diff-so-fancy (master)
$ ls /dev/null
/dev/null
```

**Comment by dmsul** [comment]
It's probably because I'm using the system (Windows) perl instead of the git-bash perl.

**Comment by dmsul** [comment]
In CMD:

```
C:\Users\sullivan
λ perl bin\diff-so-fancy
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Diff-so-fancy: https://github.com/so-fancy/diff-so-fancy
Version      : 1.2.0

Usage:

git diff --color | diff-so-fancy # Use d-s-f on one diff
diff-so-fancy --colors           # View the commands to set the recommended colors
diff-so-fancy --set-defaults     # Configure git-diff to use diff-so-fancy and suggested colors

# Configure git to use d-s-f for *all* diff operations
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

C:\Users\sullivan
λ perl bin\diff-so-fancy-win
Diff-so-fancy: https://github.com/so-fancy/diff-so-fancy
Version      : 1.2.0

Usage:

git diff --color | diff-so-fancy # Use d-s-f on one diff
diff-so-fancy --colors           # View the commands to set the recommended colors
diff-so-fancy --set-defaults     # Configure git-diff to use diff-so-fancy and suggested colors

# Configure git to use d-s-f for *all* diff operations
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

```

In PowerShell

```
C:\Users\sullivan
λ  perl bin\diff-so-fancy
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Diff-so-fancy: https://github.com/so-fancy/diff-so-fancy
Version      : 1.2.0

Usage:

git diff --color | diff-so-fancy # Use d-s-f on one diff
diff-so-fancy --colors           # View the commands to set the recommended colors
diff-so-fancy --set-defaults     # Configure git-diff to use diff-so-fancy and suggested colors

# Configure git to use d-s-f for *all* diff operations
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

C:\Users\sullivan
λ  perl bin\diff-so-fancy-win
Diff-so-fancy: https://github.com/so-fancy/diff-so-fancy
Version      : 1.2.0

Usage:

git diff --color | diff-so-fancy # Use d-s-f on one diff
diff-so-fancy --colors           # View the commands to set the recommended colors
diff-so-fancy --set-defaults     # Configure git-diff to use diff-so-fancy and suggested colors

# Configure git to use d-s-f for *all* diff operations
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
```

**Comment by scottchiefbaker** [comment]
I'm confused what you're changing. d-s-f doesn't use `/dev/null` for anything. The only references to `/dev/null` in the code are when it parses the diff headers.

**Comment by dmsul** [comment]
I literally just search & replaced `/dev/null` to `nul`. The exact thing I did in vim was `:%s/\/dev\/null/nul/g`.

Source d-s-f has the warnings; after the replacement, it has no warnings.

**Comment by webstech** [comment]
The problem is in DiffHighlight.pm:
my $s = `git config --get-color $key 2>/dev/null`;
This line is causing the message to be issued for windows version of Perl.
I submitted a pull request to fix this.

**Comment by scottchiefbaker** [comment]
I believe this is address in version 1.2.5 which I just released. If not, please reopen this issue and let me know.

**Comment by scottchiefbaker** [comment]
Oh I see what happened. We **did** fix this but it looks like that change got lost in the merge? I went ahead and cherry-picked it and it's in `next` now. Sorry for the confusion.

**Comment by dmsul** [comment]
No worries at all. This is an amazing tool and I appreciate all the work that goes into it.

I checked out `next` and that indeed does the trick. Thanks again!

**Comment by webstech** [comment]
fyi, I plan to submit another pull request once the change is part of git so the files are the same.  The change was adjusted a little bit for the git pull request.  Not sure how long it will take to get into git (pull request was done last Oct).
