### ISSUE TITLE
Feature Idea: option to set ruler to fixed width (e.g. 80 chars)

### ISSUE THREAD

**Issue by dwaltrip** [so-fancy/diff-so-fancy#313]
I've hardcoded this for now on my machine, by updating [line 528](https://github.com/so-fancy/diff-so-fancy/blob/c18fe128682c24a72b3319b06166cd5c0841acd9/diff-so-fancy#L528) to: `my $width = 80;`, which works great.

**Comment by scottchiefbaker** [comment]
This was fixed in 668bebe10f8dce930a4491b8a358f1c3f359e453 which was just released as part of v1.2.5

**Comment by dwaltrip** [comment]
Awesome thanks!
