### ISSUE TITLE
Pro-tip on "Moving around in the diff" breaks `git stash list` for non-empty stashes

### ISSUE THREAD

**Issue by gimbo** [so-fancy/diff-so-fancy#316]
The [pro-tip about "Moving around in the diff"](https://github.com/so-fancy/diff-so-fancy/blob/master/pro-tips.md#moving-around-in-the-diff) seems to break `git stash list` for non-empty stashes.  For me, at least, it seems the `--pattern` part searches for a pattern which isn't there, and I see a "Pattern not found" error rather than the actual stash list.

On a non-empty stash:

```
$ git rev-parse stash
d3d86e379483385038c345aa69bf3c4a01a0c591

$ git stash list
Pattern not found  (press RETURN)

$ git config --get core.pager
diff-so-fancy | less --tabs=4 -RFX --pattern '^(Date|added|deleted|modified): '

$ git config --get pager.stash
```

Everything works fine if I remove the `--pattern` part for `stash`:

```
$ git config --get pager.stash
diff-so-fancy | less --tabs=4 -RFX

$ git stash list
stash@{0}: WIP on master: 4c9c673 Blah blah blah
```

(I'd prefer not to do this, because I like the `--pattern` thing for `git stash show` calls, but it seems to be the compromise I need to make, unless I'm missing something?)

Anyone know a way to make this work? Otherwise, perhaps an update to the docs pointing this necessary compromise out?

Other info:

```
$ uname -a
Darwin shaman 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct 10 20:06:00 PDT 2018; root:xnu-3789.73.24~1/RELEASE_X86_64 x86_64

$ zsh --version
zsh 5.6.2 (x86_64-apple-darwin16.7.0)

$ git --version
git version 2.19.1

$ diff-so-fancy --version
Diff-so-fancy: https://github.com/so-fancy/diff-so-fancy
Version      : 1.2.0

$ less --version
less 530 (POSIX regular expressions)
```

**Comment by scottchiefbaker** [comment]
I'm not sure I totally follow here. `git stash list` is just a list of stashes, why would you use d-s-f to try and parse that? Perhaps a simple solution is just to expand the `pattern` to include `stash` to it will match something and not bail out early?

**Comment by gimbo** [comment]
> `git stash list` is just a list of stashes, why would you use d-s-f to try and parse that?

I agree completely: I don't want to - but my problem wasn't that I was trying to, my problem was that turning on d-s-f for my pager seemed to be breaking `git stash list`.

However, I realised that my problem was occurring because I wasn't following the instructions correctly anyway. Instead of doing this (as advised):

```
[pager]
    diff = diff-so-fancy | less --tabs=4 -RFX --pattern '^(Date|added|deleted|modified): '
```

I was doing this:

```
[core]
        pager = diff-so-fancy | less --tabs=4 -RFX --pattern '^(Date|added|deleted|modified): '
```

When I do it in the `[pager]` section as your docs suggest, everything seems to work fine. Apologies for confusion.

**Comment by scottchiefbaker** [comment]
Gotcha. Thanks for the clarification. If this is no longer an issue can you close it.
