### ISSUE TITLE
Support ignoring/truncating generated files

### ISSUE THREAD

**Issue by stephenh** [so-fancy/diff-so-fancy#317]
It's sometimes common to commit generated files (e.g. `yarn.lock` and `package-json.lock` are very common in JS), which clutter up diffs.

GitHub has handled this by showing a placeholder "this diff is generated code" for files that they detect as generated (via a `.gitattributes` file having a `linguist-generated` marker it).

It'd be great if `diff-so-fancy` mirror'd GitHub's behavior, ideally by auto-detecting `.gitattributes` in the repository's root directory (just given that is precedence/what people are already configuring).

**Comment by scottchiefbaker** [comment]
Can you elaborate on where/how one would read that attribute? Perhaps point met at a repo/commit that exhibits that behavior?

**Comment by stephenh** [comment]
Yep:

https://help.github.com/articles/customizing-how-changed-files-appear-on-github/

https://github.com/facebook/react/commit/fd4527dbcdab359b02dbce4752995e05502dc7b0

**Comment by scottchiefbaker** [comment]
If we were to do this it would require us to be able to read the `.gitattributes` from the root directory of the repo? This information isn't displayed anywhere as part of the diff output?

`diff-so-fancy` isn't aware of git or the repo at all, (we only parse the incoming diff output from `git`) so this might be pretty difficult.

**Comment by stephenh** [comment]
I had a bunch typed up about hacky options/hints in `git config` or what not, but turns out there is git plumbing already:

```
$ git check-attr linguist-generated yarn.lock 
yarn.lock: linguist-generated: true

$ git check-attr linguist-generated package.json 
package.json: linguist-generated: unspecified
```

So `git check-attr` will handle the `.gitattributes` detection + glob matching.

`diff-so-fancy` would still have to invoke `check-attr` for each path in the diff, and then also be aware of the GH-specific `linguist-generated` flag.

But perhaps that is okay? Or maybe if first enabled with a `diff-so-fancy.checkLinguistGenerated` flag?

**Comment by scottchiefbaker** [comment]
`diff-so-fancy` just reads the raw diff output generated by `git`. Unless this information is present somehow in the diff output, I don't think d-s-f will be able to act upon it. I like it in theory, but in practice I don't think we can do it.

**Comment by stephenh** [comment]
Cool, that makes sense. I guessing stepping further back, it would be ideal if `git diff` itself had this linguist-generated (or similar) hint awareness; if the itch gets big enough, I'll bring it up over in git proper. :-)

**Comment by stephenh** [comment]
FWIW, as an FYI + if anyone comes across this later, it turns out `git diff` can already do this with an existing `.gitattributes` hint:

https://stackoverflow.com/questions/31100061/make-git-to-track-auto-generated-files-but-ignore-from-diff/32511147#32511147

"Just create a file doc/.gitattributes which contains * -diff, and then everything under that path will be treated as binary for diffs."

Granted, it's cheating a little bit, because generated code is likely not really binary, but it achieves the high-level purpose of truncating it in diffs.
