### ISSUE TITLE
Can't locate DiffHighlight.pm in @INC

### ISSUE THREAD

**Issue by JanisE** [so-fancy/diff-so-fancy#318]
Just copied `diff-so-fancy` into `/usr/local/bin/` and I'm getting this error:

```
$ diff-so-fancy 
Can't locate DiffHighlight.pm in @INC (you may need to install the DiffHighlight module) (@INC contains: /usr/local/bin/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/diff-so-fancy line 13.
BEGIN failed--compilation aborted at /usr/local/bin/diff-so-fancy line 13.
```

OS: Linux Mint 19 (based on Ubuntu 18.04).

```
$ locate DiffHighlight
/usr/share/doc/git/contrib/diff-highlight/DiffHighlight.pm
```

**Comment by scottchiefbaker** [comment]
Did you copy the [fatpacked version](https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy) that includes `DiffHighlight`? If  you just copied d-s-f from the root of this repo you'll need to also copy the `lib/` directory.

**Comment by JanisE** [comment]
Thank you, the fatpacked version worked.

**Comment by ericfrederich** [comment]
Can we please re-open this issue as the "[fatpacked version](https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy)" no longer exists?

I'm on a new WSL2 install of Ubuntu 24.04

**Comment by ericfrederich** [comment]
... seems to have been removed here: 29a0346c01d7b45548f085f985739076150686d5

**Comment by scottchiefbaker** [comment]
I don't check the fatpacked version into the repo anymore as it was just one MORE thing to maintain. Instead the current released version is available as part of the releases: https://github.com/so-fancy/diff-so-fancy/releases/tag/v1.4.4

You're also welcome to build your own fatpacked version using the script in the directory.

**Comment by apodkutin** [comment]
Another solution will be to create `lib` relative to the core script and put https://github.com/so-fancy/diff-so-fancy/blob/next/lib/DiffHighlight.pm file there.
Works fine in WSL2 Ubuntu 20.04
