### ISSUE TITLE
New additions are in grey colour

### ISSUE THREAD

**Issue by karolisgrinkevicius** [so-fancy/diff-so-fancy#319]
Hi, I have `diff-so-fancy@1.2.0` installed and  the following global git configuration for colours: 

```
[color "diff-highlight"]
	oldNormal = red bold
	oldHighlight = red bold 52
	newNormal = green bold
	newHighlight = green bold 22
[color "diff"]
	meta = yellow
	frag = magenta bold
	commit = yellow bold
	old = red bold
	new = green bold
	whitespace = red reverse
[diff-so-fancy]
  stripLeadingSymbols = false
```

The newly added lines show up in grey colour which should be green. Is this a bug or misconfigured git?

Actual output of `git diff` using configuration provided above.

![screenshot 2018-12-03 at 11 51 27](https://user-images.githubusercontent.com/9420403/49366367-da9be080-f6f1-11e8-8edf-0f5fa096e98a.png)

**Comment by scottchiefbaker** [comment]
That config looks good to me. Even the "yellow" for the filename seems muted. I suspect this may be a terminal issue? Have you tried another terminal to see if it changes anything?

**Comment by karolisgrinkevicius** [comment]
@scottchiefbaker thanks for your reply. I'm using `iTerm2 Build 3.2.6` with the following colour profile:
<img width="584" alt="screenshot 2018-12-03 at 22 14 51" src="https://user-images.githubusercontent.com/9420403/49399098-0302f980-f749-11e8-8264-7e71881c4a3a.png">

**Comment by karolisgrinkevicius** [comment]
I solved this by changing ANSI colour configuration in iTerm2 profile. Thanks.

**Comment by scottchiefbaker** [comment]
Interesting. Thanks for the tip.

**Comment by stevemao** [comment]
We had similar issue opened before. Maybe it's worth to add tips on ANSI colour configuration in terminal profile.

**Comment by karolisgrinkevicius** [comment]
@sco

> That config looks good to me. Even the "yellow" for the filename seems muted. I suspect this may be a terminal issue? Have you tried another terminal to see if it changes anything?

BTW @scottchiefbaker where do you see muted yellow in my posted screenshot? Thanks.

**Comment by scottchiefbaker** [comment]
The first screenshot has a mustard yellow color for the filename. The config you posted should be a brighter yellow. But it's because of your ANSI profile.
