### ISSUE TITLE
stripLeadingSymbols not respected when using 256-color background and foreground

### ISSUE THREAD

**Issue by isaacs** [so-fancy/diff-so-fancy#325]
My diff config:

```ini
[color "diff"]
  meta = yellow
  frag = magenta bold
  commit = yellow bold
  whitespace = red reverse
  old = 255 52
  new = 255 22
[color "diff-highlight"]
  oldHighlight = 52 218
  oldNormal = 255 52
  newNormal = 255 22
  newHighlight = 22 194
[diff-so-fancy]
  markEmptyLines = false
  stripLeadingSymbols = true
```

The resulting output:
![screenshot 2019-02-14 17 44 25](https://user-images.githubusercontent.com/9287/52829073-3551a100-3080-11e9-9366-6998413e2718.png)

Note the `+` and `-` signs on the lines that have a background.

EDIT: it looks this this is already fixed in master, just not published to npm.

**Comment by scottchiefbaker** [comment]
I came to check the code, because we definitely fixed 256 color ANSI sequences. I don't push to NPM, so I can't speak for how up-to-date that is. I don't know anything about NPM, is there a way to see who pushed the last one and ping them to update it?

**Comment by isaacs** [comment]
Yeah, I’ll dig into it. Thanks for fixing it, sorry for the false alarm :)

**Comment by isaacs** [comment]
Reached out to the npm package maintainers.

**Comment by scottchiefbaker** [comment]
Who are the maintainers? Can you have them contact us here so we can work on more timely NPM updates in the future?

**Comment by isaacs** [comment]
@paulirish @stevemao

**Comment by paulirish** [comment]
diff-so-fancy@1.2.5 published to NPM! :)

**Comment by scottchiefbaker** [comment]
@paulirish do you normally handle the pushes to NPM?

**Comment by paulirish** [comment]
@scottchiefbaker Steve usually watches out for release cuts and ships them but I can take over. 

(Or you can...) It's just a matter of bumping the version in package.json and doing `npm publish`. If you get an npm acct i'll add you to the package.

**Comment by stevemao** [comment]
Sorry about this, but feel free to ping me if you want to make a release.
