### ISSUE TITLE
Docs: Emphasize that diff-so-fancy is usable as a general diff tool

### ISSUE THREAD

**Issue by petdance** [so-fancy/diff-so-fancy#328]
I still use Subversion a lot and diff-so-fancy is great as a tool for Subversion diffs, too.  Heck, any diffs.  Currently, it sounds like it's a git-only tool.

**Comment by unphased** [comment]
Could you elaborate, how could I use it to compare two plain files, for example? It's not obvious.

**Comment by petdance** [comment]
Take the output from `diff -u` and pipe it into `diff-so-fancy`.

    diff -u old.txt new.txt | diff-so-fancy

`diff-so-fancy` isn't doing any diffing.  It's just taking the diff output and making it prettier.

**Comment by unphased** [comment]
Oh, right. Keep forgetting that diff needs `-u` to do the "standard" thing. Thanks.

**Comment by scottchiefbaker** [comment]
This should be addressed in b18ec0273e712e63116dbc983c9e7270f4155f41 which just landed.
