### ISSUE TITLE
Unable to detect the minimal changed words

### ISSUE THREAD

**Issue by yegle** [so-fancy/diff-so-fancy#329]
See the screenshot for example.
![image](https://user-images.githubusercontent.com/146133/56478791-9c1b7e00-6466-11e9-86c5-d29a0b561e72.png)

In this diff, I changed the first URL and added some additional text. `diff-so-fancy` treated the whole text in the middle as diff.

`git diff --word-diff=color` is slightly better:
![image](https://user-images.githubusercontent.com/146133/56478854-e8ff5480-6466-11e9-87f4-395cd24f3c8e.png) but still don't treat the additional text as added text.

**Comment by yegle** [comment]
It looks like the output of `diff-so-fancy` is very similar to `diff-highlight` from git, are they related?

**Comment by scottchiefbaker** [comment]
`diff-so-fancy` uses `diff-highlight` for it's syntax based highlighting.

**Comment by scottchiefbaker** [comment]
This is a `CANTFIX` because of the way we use `diff-highlight`. Unless we switch diffing engines this is the desired output.
