### ISSUE TITLE
New lines aren't colored with stripLeadingSymbols=false

### ISSUE THREAD

**Issue by jkugelman** [so-fancy/diff-so-fancy#334]
With the default configuration where stripLeadingSymbols=true new lines are colored green. If I set it to false, new lines have no color at all.

Here is a simple `diff.txt` that shows the problem:

```bash
$ cat diff.txt
diff --git a/file.txt b/file.txt
--- a/file.txt
+++ b/file.txt
@@ -0,0 +1 @@
+new line
```

Notice that the last line (`+new line`) has no color codes:

```bash
$ git config --global diff-so-fancy.stripLeadingSymbols false
$ <diff.txt diff-so-fancy | cat -v
^[[0m^[[38;5;11m----------
^[[38;5;11mmodified: file.txt$
^[[38;5;11m----------
@ file.txt:1 @^[[1m^[[38;5;146m^[[0m
+new line
```

However if I reset it to the default true, the last line is indeed colored:

```bash
$ git config --global diff-so-fancy.stripLeadingSymbols true
$ <diff.txt diff-so-fancy | cat -v
^[[0m^[[38;5;11m----------
^[[38;5;11mmodified: file.txt
^[[38;5;11m----------
@ file.txt:1 @^[[1m^[[38;5;146m^[[0m
^[[1m^[[38;5;2mnew line
^[[0m
```

---

Note that *modified* lines are fine. It's only brand new lines that have no color. If I add `-old line` to the diff then everything's fine:

```bash
$ cat diff.txt
diff --git a/file.txt b/file.txt
--- a/file.txt
+++ b/file.txt
@@ -0,0 +1 @@
-old line
+new line
$ git config --global diff-so-fancy.stripLeadingSymbols false
$ <diff.txt diff-so-fancy | cat -v
^[[0m^[[38;5;11m----------
^[[38;5;11mmodified: file.txt
^[[38;5;11m----------
@ file.txt:1 @^[[1m^[[38;5;146m^[[0m
^[[1;31m-^[[m^[[1;31;48;5;52mold^[[m^[[1;31m line^[[m
^[[1;32m+^[[m^[[1;32;48;5;22mnew^[[m^[[1;32m line^[[m
```

---

Tested with https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy downloaded on 2019-06-12, sha1 hash e95bffe83ab8642643bcc77b5af1d5a6878d1a9b.

**Comment by scottchiefbaker** [comment]
What OS, Git, and Perl versions are we dealing with here?

**Comment by jkugelman** [comment]
It's Ubuntu 18.04 LTS with git and perl installed via apt-get.

```bash
$ lsb_release -ds
Ubuntu 18.04.2 LTS
$ apt show git
Version: 1:2.17.1-1ubuntu0.4
$ git --version
git version 2.17.1
$ apt show perl
Version: 5.26.1-6ubuntu0.3
$ perl --version
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
(with 67 registered patches, see perl -V for more detail)
```

**Comment by scottchiefbaker** [comment]
Maybe I'm not following 100%. Here is how I recreated this:

```
mkdir foo
cd foo
git init
touch index.txt
git add .
git commit -m "test"

echo "test line" >> index.txt
git diff
````

Both with and without stripping the leading symbols I get color:

![foo](https://user-images.githubusercontent.com/3429760/59390357-dd713100-8d25-11e9-8654-70406b7bee36.png)

**Comment by jkugelman** [comment]
No color for me.

```bash
[~]$ mkdir foo
[~]$ cd foo
[~/foo]$ git init
Initialized empty Git repository in /home/jkugelman/foo/.git/
[~/foo (HEAD)]$ touch index.txt
[~/foo (HEAD)]$ git add .
[~/foo (HEAD)]$ git commit -m "test"
[master (root-commit) 4977e8b] test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 index.txt
[~/foo (master)]$ echo "test line" >> index.txt
[~/foo (master)]$ git config --global diff-so-fancy.stripLeadingSymbols false
[~/foo (master)]$ git diff | diff-so-fancy | cat -A
^[[0m^[[38;5;11m----------$
^[[38;5;11mmodified: index.txt$
^[[38;5;11m----------$
@ index.txt:1 @^[[1m^[[38;5;146m^[[0m$
+test line$
```

**Comment by scottchiefbaker** [comment]
What terminal are you using?

**Comment by jkugelman** [comment]
[Terminator](https://gnometerminator.blogspot.com/p/introduction.html) 1.91-1. `$TERM` is set to `xterm-256color`.

**Comment by scottchiefbaker** [comment]
Are you able to try some other terminals? I'm curious if it's a terminal emulation thing.

**Comment by jkugelman** [comment]
* Same problem with gnome-terminal (`TERM=xterm-256color`).
* Same problem with xterm (`TERM=xterm`).

**Comment by jkugelman** [comment]
Looking at the script, the `if ($manually_color_lines)` block inside of `sub strip_leading_indicators` is where color should be added to `+test line`.

```perl
    if ($manually_color_lines) {
        if (defined($5) && $5 eq "+") {
            my $add_line_color = get_config_color("add_line");
            $line              = $add_line_color . $line . $reset_color;
        } elsif (defined($5) && $5 eq "-") {
            my $remove_line_color = get_config_color("remove_line");
            $line                 = $remove_line_color . $line . $reset_color;
        }
    }
```

When I disable `$strip_leading_indicators` then `sub strip_leading_indicators` is never called, and so color codes aren't added.

**Comment by scottchiefbaker** [comment]
I'm unable to recreate this... are you able to test with a vanilla git config? I wonder if something else is conflicting?

**Comment by scottchiefbaker** [comment]
Per your previous comment about `strip_leading_indicators()` not being called. That's OK, because the ANSI color sequence is already there from the diff as it comes from `git`. We add the color in that function because stripping the leading indicator also strips the color.

**Comment by jkugelman** [comment]
Ah, I've been testing with diff-so-fancy called manually on the command-line rather than having it configured as my git pager. I also have this in `~/.gitconfig`:

```
[color]
        status = auto
        branch = auto
        ui = auto
        interactive = auto
```

This means that `git <whatever> | diff-so-fancy` causes git to disable color codes since its output is to a pipe not a tty. (See my original example up top where I wanted to color a diff I'd saved as `diff.txt`.)

**Comment by scottchiefbaker** [comment]
That would explain it. d-s-f tries to preserve the ANSI codes from `git diff` to use the original colors. If you're stripping the color out **before** it gets to d-s-f it would make sense it's coming out the other side non-colored.

**Comment by cstrahan** [comment]
@jkugelman I talk about enforcing color on a case-by-case basis (and also setting up an alias) here: https://github.com/so-fancy/diff-so-fancy/pull/339#issuecomment-506997057

Such an alias (and the tip about `git -c color.ui=always diff`) might be worth a suggestion in the readme (and might help drive home the fact that d-s-f expects ANSI color codes coming from `git` in order for the end result to look as expected).

**Comment by scottchiefbaker** [comment]
@jkugelman where did we leave this? Sounds like it's not a d-s-f bug, but more of a git configuration issue?

**Comment by jkugelman** [comment]
I didn't realize that d-s-f is only intended to be used interactively with `git diff`. I thought it could also be used to color plain diff/patch files on disk without involving git. I don't know if that's something you want to add support for? If not, I won't object to closing this issue as "works as intended".

**Comment by scottchiefbaker** [comment]
@jkugelman we did add support for standalone diffs in the last version. It's a new feature but it should work 98% of the time. To be consistent d-s-f has to be called in the same fashion:

    git diff | diff-so-fancy
    cat diff.txt | diff-so-fancy

etc... If you call it in this manner does your example work?

**Comment by scottchiefbaker** [comment]
I just landed one minor tweak to the standalone (non-git) tree to properly colorize the fragment. The code was working before, the coloring was just off. This is using the example you provided:

![snippet](https://user-images.githubusercontent.com/3429760/61905871-fcdfaa00-aede-11e9-89ee-58ea5788f48b.png)

**Comment by jkugelman** [comment]
Looks good!
