### ISSUE TITLE
Mistakes line starting with "-" as removed (with `log --graph`)

### ISSUE THREAD

**Issue by blueyed** [so-fancy/diff-so-fancy#336]
Using the following git config:
```ini
[pager]
	log = diff-so-fancy
```

With `git log -1 .travis`, I see:

```
| diff --git a/.travis.yml b/.travis.yml
| index b5abc0b..6952a25 100644
| --- a/.travis.yml
| +++ b/.travis.yml
| @@ -11,6 +11,7 @@ addons:
|  env:
|    global:
|      - LUAROCKS=2.3.0
| +    - LUAROCKS=3.1.3
|    matrix:
|      - WITH_LUA_ENGINE=Lua LUA=lua5.3
|      - WITH_LUA_ENGINE=LuaJIT LUA=luajit2.1
|
```

But the line before the added one gets highlighted as removed - apparently mistaking the `-` there:

![2019-06-23-211012_657x767_escrotum](https://user-images.githubusercontent.com/9766/59980831-57919780-95fb-11e9-85f1-673a2b719b63.png)

Version      : 1.2.5  (next branch, 20b70f16fc697b0711c8e6b8af94368d6f9365af)

**Comment by scottchiefbaker** [comment]
My first guess is that perhaps this is a `git` bug and not a d-s-f bug? Usually d-s-f doesn't muck around with colors and line changes like this as it just passes through what `git` sends us but in a cleaned up fashion.

What does the raw diff look like?

**Comment by blueyed** [comment]
It is caused by using `--graph`.

1. git clone https://github.com/blueyed/luv.git
2. cd luv
3. git clone https://github.com/blueyed/luv.git

It works with (i.e. upstream):
```ini
[pager]
	log = /usr/share/git/diff-highlight/diff-highlight | $(git config core.pager)
[core]
	pager = less -S --no-init --quit-if-one-screen
```

**Comment by blueyed** [comment]
Duplicate of https://github.com/so-fancy/diff-so-fancy/issues/199 then I guess..
