### ISSUE TITLE
Travis tests are failing on OS X

### ISSUE THREAD

**Issue by scottchiefbaker** [so-fancy/diff-so-fancy#337]
Builds have been failing on OS X for a while now and I have no idea why.

@BernhardWebstudio any way I can get you to take another look at our Travis config again?

**Comment by BernhardWebstudio** [comment]
Well, on _master_ they are because there it is still the old `.travis.yml`. On _next_, the main issue seems to be the error message `Your Homebrew is outdated. Please run _brew update_.`, which prevents perl, cpanminus etc. from being installed. I will submit a PR shortly...

**Comment by scottchiefbaker** [comment]
Fixed after merge!
