### ISSUE TITLE
diff-so-fancy: not found

### ISSUE THREAD

**Issue by xss** [so-fancy/diff-so-fancy#343]
I just installed diff-so-fancy. It is in `$PATH` (I put it in `~/.local/bin`; it doesn't matter whether I put the [install pack](https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy) there directly or if it is merely symlinked from there).

As long as pager is not set (or circumventing it), running `git diff | diff-so-fancy` works fine.

However, once the pager property was added and it should be used for any diff output, I always get the following error, and no diff whatsoever:

    $ git diff
    diff-so-fancy | less --tabs=4 -RFX: 1: diff-so-fancy | less --tabs=4 -RFX: diff-so-fancy: not found

This is also the output for the [bug-reporting query](https://github.com/so-fancy/diff-so-fancy/blob/master/reporting-bugs.md).

Instead of the fatpacked script, I also tried with a cloned repo and symlinking to the `diff-so-fancy` file from `$PATH`. With identical results.

Is there something wrong with d-s-f? Or am I missing some obscure dependency or have another collision I am not aware of? The documentation or search engines didn't yield anything helpful, beside the obvious hint to have d-s-f available in `$PATH`.

**Comment by scottchiefbaker** [comment]
Can you provide version information: OS, Bash, Perl?

Does it work if you put the full path in your git alias?

**Comment by xss** [comment]
Hi @scottchiefbaker, thank you for looking into this!

> Can you provide version information: OS, Bash, Perl?

OS: Ubuntu 18.04.3 LTS
Bash: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Perl: v5.26.1, built for x86_64-linux-gnu-thread-multi
Kernel, in case that matters: 5.0.0-26-generic

> Does it work if you put the full path in your git alias?

Good point! This does, indeed, work (from ~/.gitconfig):

    [core]
            pager = ~/repos/diff-so-fancy.packed | less --tabs=4 -RFX

So, how could that be that git seems to not use/see the $PATH?

**Comment by xss** [comment]
So, upon investigating a bit more...

This works in `~/.gitconfig`:

    [core]
            pager = diff-so-fancy

Hence, the `$PATH` seems to be recognized in some cases, after all. But as soon as there's a `| less`after it, it stops working. In those same cases, also this commands fails with the identical error:

    git config --list

When issued on the command line directly, without the pager setting in `.gitconfig`, the corresponding `git-diff` command works:

    git diff HEAD..HEAD^ | diff-so-fancy | less --tabs=4 -RFX

My `less` looks normal:

    $ type less
    less is /usr/bin/less
    $ less --version
    less 487 (GNU regular expressions)

I can sure live with the full path in `~/.gitconfig`, but am still curious as to what's going on.

**Comment by scottchiefbaker** [comment]
This is super weird... does it work if you put the FULL path to `less` in your gitconfig?

**Comment by xss** [comment]
Nope. This results in the same error (of course, now including the full path `/usr/bin/less`).

**Comment by scottchiefbaker** [comment]
What about calling d-s-f directly?

    cat foo.txt | diff-so-fancy

or

    cat foo.txt | diff-so-fancy | less --tabs=4 -RFX

**Comment by xss** [comment]
Both work as expected, the latter making the cat output scrollable as expected. When `cat`-ing a diff/patch file, the output is formatted beautifully.

**Comment by scottchiefbaker** [comment]
What if you change your git pager to **just** `less` (no d-s-f). Do you get the same error?

**Comment by xss** [comment]
I think I tried that, as well, and it worked as expected (after all, it is `git`'s default behavior, isn't it?). I will re-check tomorrow once I'm back at my computer.

**Comment by scottchiefbaker** [comment]
Hate to say it, but this sounds like either a git or a bash bug in your environment. D-s-f is doing the right thing, it's just not getting called the way we're used to.

**Comment by scottchiefbaker** [comment]
Ooops I clicked the wrong button. Didn't mean to close this. Let me know what you think the next step is.

**Comment by xss** [comment]
For now, I am low on ideas. I just installed d-s-f on another machine (home PC) without any issues. So yes, it seems to be something on the original computer (work PC).

A relevant key difference might be that this home PC is pretty much a "git virgin" – the `git config --global` command for setting up d-s-f created `~/.gitconfig` in the first place. On contrast, the "problematic" work PC's gitconfig has been groomed and ported over several machines and installations for years. So, yes, there's probably something interfering there.

I will investigate the git and bash environment on the work PC more next week, and report possible findings here. Thank you very much for taking the time to look into this, Scott! :)

**Comment by scottchiefbaker** [comment]
Let me know your findings, I'm curious now!

**Comment by xss** [comment]
Hi,

after a lot more testing and trial-and-error I finally found a relevant source of the issue, I think. It seems to depend on _how_ the $PATH is concatenated.

I had the following in my `~/.bashrc`[¹]:

    PATH="$PATH:~/.local/bin"

This resulted in the relevant $PATH part:

    $ echo $PATH
    <many-more-paths-here>:~/.local/bin

This notation, `~/.local/bin`, seems to cause `git` not to be able to resolve the path properly and act funny, so pager settings can't find the commands in that path – but only as soon as there is _more than one word_[²] in the pager setting!

Changing the $PATH in `.bashrc` to either of the following ...

    PATH=$PATH:~/.local/bin        # the same but without the quotes
    PATH="$PATH:$HOME/.local/bin"  # var $HOME instead of generic ~ as home path

... will cause a minor change in $PATH:

    $ echo $PATH
    <many-more-paths-here>:/home/<username>/.local/bin

This fixes the issue, and the diff-so-fancy/less combo – or any other pager command group – works as expected, for all commands available in $PATH.

So, in the end, a $PATH containing `~/<some-dir>` is not at all wrong and works perfectly for bash and scripts, but causes problems for `.gitconfig`.

I hope this helps someone else with a similar issue. :)

Regards
xss

----

[¹] (There's practically no difference on my machine between `.profile`, `.bash_profile` or `.bashrc`, they all source the same files in the end.)

[²] As illustrated before, with my old $PATH setting, this worked:

    [core]
            pager = diff-so-fancy

... but this did not:

    [core]
        pager = diff-so-fancy | less

I could reproduce this behavior for pretty much any command available in my `.local/bin/` (both symlinked and binary/script), not only d-s-f. The commands alone were called fine. As soon as there was whatever behind the command, it failed.

**Comment by hazkaz** [comment]
I too had this issue in debian, although I was not able to reproduce everything @xss said. In my case symlinking `diff-so-pretty` to `/usr/local/bin` using 

`ln -s $HOME/.npm-global/bin/diff-so-pretty /usr/local/bin` 

solved the issue
