### ISSUE TITLE
Latest release reports wrong version

### ISSUE THREAD

**Issue by rlue** [so-fancy/diff-so-fancy#346]
```sh
$ curl -L https://github.com/so-fancy/diff-so-fancy/archive/v1.2.7.tar.gz | tar xzf -
$ head -n3 diff-so-fancy-1.2.7/diff-so-fancy
#!/usr/bin/env perl

my $VERSION = "1.2.6";
```

**Comment by scottchiefbaker** [comment]
That command pulls the `next` branch, which is currently staged for 1.2.7. That version is not released yet and is still considered "beta".

    https://github.com/so-fancy/diff-so-fancy/archive/master.zip

Is the current official release, and is version 1.2.6

**Comment by scottchiefbaker** [comment]
There was a minor miscommunication on our side on this. A git tag was created for 1.2.7 but it was slightly premature. For the time being 1.2.6 is the official release, and 1.2.7 is beta on the `next` branch.

We'll probably just skip to 1.2.8 for the next release to avoid this confusion in the future.

Thanks for the heads up.
