### ISSUE TITLE
Can't work: perl script error

### ISSUE THREAD

**Issue by foisonocean** [so-fancy/diff-so-fancy#347]
![image](https://user-images.githubusercontent.com/15059605/64892269-92f5ac80-d6a6-11e9-8943-da7642ccd7cc.png)

**Comment by scottchiefbaker** [comment]
What OS and platform?

`tput` is needed to determine the width of your terminal.

**Comment by foisonocean** [comment]
@scottchiefbaker My problem solved after installing `tput`, thanks man
