### ISSUE TITLE
unknown terminal "tmux-256color"

### ISSUE THREAD

**Issue by mastertinner** [so-fancy/diff-so-fancy#348]
I'm running `diff-so-fancy` in a `tmux` session with `set -g default-terminal "tmux-256color"`. That leads to 

```shell
$ git diff
WARNING: terminal is not fully functional
-  (press RETURN)tput: unknown terminal "tmux-256color"
Argument "" isn't numeric in repeat (x) at /usr/local/bin/diff-so-fancy line 578, <STDIN> line 26.
```

Is `tmux-256color` a terminal that should be supported?

If I use `screen-256color` instead, everything works as expected.

**Comment by scottchiefbaker** [comment]
d-s-f shells out to `tput` to determine the width of your terminal. This is a tput error, not a d-s-f error.

Does the command `tput cols` work for you in a standalone shell?

**Comment by mastertinner** [comment]
You are right.

When I use `tmux-256colors`, the output of `tput cols` is `tput: unknown terminal "tmux-256color"`.

When I use `screen-256colors`, the output of `tput cols` is `239`.

I'll close this issue then. Thanks for the help!
