### ISSUE TITLE
diff-so-fancy broken after Catalina upgrade

### ISSUE THREAD

**Issue by amit1rrr** [so-fancy/diff-so-fancy#353]
I recently upgraded to Catalina which broke my diff-so-fancy installation.

Here's the error I see when I press git diff -

```
tput: unknown terminal "xterm-256color"
Argument "" isn't numeric in repeat (x) at /usr/local/bin/diff-so-fancy line 578, <STDIN> line 13.
```

Here's the relevant code around line 578 - 

```
558 # Print a line of em-dash or line-drawing chars the full width of the screen
559 sub horizontal_rule {
560     my $color = $_[0] || "";
561     my $width = $ruler_width || `tput cols`;
562 
563     if (is_windows()) {
564         $width--;
565     }
566 
567     # em-dash http://www.fileformat.info/info/unicode/char/2014/index.htm
568     #my $dash = "\x{2014}";
569     # BOX DRAWINGS LIGHT HORIZONTAL http://www.fileformat.info/info/unicode/char/2500/index.htm
570     my $dash;
571     if ($use_unicode_dash_for_ruler && should_print_unicode()) {
572         $dash = Encode::encode('UTF-8', "\x{2500}");
573     } else {
574         $dash = "-";
575     }
576 
577     # Draw the line
578     my $ret = $color . ($dash x $width) . "\n";
```

Very likely, $color is empty because horizontal_rule is not getting proper input. I tried quite a few things but nothing seems to work. Any ideas?

**Comment by scottchiefbaker** [comment]
Is Catalina an OSX thing? I'm not familiar with that term.

The issue you're seeing here is that we shell out to tput to get the terminal width. For some reason your terminal is not supported by `tput` and when it tries to draw the horizontal rule it doesn't know how wide to make it.

This is not a d-s-f bug as much as a terminal/tput bug. See if you can figure out why `tput cols` doesn't work on your terminal and then d-s-f will work.

**Comment by scottchiefbaker** [comment]
Alternately you should be able to force the [ruler width](https://github.com/so-fancy/diff-so-fancy#rulerwidth).
