### ISSUE TITLE
Problem w/ usage

### ISSUE THREAD

**Issue by scy86dev** [so-fancy/diff-so-fancy#354]
Your readme doesn't indicate basic usage from what I can see. When I try to do a diff such as...  
`diff-so-fancy file1 file2`
... it replies with the following...  
```
[~/sandbox] > diff-so-fancy file1.txt file2.txt 
Diff-so-fancy: https://github.com/so-fancy/diff-so-fancy
Version      : 1.2.6

Usage:

git diff --color | diff-so-fancy # Use d-s-f on one diff
diff-so-fancy --colors           # View the commands to set the recommended colors
diff-so-fancy --set-defaults     # Configure git-diff to use diff-so-fancy and suggested colors

# Configure git to use d-s-f for *all* diff operations
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
```

What am I doing wrong here? I have already executed `git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"` and have already setup the recommended colors via your readme instructions.

**Comment by scottchiefbaker** [comment]
`diff-so-fancy` expect all data to be passed in via `STDIN`. If you want to use it outside of `git` it needs to be in the format of

```
diff -u file1 file2 | diff-so-fancy
cat foo.diff | diff-so-fancy
```

**Comment by alichtman** [comment]
> `diff -u file1 file2 | diff-so-fancy`

This doesn't work for me on macOS. All version information attached in a screenshot. The command exits successfully but doesn't show any output.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/20600565/68404769-54004680-017f-11ea-814d-9e2aa356843e.png">

**Comment by alichtman** [comment]
You can put this in your `.zshrc` to make `diff-so-fancy` instead of `diff`:

```bash
function pdiff () {
	diff -u $1 $2 | diff-so-fancy
}
```

**Comment by scottchiefbaker** [comment]
This should be addressed in the last commit I just landed.
