### ISSUE TITLE
Automating release of ".deb" package

### ISSUE THREAD

**Issue by aos** [so-fancy/diff-so-fancy#357]
Hey y'all. First off, thank you for this.

Now, I've been working on building a `.deb` package of `diff-so-fancy`. The reason for this is I would like to have it automatically install using Ansible (or chef, puppet, etc.) on my boxes. I got one working and all you'd have to do is download the package and run:
```
$ sudo apt-get install ./<diff-so-fancy-package-name-with-version>.deb
```
and it will install `diff-so-fancy`.

I would like this automated though so that on each release, we can generate the `.deb` package and have it listed in the `assets`. These should work on Debian, Ubuntu, and really any linux distro that can use in `.deb` packages. So... I have a few questions for you:

1. What is your release process like? Looking at the repo, I don't see anything specific so I'm assuming the release process is done by hand? As in, you manually tag your releases?
2. If it is automated somehow, I'm happy to send a PR that will automate deb package creation for every release.
3. If not automated, I was thinking of making a simple service that polls this repo for a new release every X days, grab the latest release, package it and make it available on a PPA repository. Or, I can run a simple web server that hosts these packages. I would rather not go down this route obviously.

Let me know. Thanks.

**Comment by scottchiefbaker** [comment]
There is no automated release process. We do releases when the code warrants it. These days d-s-f is pretty mature so development has slowed down.

Thanks for offering to make a `.deb`. Do you have any clout to actually get it included in the debian repos?

**Comment by aos** [comment]
Sounds good. Thanks for answering. Give me a few weeks and I'll report back with an update.

**Comment by aos** [comment]
Hey y'all -- just to give a small update: a bunch of unexpected life stuff has come into the picture and I got super busy. I am picking this up again now!

**Comment by scottchiefbaker** [comment]
Thanks for looking in to this.

**Comment by aos** [comment]
Hey, so I've finally packaged it. For Ubuntu, it can be downloaded like this:

```
$ sudo add-apt-repository ppa:aos1/diff-so-fancy
$ sudo apt update
$ sudo apt install diff-so-fancy
```
If you'd like, I can send a PR to add these instructions to the README. It also comes with a manpage. :-)

For Debian, there was actually [already an ITP (intent-to-package) posted](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925288) but they decided it would be best to use the diff-highlight program that comes secretly packed with git. Unfortunately, I found out about this after I had made a Debian package for it.

Alternatively, I've created a repository that instructs you on how to create `.deb` for this [located here](https://github.com/aos/dsf-package). All you need to do is clone it, and follow the instructions under **Create Binary Package** and it will build a `.deb` that you can add to your release page. Let me know your thoughts! Thanks.

**Comment by olleolleolle** [comment]
@aos  Thank you so much for starting this!

An attempt was made:

```
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/aos1/diff-so-fancy/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I will now learn more about if I _could_ get that to install.

**Comment by aos** [comment]
Hey @olleolleolle -- are you running Xenial by any chance? I believe I tagged the package as Bionic and up (because that's what I'm using). I've gone ahead and published it for Xenial as well. Try giving it another shot.

**Comment by olleolleolle** [comment]
@aos Thanks so much for the hint, and for the republishing.

This made it install cleanly for me! ✨

**Comment by scottchiefbaker** [comment]
Is this completed? Can I mark is as closed?

**Comment by olleolleolle** [comment]
https://github.com/aos/dsf-package This repository has the automation tools, and I have been able to use a release produced by those tools. They need to be _run_ by an enthusiast on release I guess – is that right @aos?

**Comment by aos** [comment]
That's right @olleolleolle. The repository is there in case anyone else wants to create Debian/Ubuntu packages. I provided it in case the authors of d-s-f would like to also make `.deb` packages to be added when they cut new releases. :-)

I am maintaining the Ubuntu package that can be pulled down via the `ppa:aos1/diff-so-fancy` repository. The process is automated so that any new releases to d-s-f will also be pulled into the repository.

**Comment by scottchiefbaker** [comment]
Sounds like this is all wrapped up. I'm going to close this issue. 

Thanks for doing this.

**Comment by theAkito** [comment]
1. This should be in the README.md and not hidden behind 2 reference issues, so nobody can find it.
2. Never use PPAs on Debian. It has to be in the real repositories. PPAs are for Ubuntu and derivatives, only.

**Comment by aos** [comment]
@theAkito RE: your second point -- I generally agree with you, it could cause a lot of issues. However, in this case it's alright. The package doesn't pull in any additional dependencies (besides perl, but that's available on all Linux flavors) so it won't cause any harm. If it makes you feel any better, I could add a warning. :-)

The reason I included the Debian instructions is because this package won't be getting pulled into Debian main any time soon (or may be ever, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925288).

**Comment by theAkito** [comment]
@aos 

Thank you very much for the information. I guess, it technically is alright, though I personally would prefer to refrain from adding any PPA to my Debian, for best practice and avoidance of confusion reasons. Well, that is a minor issue anyway, so nevermind that, for now.



> The reason I included the Debian instructions is because this package won't be getting pulled into Debian main any time soon (or may be ever, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925288).

I've read through the conversation and from what I understand they were mainly talking about what is included as a "native" part of Git. However, this can still be included in the Debian repositories -- at least I do not see any message in the conversation, speaking against adding this piece of software, explicitly.

Another reason, why I think it should be no problem for this software to be included in the official repositories is for example the following experience with the inclusion of Debian packages into the Debian ecosystem: https://github.com/zyedidia/micro/issues/1#issuecomment-361368236

As you can see, as long as you can package it properly, there should be nothing blocking this package from being accepted into the official repositories. I also don't see why software should be rejected, as long as it works properly and is packaged correctly.

Packaging this should also be child's play, as `perl` is pretty much omnipresent in the Linux world.

**Comment by OJFord** [comment]
@theAkito This discussion probably belongs at aos/dsf-package.
