### ISSUE TITLE
How to uninstall`

### ISSUE THREAD

**Issue by hejkerooo** [so-fancy/diff-so-fancy#359]
`diff-so-fancy | less --tabs=4 -RFX: diff-so-fancy: command not found`

Whatever I want to do with git CLI is printing me this issue
How I can remove this package?

Edit:
nvm, `git config --global core.pager "" ` worked

**Comment by jcrengifoa** [comment]
Just in case somebody else needs this:
`git config --global core.pager 'less'`
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration
