### ISSUE TITLE
word-diff of markdown files with lists is mis-highlighted

### ISSUE THREAD

**Issue by benwaffle** [so-fancy/diff-so-fancy#362]
a:
```
- hey
- hello2
```

b:
```
- hey
- hello
```

Bad diff (the `hey` line isn't changed):
<img width="206" alt="Screen Shot 2020-02-05 at 1 17 50 PM" src="https://user-images.githubusercontent.com/1713819/73870370-fcbf5000-4819-11ea-928a-ffc76fdcb605.png">

**Comment by scottchiefbaker** [comment]
I do not get the same output you do:

![diff](https://user-images.githubusercontent.com/3429760/73883774-612ddf80-4819-11ea-8cc5-0d61dd1da21e.png)

Try getting the raw diff output (not through d-s-f) and see if it's correct. All d-s-f does it parse the git output.

**Comment by benwaffle** [comment]
the `git diff` output is correct

```
diff --git a/x/a b/y/a
index 2aafcc1..85a78b6 100644
--- a/x/a
+++ b/y/a
@@ -1,2 +1,2 @@
- hey
- [-hello2-]{+hello+}
```

**Comment by scottchiefbaker** [comment]
I am unable to recreate... what version of d-s-f are you using?

**Comment by benwaffle** [comment]
1.2.6

**Comment by benwaffle** [comment]
and git 2.24.1

**Comment by scottchiefbaker** [comment]
Wait... that `hey` line has a minus sign at the beginning. In diff syntax that means the line is removed.

Either the raw diff is wrong, or git is reporting it incorrectly. D-s-f is doing the right thing here.

**Comment by benwaffle** [comment]
yes, except this is a --word-diff so the first character is not a space for unchanged lines

**Comment by scottchiefbaker** [comment]
Diff-so-fancy is just a parsing tool for the raw `git diff` (or any diff -u) style of output. D-s-f has no way to know that this is a `--word-diff` (there is nothing in the diff output that indicates this) so there is no way for d-s-f to know that the first `-` is **not** a line removal.

My first reaction to this is that d-s-f is just **not** compatible with `--word-diff`. Really you don't need `--word-diff` as d-s-f already highlights word changes using `DiffHighlight`?

**Comment by scottchiefbaker** [comment]
Secondly I am unable to recreate. Here is my test-case:

```
mkdir x
mkdir y
echo -e "hey\nhello2" > x/a
echo -e "hey\nhello" > y/a
git diff --word-diff x y
```

This results in the image I posted in the second comment. When I check the diff on this test case it's different than yours:

```
diff --git a/x/a b/y/a
index e3339b3..03a60b5 100644
--- a/x/a
+++ b/y/a
@@ -1,2 +1,2 @@
hey
[-hello2-]{+hello+}
```

Perhaps `git diff` changed output formats in a newer version? I'm running git version 2.16.1

**Comment by scottchiefbaker** [comment]
I just tested with git 2.25.0 and I am still unable to recreate your diff output. I suspect you have some  setting in your config that's adding those `-`s to your diff output.

Try using a vanilla config and see if you get the same diff output.

**Comment by benwaffle** [comment]
My test case is this:
```
mkdir x
mkdir y
echo -e "- hey\n- hello2" > x/a
echo -e "- hey\n- hello" > y/a
git diff --word-diff x y
```

>My first reaction to this is that d-s-f is just not compatible with --word-diff. Really you don't need --word-diff as d-s-f already highlights word changes using DiffHighlight?

--word-diff is nicer because it has very compact diffs even for very long lines, so the line isn't printed twice

>so there is no way for d-s-f to know that the first - is not a line removal.

Makes sense, not sure what the solution is here, if any. Could you look for any of `[-`, `-]`, `{+`, `+}` in the output to see if it is a word-diff?

**Comment by scottchiefbaker** [comment]
For d-s-f to know if it was word diff output I'd have to pre-process **all** (which could be huge) of the output looking for `[-` and the like. Even if we found those character strings there is no guarantee that they're not just part of a regular diff.

The short version is that there is no easy way for d-s-f to know that it's a word diff.  To put it another way, d-s-f does not appear to be compatible with word diffs. Because d-s-f already does word highlighting I think we'll probably stick with things the way they are.

**Comment by OJFord** [comment]
Pass `--line-prefix=' '` to `git diff` as well; that way every line will be preceded by a space, and d-s-f won't interpret any source characters (like `-` in your example) as being unified diff indicators.

There will be a preserved space left at the end of all of the output (including diff header); if that bothers you, you could strip that with `sed` in your `git config`'s `pager.diff`.

**Comment by scottchiefbaker** [comment]
Unfortunately d-s-f can't support word diffs. That's why we use `DiffHighlight` which does most of that work already.
