### ISSUE TITLE
Newlines are not highlighted when piped from `colordiff`

### ISSUE THREAD

**Issue by benwoodward** [so-fancy/diff-so-fancy#363]
`colordiff` newlines:
```
^[[0;32m+^[[0;0m
^[[0;32m+^[[0;0m
^[[0;32m+^[[0;0m
^[[0;32m+^[[0;0m
^[[0;32m+^[[0;0m
```

`git diff --color=always` newlines:
```
^[[32m+^[[m
^[[32m+^[[m
^[[32m+^[[m
^[[32m+^[[m
^[[32m+^[[m
```

The reason I have this issue is because I'm using `filterdiff` to extract the diff for a specific hunk. `filterdiff` regenerates the diff content and the color information is removed. So I then pipe to `colordiff`, however, colordiff output contains extra `0;` non printable characters which is confusing `diff-so-fancy`. 

```
❯ g diff | filterdiff --lines=696 | cat -v
diff --git a/.config/nvim/init.vim b/.config/nvim/init.vim
index e8e4a5c..f5b1be4 100644
--- a/.config/nvim/init.vim
+++ b/.config/nvim/init.vim
@@ -696,6 +696,11 @@ function! g:FuckThatMatchParen ()
     endif
 endfunction

+
+
+
+
+
 augroup plugin_initialize
     autocmd!
```

```
❯ g diff | filterdiff --lines=696 | colordiff | cat -v
^[[1;36mdiff --git a/.config/nvim/init.vim b/.config/nvim/init.vim^[[0;0m
^[[0;0mindex e8e4a5c..f5b1be4 100644^[[0;0m
^[[0;31m--- a/.config/nvim/init.vim^[[0;0m
^[[0;32m+++ b/.config/nvim/init.vim^[[0;0m
^[[0;36m@@ -696,6 +696,11 @@ function! g:FuckThatMatchParen ()^[[0;0m
^[[0;0m     endif^[[0;0m
^[[0;0m endfunction^[[0;0m
^[[0;0m ^[[0;0m
^[[0;32m+^[[0;0m
^[[0;32m+^[[0;0m
^[[0;32m+^[[0;0m
^[[0;32m+^[[0;0m
^[[0;32m+^[[0;0m
^[[0;0m augroup plugin_initialize^[[0;0m
^[[0;0m     autocmd!^[[0;0m
```

Meaning that newlines aren't highlighted: 

<img width="562" alt="Screen Shot 2020-02-09 at 11 24 35 pm" src="https://user-images.githubusercontent.com/1472981/74100420-8dd45500-4b93-11ea-89e5-318df4605a1e.png">

My current workaround for this issue is to use sed: 

`g diff | filterdiff --lines=696 | colordiff | sed 's/0;//g' | diff-so-fancy`

![image](https://user-images.githubusercontent.com/1472981/74100432-ae9caa80-4b93-11ea-8007-884a2746ccf9.png)

**Comment by scottchiefbaker** [comment]
I don't know how much we can help... d-s-f is written to parse `git diff` output, and adding another mode for filter diff would get really complicated. I think you're sed solution is probably the best.
