### ISSUE TITLE
Rulers: 1 char too long, and not Unicode?

### ISSUE THREAD

**Issue by fniessen** [so-fancy/diff-so-fancy#364]
Dear,

First, thanks a lot for this wonderful package… which should be standard!

Second, I'm reporting weird output in my environment (MinTTY on Cygwin):
- The ruler is 1-char too long (coming back onto the next physical line)
- The ruler is not nice as yours: always the same, in both values of the parameter

![image](https://user-images.githubusercontent.com/1748469/74652237-e1dbcc80-5185-11ea-8616-f8fe2307983d.png)

Any idea and/or help?

Best regards!

**Comment by OJFord** [comment]
`tput cols` is used to determine the width, presumably that's mis-reporting. Is it correct at different widths? In a different term?

An unbroken unicode line is just a matter of font (and term) support, I assume it's your font that's the issue, as it's clearly patched with powerline symbols, and they display fine.

**Comment by fniessen** [comment]
Dear @OJFord , funny: `tput cols` gives me 1 char LESS than the real size…

![image](https://user-images.githubusercontent.com/1748469/74682296-f049d880-51c5-11ea-92bb-5927c7647ac1.png)

Regarding the font, indeed, the one I used has quite a good coverage, maybe not that full, still, then?  It's "Powerline Consolas".

Any idea what to do to improve the look & feel. Note that I'm already very pleased with what I get. The diffs are subtle, but that's in those details we see we have a good environment...

**Comment by scottchiefbaker** [comment]
@fniessen did we ever figure out what's up with this? d-s-f just uses `tput cols` to calculate how large to draw that line.

**Comment by fniessen** [comment]
Dear @scottchiefbaker , unfortunately, no, I don't understand the problem - and I still have it.

I can only see that all the diff lines are beginning with 2 blank chars; for exemple:

    f.niessen@XIPHIAS:~/.dotfiles/emacs-leuven-theme (master)
    $ g show
      2020-04-24 14:04:43 +0200 8a4f745 (HEAD -> master) Apply ...
      ----------------------------------------------------------------------------------------------------------
      -
      modified: leuven-theme.el
      ----------------------------------------------------------------------------------------------------------
      -
      @ leuven-theme.el:7 @
    
      ;; Author: Fabrice Niessen <(concat "fniessen" at-sign "pirilampo.org")>
      ;; URL: https://github.com/fniessen/emacs-leuven-theme
      ;; Version: 20200422.0734

**Comment by fniessen** [comment]
I dunno if this is normal or not.

**Comment by scottchiefbaker** [comment]
Where do you see blank lines?

**Comment by fniessen** [comment]
I meant (and wrote ;-)) blank characters… 1 blank is certainly normal (for the + or - sign), but what about 2 characters?

**Comment by scottchiefbaker** [comment]
My guess is that this is something git specific in your config. Do you get the same issue if you disable your local `~/.gitconfig` by faking out **$HOME**?

```
HOME=/dev/null git show
```

**Comment by fniessen** [comment]
Excellent one-liner -- never thought of such a simple thing!  Thank you!!

Yes, same output, with 2 leading blank characters.

    f.niessen@XIPHIAS:~/.dotfiles/emacs-leuven-theme
    $ HOME=/dev/null git show
      commit 444d36526382466e6bcf11c58066bcef759e4c1f (HEAD -> master, origin/master, origin/HEAD)
      Author: Fabrice Niessen <fniessen@pirilampo.org>
      Date:   Sat Apr 25 09:56:59 2020 +0200

          Improve face for number of informational messages

      diff --git a/leuven-theme.el b/leuven-theme.el
      index e4b40ff..bc0d773 100644
      --- a/leuven-theme.el
      +++ b/leuven-theme.el
      @@ -4,7 +4,7 @@

       ;; Author: Fabrice Niessen <(concat "fniessen" at-sign "pirilampo.org")>
       ;; URL: https://github.com/fniessen/emacs-leuven-theme
      -;; Version: 20200424.1403
      +;; Version: 20200425.0956
       ;; Keywords: color theme

       ;; This file is part of GNU Emacs.
      @@ -432,7 +432,7 @@ more...")
          ;; `(completions-common-part ((,class (:foreground "red" :weight bold))))
          ;; `(completions-first-difference ((,class (:foreground "green" :weight bold))))
          `(compilation-error ((,class (:weight bold :foreground "red")))) ; Used for grep error messages.
      -   `(compilation-info ((,class ,grep-file-name)))
      +   `(compilation-info ((,class (:weight bold :foreground "#6784d7"))))
          `(compilation-line-number ((,class ,grep-line-number)))

**Comment by scottchiefbaker** [comment]
Do you see the extra lines in the `git diff` output without d-s-f? This is sounding more like a git issue, than a d-s-f issue.

**Comment by alissa-huskey** [comment]
I was running into the same thing. It turned out I had an option in `$LESS` that enabled the status column, and thus added a space at the beginning of every line. 

I was able to resolve it by clearing the LESS environment variable in my `core.pager` config to.

`git config --global core.pager "diff-so-fancy | LESS= less --tabs=4 -RFX"`

If anyone else is running into this, they can check `$LESS`, `$MORE` and `command -v less` for the following flags:

```
-J or --status-column
-w or --hilite-unread
-W or --HILITE-UNREAD
```

**Comment by fniessen** [comment]
Dear @alissa-huskey , thanks _A LOT_ for the tip!  This does indeed solve my length problem as well.

The Unicode aspect remains, though.  Any idea?

**Comment by alissa-huskey** [comment]
> The Unicode aspect remains, though. Any idea?

I'm not sure what you mean. Can you provide more details?

Off the top of my head when over encountered encoding issues it has been a locale issue. Try checking `locale`, `man locale` and the `LC_*`

**Comment by fniessen** [comment]
Dear @alissa-huskey , Here's a screenshot showing the problem of the ruler:

![image](https://user-images.githubusercontent.com/1748469/103151078-14c5f800-477b-11eb-9fd1-e6bf0ef85071.png)

... while I do have UTF-8 in all locales...

Any idea?

PS- Happy Christmas!

**Comment by scottchiefbaker** [comment]
We use this:

https://github.com/so-fancy/diff-so-fancy/blob/master/diff-so-fancy#L490

to determine if we should output in unicode or ASCII. We've had several bug reports on this over the years, and to my recollection **every** one has been related to a terminal bug or configuration issue.

**Comment by fniessen** [comment]
Dear @scottchiefbaker ,

I do have this for the locales:

    $ echo "$LESSCHARSET", "$LESSCHARDEF", "$LC_ALL", "$LC_CTYPE", "$LANG"
    , , , , C.UTF-8

So, I do have UTF-8 in there.

But I just discovered that changing my pager definition from:

    pager = diff-so-fancy | LESS= less --tabs=4 -RFX

to

    pager = diff-so-fancy | LESS= less --tabs=4 -RFX

makes the UTF-8 ruler appears. And moving back to the old def makes it disappear.

Does that mean I can't use my first definition of pager, with `less` automagically applied?

**Comment by scottchiefbaker** [comment]
I just pushed a commit to add a `--debug` option. Can you download the version on the `next` branch and then run:

    diff-so-fancy --debug

And post the output. It will help us determine what the issue is.

**Comment by fniessen** [comment]
Dear @scottchiefbaker , thanks for helping!

Is it this output you're after?

    f.niessen@XIPHIAS:~/diff-so-fancy (next)
    $ ./diff-so-fancy -v
    Diff-so-fancy: https://github.com/so-fancy/diff-so-fancy
    Version      : 1.4.0

    f.niessen@XIPHIAS:~/diff-so-fancy (next)
    $ ./diff-so-fancy --debug
    Missing input on STDIN

    f.niessen@XIPHIAS:~/diff-so-fancy (next)
    $ head lib/DiffHighlight.pm | ./diff-so-fancy --debug
    package DiffHighlight;

    use 5.008;
    use warnings FATAL => 'all';
    use strict;

    # Use the correct value for both UNIX and Windows (/dev/null vs nul)
    use File::Spec;

    my $NULL = File::Spec->devnull();

    f.niessen@XIPHIAS:~/diff-so-fancy (next)
    $

**Comment by scottchiefbaker** [comment]
Sorry... I pushed to my repo, not this repo. Try `git pull` again and then `diff-so-fancy --debug`

**Comment by fniessen** [comment]
Never mind.  Here's the new output:

     f.niessen@XIPHIAS:~/diff-so-fancy (next)
    $ g pull
    From https://github.com/so-fancy/diff-so-fancy
       ac392fa..7792d3f  next       -> origin/next
    Updating ac392fa..7792d3f
    Fast-forward
     diff-so-fancy | 32 ++++++++++++++++++++++++++++++++
     1 file changed, 32 insertions(+)

    f.niessen@XIPHIAS:~/diff-so-fancy (next)
    $ ./diff-so-fancy -v
    Diff-so-fancy: https://github.com/so-fancy/diff-so-fancy
    Version      : 1.4.0

    f.niessen@XIPHIAS:~/diff-so-fancy (next)
    $ head lib/DiffHighlight.pm | ./diff-so-fancy --debug
    Diff-so-fancy   : v1.4.0
    Git             : v2.29.2
    Perl            : v5.30.3

    Supports Unicode: Yes
    Unicode Ruler   : Yes
    Terminal width  : 236
    Terminal $LANG  : C.UTF-8
    Is Windows      : Yes
    Operating System: cygwin

**Comment by scottchiefbaker** [comment]
@fniessen that all looks normal to me. I wonder if somehow things are changing when it gets piped to less. What if you change your pager to:

    pager = diff-so-fancy --debug | LESS= less --tabs=4 -RFX

and then you run `git diff`

**Comment by fniessen** [comment]
Dear @scottchiefbaker 

A picture is worth 1,000 words:

![image](https://user-images.githubusercontent.com/1748469/103271790-7aa0c280-49bb-11eb-898c-88be71ad5a2f.png)

Not getting it yet... ;-(

Best regards!

**Comment by fniessen** [comment]
@scottchiefbaker , The previous test wasn't correct anymore, as I still had a copy of diff-so-fancy in my PATH.
Now, it's correct... and gives interesting info:

![image](https://user-images.githubusercontent.com/1748469/103298597-fa01b680-49fa-11eb-96b1-d41dff9ad9c4.png)

Can you "parse" it?

**Comment by fniessen** [comment]
FYI,

    f.niessen@XIPHIAS:~/diff-so-fancy (next)
    $ g alias G df
    df = diff

**Comment by scottchiefbaker** [comment]
Interesting... so when you pipe it to less d-s-f no longer things your terminal supports unicode. We try and be smart by detecting what charset less supports [here](https://github.com/so-fancy/diff-so-fancy/blob/master/diff-so-fancy#L490).

My guess is you have an environment variable set that's telling `less` not to do unicode. What is your output of:

    env | egrep 'LESSCHAR|LC_|LANG'

**Comment by fniessen** [comment]
Dear @scottchiefbaker , these are the results:

    $ env | egrep 'LESSCHAR|LC_|LANG'
    LC_CTYPE=
    LANG=C.UTF-8

**Comment by scottchiefbaker** [comment]
Aha... that is the problem then. 

https://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html

`LC_CTYPE` being set to "" is making d-s-f think `less` doesn't support Unicode. You either need to unset `LC_CTYPE` entirely or set it to something with `UTF-8` in it.

**Comment by fniessen** [comment]
Dear @scottchiefbaker ,

Indeed, I had this in my Shell RC files:

    # For scripts in R language.
    export LC_CTYPE=

Something to do with handling of accents.

I now did `unset LC_CTYPE` and that does work.

PS - Weird to see the output of `locale` where we do think that LC_CTYPE is set...
PPS - Dunno if my R scripts problems will reoccur...

**Comment by scottchiefbaker** [comment]
Well you inspired me to add `--debug` which will help in the future. Glad it's fixed.

**Comment by fniessen** [comment]
Dear @scottchiefbaker , thanks a lot for the help - and the improvement!

Maybe a suggestion for the --debug option: add the explicit values of some of the key env vars, such as LC_CTYPE?

**Comment by scottchiefbaker** [comment]
d-s-f uses a [bunch of variables](https://github.com/so-fancy/diff-so-fancy/blob/master/diff-so-fancy#L482) to determine if `less` supports Unicode. Whichever of those it finds **first** is what it will use to determine Unicodeness. Whatever that value is, is what d-s-f prints out in `--debug`.
