### ISSUE TITLE
v1.2.7 reports version as 1.2.6

### ISSUE THREAD

**Issue by OJFord** [so-fancy/diff-so-fancy#367]
https://github.com/so-fancy/diff-so-fancy/blob/05e2a1aca01746ed5de24e27f1ca7832393dc216/diff-so-fancy#L3

**Comment by OJFord** [comment]
Ah, only now do I see #346.

Issue is that packagers have picked it up because it is tagged and listed in 'releases', even though GitHub's 'latest' embellishment is sitting on 1.2.6 (because that's had a 'Release' created for it with description etc.).

**Comment by scottchiefbaker** [comment]
This is a known bug. There is no real difference between the two versions, it was a labeling mistake between developers. I don't want to release a whole new version JUST to bump the version. This will be fixed at the next release.
