### ISSUE TITLE
[BUG] Use of uninitialized value $add_color

### ISSUE THREAD

**Issue by bruce-ricard** [so-fancy/diff-so-fancy#369]
Using version: 1.2.6

When running `git log -p | diff-so-fancy | less -RFX`, it appears that I get a good output, but the last line of the initial first page of the `less` contains:

> :Use of uninitialized value $add_color in concatenation (.) or string at /usr/local/bin/diff-so-fancy line 593, <STDIN> line 546.

When I move the `less` up and down, this line moves up and down with the rest of my diff, as if it was part of it. 
I was actually wondering for quite a few seconds why that line was in my files.

There might be something wrong with my setup, but the error message should not be displayed this way.

edit: it appears the issue was because the executable couldn't find the library. As I mentioned in an [other issue](https://github.com/so-fancy/diff-so-fancy/issues/333#issuecomment-618124738) it would be great if the error message could be clearer that the library couldn't be found by the executable.

**Comment by scottchiefbaker** [comment]
This is indeed a side-effect of not being able to find the `DiffHighlight` library. I commented in that #333 regarding the proper ways to install the script, which would avoid this in the future.
