### ISSUE TITLE
I can't find a changelog?

### ISSUE THREAD

**Issue by timotheecour** [so-fancy/diff-so-fancy#370]

**Comment by scottchiefbaker** [comment]
Can you elaborate on what you're trying to find?

**Comment by timotheecour** [comment]
Most projects have a changelog, it is useful when you've upgraded to latest release tag and dont want to peer commits. Feel free to close.

**Comment by scottchiefbaker** [comment]
I don't publish and actual changelog **file**, but I do chronicle all the changes in the release information section of GitHub.

https://github.com/so-fancy/diff-so-fancy/releases

Does that have what you want?

**Comment by timotheecour** [comment]
yes, thanks!
