### ISSUE TITLE
Syntax-highlighting for combined diff is not rendered in a word-by-word basis

### ISSUE THREAD

**Issue by thith2** [so-fancy/diff-so-fancy#371]
I consider this as a bug because with normal git diff input, d-s-f perfectly highlighted changed words within lines, as shown in the project README screenshot.

Reproducing the issue:
```
% diff-so-fancy < combined-diff.txt
```

(where `combined-diff.txt` contains exactly same example combined diff as found at <https://git-scm.com/docs/diff-generate-patch#_combined_diff_format>)

**Comment by OJFord** [comment]
- `diff-so-fancy` itself does not do any highlighting
- `diff-highlight` (typically distributed with git: https://github.com/git/git/tree/master/contrib/diff-highlight) highlights intra-line diffs, but not syntax

What is the issue you are seeing? No highlightling at all? How about `diff-highlight < combined-diff.txt`?

**Comment by thith2** [comment]
> * `diff-so-fancy` itself does not do any highlighting
>
> * `diff-highlight` (typically distributed with git: https://github.com/git/git/tree/master/contrib/diff-highlight) highlights intra-line diffs, but not syntax

Thanks for pointing these out, after attempts to read the source code with the help of your tips (BTW I'm not a Perl guy) it appears that the root cause is `diff-hightlight` script, which does not support combined diff.  Oh, then this would be an upstream issue.

> What is the issue you are seeing?

It does not highlight the *word changes* -- by say word changes here I mean string colored by attribute `color.diff-highlight.newHighlight` and `color.diff-highlight.newHighlight`, i.e. string like `Core::` found in the right side of project screenshot:
![](https://user-images.githubusercontent.com/3429760/32387617-44c873da-c082-11e7-829c-6160b853adcb.png)

> No highlightling at all?

There is highlighting in the output of `diff-so-fancy < combined-diff.txt`, but there is not word-by-word highlighting, which is caused by `diff-highlight`'s lacking of support for combined diff.

> How about `diff-highlight < combined-diff.txt`?

Because the `diff-highlight` does not support combined diff, the output of `diff-highlight < combined-diff.txt` is not colored at all.  I think my copy of `diff-highlight` is OK, test shown that it works as expected with normal diffs (which display word changes in reverse video), it just lacks support for combined diff.

**Comment by thith2** [comment]
And since this is an upstream issue -- if I understand correctly -- here I'm closing this issue.
