### ISSUE TITLE
side-by-side view (two columns)

### ISSUE THREAD

**Issue by MarcoIeni** [so-fancy/diff-so-fancy#377]
`diff` supports the -y options. From the man page:
```
       -y, --side-by-side
              output in two columns
```

let's say we have two files:
one:
```
hi
from me
to you
```

and two:
```
hello
from me
to everyone
```

This is the output:
```
$ diff -y one two
hi							      |	hello
from me								from me
to you							      |	to everyone
```
As you can see a `|` character is shown where lines differ, but nothing more than this.

Would it be possible to have this kind of output with `diff-so-fancy`, too?
If so, different words (for example `you` and `everyone` should be highlighted as usual.

**Comment by scottchiefbaker** [comment]
Unfortunately the way d-s-f is architected this type of output would be almost impossible to support. There are other tools that do what you want... tig comes to mind. 

For d-s-f though this is a `CANTFIX`.
