### ISSUE TITLE
Segmentation fault on macOS 10.15.6

### ISSUE THREAD

**Issue by MenkeTechnologies** [so-fancy/diff-so-fancy#378]
<img width="416" alt="Untitled" src="https://user-images.githubusercontent.com/18195247/88571967-6cb1d480-d00c-11ea-8caa-19a1366eef56.png">

**Comment by scottchiefbaker** [comment]
That's impressive! 

d-s-f is just a Perl script, so theoretically it's **impossible** for it to segfault. Most likely your Perl installation is messed up, and that's what is segfaulting.

**Comment by MenkeTechnologies** [comment]
yeah its my PERL5LIB env variable.

**Comment by scottchiefbaker** [comment]
Phew. You had me nervous.

Glad you found a fix.
