### ISSUE TITLE
How to installon debian

### ISSUE THREAD

**Issue by Melonangie** [so-fancy/diff-so-fancy#380]
diff-so-fancy doesn't appear in my repos. How do you manually install it?
`あす sudo aptitude install diff-so-fancy                                                                                     
[sudo] password for kenzo: 
Couldn't find any package whose name or description matched "diff-so-fancy"
Unable to apply some actions, aborting
`

**Comment by scottchiefbaker** [comment]
Here are the [installation instructions](https://github.com/so-fancy/diff-so-fancy#install).

**Comment by IceCodeNew** [comment]
search, before ask.
https://github.com/so-fancy/diff-so-fancy/issues/357

**Comment by aos** [comment]
I've updated the issue #357 with installation instructions for Debian and Ubuntu. Hope that helps!
