### ISSUE TITLE
Wrong file name when use with "kubectl diff"

### ISSUE THREAD

**Issue by Just4test** [so-fancy/diff-so-fancy#381]
I run command such like
```
kubectl diff --server-side=false -f 123.yaml | diff-so-fancy
```
There are sevel resources in 123.yaml, kubectl will compare them one by one. From the second part, diff-so-fancy still using the file name in first part.
Here's the second part of kubectl diff result:
```
--- /tmp/LIVE-067561829/apps.v1.Deployment.ettsx.resource-rabbitmq-consumer
+++ /tmp/MERGED-612643200/apps.v1.Deployment.ettsx.resource-rabbitmq-consumer
@@ -2,11 +2,10 @@
```

diff-so-fancy change it into:
```
-- /tmp/LIVE-067561829/apps.v1.Deployment.ettsx.resource-rabbitmq-consumer
++ /tmp/MERGED-612643200/apps.v1.Deployment.ettsx.resource-rabbitmq-consumer
@ /tmp/MERGED-612643200/apps.v1.Deployment.ettsx.evaluation-kafka-consumer:5 @
```

**Comment by Just4test** [comment]
Here's the complete file.
[diff.txt](https://github.com/so-fancy/diff-so-fancy/files/5116385/diff.txt)

**Comment by scottchiefbaker** [comment]
d-s-f expects the diff output to be in `git` format. In this scenario I assume d-s-f thinks the file is being renamed (because the paths are different). In other words, this is not the standard format d-s-f expects, but it will work other than the filename portion.
