### ISSUE TITLE
Request: Debian package for Focal (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by rootwork** [so-fancy/diff-so-fancy#383]
Not sure if I should request this here or of @aos directly -- thank you for the earlier Debian packages! -- but the [PPA for diff-so-fancy](https://launchpad.net/~aos1/+archive/ubuntu/diff-so-fancy) only lists Xenial and Bionic (the last two Ubuntu LTS releases), so you can't `apt install` it on Focal.

Would it be possible to create a Debian package for Focal?

Thank you!

**Comment by rootwork** [comment]
See #357 for the original creation of the Debian packages.

**Comment by aos** [comment]
Hey @rootwork -- thanks for the ping. I am currently in the process of publishing the `1.3.0` version for Focal/Bionic/Xenial as well as porting `1.2.6` to Focal. Hopefully they'll be ready by tomorrow (just waiting on Launchpad to publish). Hang tight!

**Comment by rootwork** [comment]
Awesome, thanks so much for your work on this @aos! I (and I'm sure many others) really appreciate it!

**Comment by hyorigo** [comment]
Here's the commands for Ubuntu/Debian, in case others may need:

```bash
add-apt-repository -y ppa:aos1/diff-so-fancy
apt update
apt install -y diff-so-fancy
```

**Comment by OJFord** [comment]
> Not sure if I should request this here or of @aos directly

Repo is [here](https://github.com/aos/dsf-package) - packaging issues probably best discussed there.

**Comment by wolf99** [comment]
Can this be mentioned as part of the installation section in this repo's docs?
I just spent the last 10 mins (Yeah I was a bit slow to check issues! 😂) trying to figure how to have a `lib`  directory in a standard bin location (e.g. `/usr/local/bin/`) without fear of future name clashes (I don't think it's possible).

**Comment by rootwork** [comment]
+1 to either adding these instructions to the installation section or, barring that, at least linking to https://github.com/aos/dsf-package or https://launchpad.net/~aos1/+archive/ubuntu/diff-so-fancy

More and more people will be looking for Ubuntu 20+/compatible Debian versions.

**Comment by rootwork** [comment]
Also I was about to do a PR for this to make it easier, but wasn't sure how/where the maintainers would want to place this info.

**Comment by OJFord** [comment]
The install section currently says:

> diff-so-fancy is also available from NPM, Nix, brew, and as a package on Arch and Debian Linux.

Expanding on that to at least link the packages sounds good to me @rootwork.

**Comment by OJFord** [comment]
Sorry @rootwork I'd forgotten about that offer and just opened #404; your comments would be welcome of course 🙂.

I'll close this now as I assume from above that it is now updated for 'Focal'; if there's any issue with that best to discuss on that its own GH repo (or Launchpad mailing list, or whatever).

Cheers.
