### ISSUE TITLE
Request: flag to fall back to regular diff

### ISSUE THREAD

**Issue by albertvaka** [so-fancy/diff-so-fancy#384]
I want to copy some patches onto an email thread, and I want them to be consistent with other diffs that are being sent there. Right now I have to temporarily revert my gitconfig. Would be nice if this could be done with a command line arg.

**Comment by scottchiefbaker** [comment]
d-s-f only kicks in for an interactive terminal (i.e. a human is reading it). If you redirect to a file you should still get normal diff output:

    git diff > /tmp/my.diff

**Comment by albertvaka** [comment]
That solves it for me then, thanks!
