### ISSUE TITLE
Using Vim/Neovim as pager

### ISSUE THREAD

**Issue by Akmadan23** [so-fancy/diff-so-fancy#393]
Is it possible to pipe `diff-so-fancy` into vim and display colors and characters correctly? I tried setting `ft=diff` but colors aren't displayed correctly...

**Comment by scottchiefbaker** [comment]
That's probably a question better posed to vim/nvim people. d-s-f outputs text wrapped in ANSI color codes. Anything that can display those should work just fine.

**Comment by Akmadan23** [comment]
Yes, I needed a plugin to escape ANSI codes, so I tried [AnsiEsc.vim](https://github.com/vim-scripts/AnsiEsc.vim), which worked in part but there were some errors, then I found [vim-plugin-AnsiEsc](https://github.com/powerman/vim-plugin-AnsiEsc), a fork that handles every escape sequence and works pretty well.
