### ISSUE TITLE
Is there a quick way to toggle to default behavior ?

### ISSUE THREAD

**Issue by meehatpa** [so-fancy/diff-so-fancy#396]
Without having to edit .gitconfig, is there way to temporarily revert to default git diff's behavior?

**Comment by scottchiefbaker** [comment]
There are a couple suggestions in our [ProTip](https://github.com/so-fancy/diff-so-fancy/blob/master/pro-tips.md#opting-out) docs.

**Comment by meehatpa** [comment]
Thanks. That is exactly what I was looking for.
