### ISSUE TITLE
Need to fix failing OSX tests

### ISSUE THREAD

**Issue by scottchiefbaker** [so-fancy/diff-so-fancy#402]
Looks like our OSX tests are failing with some tooling errors. I don't know anything about OSX testing/tooling I'm hoping someone in the community can help.

**Comment by scottchiefbaker** [comment]
@GenieTim are you available?

**Comment by GenieTim** [comment]
I will look at it. Is it urgent or Weekend sufficient?

**Comment by scottchiefbaker** [comment]
Not a huge hurry... at your leisure sir.

Thanks for the prompt response.
