### ISSUE TITLE
[improvement] Request: whitespace symbols

### ISSUE THREAD

**Issue by jaques-sam** [so-fancy/diff-so-fancy#405]
I really ❤️ this tool and I use it everyday!

There is a nice improvement that will help everyone using it: showing whitespaces with different characters.
It's not always clear which whitespace it is, and I had already assumed wrongly.

Thanks!

**Comment by OJFord** [comment]
Empty lines are marked by default, and whitespace that's added/removed should be highlighted?

So you'd like the whitespace diff to be represented by some other character in addition to/instead of the highlighting? How would you distinguish a whitespace diff from a diff involving that character itself?

**Comment by jaques-sam** [comment]
Yes, I mean using the typical whitespace characters like `¶ ⇥ ↵ ﹒` etc. Of course you'd give them a different color so you won't spot them as changed characters 😉 This way you can distinguish between them. Btw, in 99.99% of the cases, I don't see why I would have a ↵ symbol in my code, other than special files with symbols :-) (this could be the off-case where people want to disable whitespace characters)

**Comment by scottchiefbaker** [comment]
Would you want ALL whitespace shown with a special char, or just stuff on changed lines?

**Comment by jaques-sam** [comment]
My first thought was only the changed lines. In the rest, the user is not interested.

**Comment by scottchiefbaker** [comment]
It sounds to me like you're trying to catch whitespace "errors" before they get committed. I fully support that, as I'm very picky about my whitespace as well.

That said I think that checking is much better performed by your editor and/or git. I have `vim` configured to highlight any [bad whitespace](https://vim.fandom.com/wiki/Highlight_unwanted_spaces).

Alternately you can [configure](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---check) `git` to not allow you to commit files with whitespace errors with `--check` or `--ws-error-highlight`.

I think what you're requesting is better done by other tools.

**Comment by scottchiefbaker** [comment]
The more I think about this... it's best done in other tools and not d-s-f. I'm gonna close this issue. If you find a compelling reason it should be in d-s-f we can re-open it.
