### ISSUE TITLE
MacOS tests are failing again?

### ISSUE THREAD

**Issue by scottchiefbaker** [so-fancy/diff-so-fancy#412]
@GenieTim looks like our Mac tests are failing again. If you have a chance can you take a look?

**Comment by GenieTim** [comment]
Which branch are we talking about? Both next and master's badges are green?

**Comment by scottchiefbaker** [comment]
Weird... yesterday I was seeing a MacOS failure in the tests. Must have been a fluke. Thanks for checking!

**Comment by GenieTim** [comment]
Alright. Maybe it was a timeout or something, the current MacOS tests include tons of uncached installs and updates.

**Comment by scottchiefbaker** [comment]
So... every commit I get an email saying their is a failure...

https://travis-ci.org/github/scottchiefbaker/diff-so-fancy/jobs/773162255

But the badges are green?

**Comment by GenieTim** [comment]
Strange. Even stranger: this fail you linked to is using the old travis config (xcode 9.4 rather than 12.2). Did my last PR go into the wrong branch?

**Comment by scottchiefbaker** [comment]
No I don't think... I'm also pushing to my repo:

https://github.com/scottchiefbaker/diff-so-fancy/tree/master

Maybe the config is wrong there?

**Comment by GenieTim** [comment]
> Maybe the config is wrong there?

In the next branch it is, yes, but not in the master. The failing job you sent is in the next branch, where yes, it is the wrong one.
