### ISSUE TITLE
`diff-so-fancy --set-defaults` gets stuck at reading the `stdin` (at branch next)

### ISSUE THREAD

**Issue by XuehaiPan** [so-fancy/diff-so-fancy#413]
I installed `diff-so-fancy` at the next branch. And `diff-so-fancy --set-defaults` gets stuck at reading the `stdin`. This issue can be reproduced on both macOS and Linux.

Steps to reproduce:

```bash
git clone https://github.com/so-fancy/diff-so-fancy.git --branch next
cd diff-so-fancy
./diff-so-fancy --set-defaults
```

Or install using Homebrew / Linuxbrew:

```bash
brew install diff-so-fancy
diff-so-fancy --set-defaults
```

**Comment by OJFord** [comment]
> Or install using Homebrew / Linuxbrew: `brew install diff-so-fancy`

Unless you `install --HEAD` that will (today) install v1.4.1.

So are you reproducing this with both v1.4.1 and the next branch, or did you `install --HEAD` but just omit it from the issue description?

**Comment by scottchiefbaker** [comment]
I believe I found the bug... can you try again with the `next` branch?

**Comment by XuehaiPan** [comment]
It is fixed by the newest commint at the `next` branch.

**Comment by scottchiefbaker** [comment]
Excellent!
