### ISSUE TITLE
NPM version is still 1.3.0

### ISSUE THREAD

**Issue by wvds** [so-fancy/diff-so-fancy#416]
It looks like the version on NPM is outdated, see: https://www.npmjs.com/package/diff-so-fancy
The package.json contains the same version, but the releases say 1.4.2 is the latest.

I noticed it because the --patch mode gave an error in interactive mode, while I saw it was implemented.
We can still get the latest version via `npm install -g so-fancy/diff-so-fancy#v1.4.2`, but it would be nicer if we could just do `npm install diff-so-fancy@latest`.

Thanks for the awesome package!

**Comment by scottchiefbaker** [comment]
Paging @stevemao or @paulirish to look at NPM stuff.

**Comment by paulirish** [comment]
1.4.2 published on npm
