### ISSUE TITLE
Merge updates to master branch into next

### ISSUE THREAD

**Issue by codeinred** [so-fancy/diff-so-fancy#424]
`master` has some updates / modifications that aren't present in `next`. There aren't a lot, thankfully, and these changes can be merged without any conflicts, but it should probably be taken care of so that next remains a superset of the master branch.

![image](https://user-images.githubusercontent.com/36810712/139909204-79eba663-3032-42ea-9daf-1ca446118daf.png)

**Comment by scottchiefbaker** [comment]
Good catch. We had a couple merges accidentally go in to `master`, but that should be merged now. Can you confirm?

**Comment by codeinred** [comment]
It looks good! Thank you for taking care of that!
