### ISSUE TITLE
Release a version for ubuntu impish dist

### ISSUE THREAD

**Issue by albertoleal** [so-fancy/diff-so-fancy#427]
Hi 👋 

I'm getting the following error:

```
Failed to update apt cache: E:The repository 'http://ppa.launchpad.net/aos1/diff-so-fancy/ubuntu impish Release' does not have a Release file., W:Updating from such a repository can't be done
```

And, looking at the repo, it does not have a release for impish yet. Could you please release one? :)
Thanks

**Comment by OJFord** [comment]
Hi, Debian/Ubuntu/derivative packages are provided by https://github.com/aos/dsf-debian, please open an issue there.

Thanks 🙂.
