### ISSUE TITLE
different default set for black-on-white terminals?

### ISSUE THREAD

**Issue by 0-wiz-0** [so-fancy/diff-so-fancy#428]
I prefer black-on-white mode, and in that, some of the output of diff-so-fancy is hard to read (first lines of `--help` is light-grey, header for diff is yellow). Is there an easy way to make diff-so-fancy aware of that preference and choose different colors?

**Comment by OJFord** [comment]
The colours in the readme are just a suggestion, you can set them to whatever you prefer. There aren't diff-so-fancy-specific defaults, it's just git defaults, or what's in your [git config](https://git-scm.com/docs/git-config).

**Comment by 0-wiz-0** [comment]
The version is always printed with color("white_bold").
Reading the source code I see that I can change the "meta" color to change the yellow though, thanks.
