### ISSUE TITLE
Feature request: semantical diffs

### ISSUE THREAD

**Issue by DavidFarago** [so-fancy/diff-so-fancy#432]
How hard would it be to integrate some semantical diffs, esp. detecting code refactorings like 
* grouping together multiple same renamings of a variable of function name
* show that code has been moved, so that a reviewer does not need to stare and compare the moved code block.

An example of semantical diffs can be found at https://sysmagine.com/products/inspecdiff/.

**Comment by OJFord** [comment]
I long for the day that git or a similarly ubiquitous tool offers semantic diffs, but it can't be achieved in diff-so-fancy without entirely changing what it is.

Dsf is only the pager (or a filter in pager pipeline) for a diff, for example output by git. It does not generate the diff itself; what it operates on does not contain enough information to be turned into a semantic diff, it'd have to additionally open and parse both versions of the file.

**Comment by scottchiefbaker** [comment]
@DavidFarago fwiw `git diff` does have the `--color-moved` param which will highlight code moves in a different color (and d-s-f respects this). It's not perfect, but I've used it with some success.
