### ISSUE TITLE
Is 1.4.3 a stable release?

### ISSUE THREAD

**Issue by ryandesign** [so-fancy/diff-so-fancy#433]
I see that the 1.4.3 tag was created Jul 27, 2021 however the latest release shown on the project's main GitHub page is still 1.4.2. If 1.4.3 is ready for use, could you create the GitHub release for it as was done for previous releases?

**Comment by ryandesign** [comment]
And see also #418.

**Comment by ryandesign** [comment]
Thank you! Could you add the "fatpacked" diff-so-fancy file to the release's assets?

**Comment by scottchiefbaker** [comment]
Good call... this should be completed now.
