### ISSUE TITLE
Use diff-so-fancy for other command line tools?

### ISSUE THREAD

**Issue by mhyousefi** [so-fancy/diff-so-fancy#435]
First of all, thank you for developing this useful tool.

I was wondering if it is possible to utilize `diff-so-fancy` for other command line tools such as helm (in macOS or linux distros) or is it only applicable to `git`?

**Comment by scottchiefbaker** [comment]
A while back I added [unified diff support](https://github.com/so-fancy/diff-so-fancy#with-diff). Anything that can output unified diffs will probably work with d-s-f. Our primary focus, as @OJFord said is `git` as that is the most commonly used tool. I believe there was work done to get it to work with Mercurial too?
