### ISSUE TITLE
Bright colors are not working when color is not coming from git

### ISSUE THREAD

**Issue by utix** [so-fancy/diff-so-fancy#443]
Since 754f9dfbd2085eb8241d71808dda9592b463c5a8 bright colors for func are not working

**Comment by utix** [comment]
Same issue for `newNormal` and `oldnormal`

**Comment by scottchiefbaker** [comment]
Merged!

**Comment by utix** [comment]
I have a test update to check this and the trailing bold:
https://github.com/utix/diff-so-fancy/commit/0c3f6c3c4ea08847ee1b8c802dfbf8526b691cf8
