### ISSUE TITLE
Convert two variable assignments to the usage of combined operators

### ISSUE THREAD

**Issue by elfring** [so-fancy/diff-so-fancy#448]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://perldoc.perl.org/perlop#Assignment-Operators "Description for assignment operators") accordingly.

```diff
diff --git a/third_party/build_fatpack/build.pl b/third_party/build_fatpack/build.pl
index 942527f..f9d5cae 100755
--- a/third_party/build_fatpack/build.pl
+++ b/third_party/build_fatpack/build.pl
@@ -40,7 +40,7 @@ my $dsf_version = get_version($input_file);
 my $cmd = "fatpack pack $input_file 2>/dev/null > $output_file";
 
 my $exit = system($cmd);
-$exit    = $exit >> 8;
+$exit >>= 8;
 
 rmdir("fatlib"); # fatpack leaves empty fatlib dirs so we remove them
 my $size = -s $output_file;
diff --git a/third_party/cli_bench/cli_bench.pl b/third_party/cli_bench/cli_bench.pl
index 1080ef4..b114aee 100644
--- a/third_party/cli_bench/cli_bench.pl
+++ b/third_party/cli_bench/cli_bench.pl
@@ -114,7 +114,7 @@ sub average {
 	}
 
 	my $count = scalar(@_);
-	$ret = $ret / $count;
+	$ret /= $count;
 
 	return $ret;
 }
```

**Comment by scottchiefbaker** [comment]
These changes are fine with me. Did you want to submit a PR for this?

If you do, please make sure the `=` line up with previous lines. It makes the code more easily readable.

**Comment by elfring** [comment]
:thought_balloon: Can you get into the mood to integrate the shown change possibilities directly just for two source code places?

**Comment by elfring** [comment]
Thanks for [your integration of another small source code improvement](https://github.com/so-fancy/diff-so-fancy/commit/f67767be40620095e13781655e42ce30d1e2858d "Code simplifications").
