### ISSUE TITLE
[QUESTION] Is it possible to make dsf output on the same order as the regular git diff?

### ISSUE THREAD

**Issue by ericriff** [so-fancy/diff-so-fancy#449]
I'm sorry if the title is confusing. I don't know how to put it in words, but when you run dsf the cursor ends up at the end of the report so you have to scroll up to see the rest. 
On the other hand when you run the regular git diff, the cursor ends up at the begging of the report, so you have to scroll down to see the rest of the report.

Even though gsf looks waaaay better than the regular diff, I pretty much prefer the regular git diff behavior described above. The behavior of dsf is particularly annoying when there are a lot of changes on a file, so I have to scroll up a lot to see the file name. 

Thanks.

**Comment by ericriff** [comment]
Well, never mind. It's working as expected now. No idea what changed. Sorry about the noise.

**Comment by OJFord** [comment]
No worries, dsf works line by line, so this should never be (possible to be) the case.

It was perhaps different `less` (or whatever ultimate pager you were using) settings that caused the difference.
