### ISSUE TITLE
Question about packaging

### ISSUE THREAD

**Issue by ghost** [so-fancy/diff-so-fancy#455]
Hi,
I want to package this for Haiku (as I use it on it).

I'd like to know if it is possible to move the lib/ contents into a system library folder instead, so that the main script can still find it.

One complication for this in haiku packages is that they can be mounted anywhere, in theory anyhow. (in practice only the haikuporter tool does this currently, but it uses a chroot for that)
So my question would be, can i patch the script so it would find the library as long as it is in the standard LIBRARY_PATH?

as a second question: is the stuff in third_party required?
(that is is the script + lib/ the only thing needed?)

**Comment by scottchiefbaker** [comment]
@nephele-gh you should only need ONE file if you want to package d-s-f. The easiest thing to do is get the standalone version from the latest release: https://github.com/so-fancy/diff-so-fancy/releases/tag/v1.4.3

That first file is the fatpacked version of d-s-f with the included modules built in.

**Comment by scottchiefbaker** [comment]
👍

**Comment by scottchiefbaker** [comment]
@ghost I don't know much about Haiku? Is there a URL I can include in the README to point at d-s-f in Haiku?
