### ISSUE TITLE
unified diffs with -U0 show incorrect line number

### ISSUE THREAD

**Issue by kambala-decapitator** [so-fancy/diff-so-fancy#460]
Line number is exactly off by 3 (which is the default `-U` value).

macOS 12.6.3, diff-so-fancy v1.4.3 from brew, using the default Terminal app. Have this issue since I started using the tool a few years ago.

Example, the changed line is 1299 (hope it's clear without SS):

```
> git diff sigma-2.4 tbl/sigma/en/patchstring.txt
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: tbl/sigma/en/patchstring.txt
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ tbl/sigma/en/patchstring.txt:1299 @
"x" "+15% Physical Resist After Level 120\n+25% to Experience Gained Until Level 120"
"x" "Treewarden Morph"
"x" "Thundercrack: +100% Bonus Lightning Damage"
"11298" "\dgrey;+8% to Physical/Magic Spell Damage\n+25% Total Character Defense\n+10 Life after each Kill\n+1 to All Skills\n\grey;(Bonus per Socketed Great/Elemental Runes)\n\orange;Gematria"
"11298" "\dgrey;+8% to Physical/Magic Spell Damage\n+25% Bonus to Defense\n+10 Life after each Kill\n+1 to All Skills\n\grey;(Bonus per Socketed Great/Elemental Runes)\n\orange;Gematria"
"11299" "+180% Damage to The Zakarum"
"x" "\dgrey;+20% to Elemental Resists\n+0.75% Base Block Chance\n+1 to All Skills\n\grey;(Bonus per Socketed Great/Elemental Runes)\n\orange;Gematria"
"x" "Worship the Crack Monkeys!"

> git diff -U0 sigma-2.4 tbl/sigma/en/patchstring.txt
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: tbl/sigma/en/patchstring.txt
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ tbl/sigma/en/patchstring.txt:1302 @
"11298" "\dgrey;+8% to Physical/Magic Spell Damage\n+25% Total Character Defense\n+10 Life after each Kill\n+1 to All Skills\n\grey;(Bonus per Socketed Great/Elemental Runes)\n\orange;Gematria"
"11298" "\dgrey;+8% to Physical/Magic Spell Damage\n+25% Bonus to Defense\n+10 Life after each Kill\n+1 to All Skills\n\grey;(Bonus per Socketed Great/Elemental Runes)\n\orange;Gematria"
```

P.S. Tried to follow https://github.com/so-fancy/diff-so-fancy/blob/master/reporting-bugs.md but script gave me an error:

```
> curl https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/report-bug.sh | bash -s 'git diff sigma-2.4 tbl/sigma/en/patchstring.txt' file.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1262  100  1262    0     0   9600      0 --:--:-- --:--:-- --:--:-- 10015
fatal: option '--color' must come before non-option arguments
```

executed in Fish shell if it matters.

**Comment by scottchiefbaker** [comment]
Interesting... this has never come up before. I think most people just roll with the default three lines of context. I made a change on a sample file on line #7, and this is the output from `diff`:

With three (`-u`) lines of context the hunk header is: `@@ -4,7 +4,7 @@`  
With one (`-U1`) lines of context the hunk header is: `@@ -6,3 +6,3 @@`
With one (`-U2`) lines of context the hunk header is: `@@ -5,5 +5,5 @@`
With zero (`-U0`) lines of context the hunk header is: `@@ -7 +7 @@`

If you can find for me what those numbers mean I might be able to fix this. diff-so-fancy has no way of knowing how many lines of context `diff` generated (or even if diff was used), so we can only "guess" based on the input.

**Comment by scottchiefbaker** [comment]
The code in question is this [line](https://github.com/so-fancy/diff-so-fancy/blob/master/diff-so-fancy#L552). If we can find a way to calculate the correct number of context lines there instead of defaulting to three this will be easy.

I don't see an easy way to calculate the offset based on the hunk header though.

**Comment by kambala-decapitator** [comment]
as I understand, those numbers mean:
1. line number of the first line that will be displayed in the hunk
2. (after comma) total number of lines that are displayed in the hunk

so for `-U2` the latter would be 2 + 1 + 2 = 5.

however I can't tell you the right algorithm to find the line number for any `-U` setting.

**Comment by kambala-decapitator** [comment]
oh, maybe just count amount of lines that are prefixed neither with `+` nor `-`?

**Comment by scottchiefbaker** [comment]
I'm wondering if it might not be easier to just add a new cli param for d-s-f to specify the number of context lines?

**Comment by kambala-decapitator** [comment]
> I'm wondering if it might not be easier to just add a new cli param for d-s-f to specify the number of context lines?

would be fine for the first iteration, but not as convenient to end user :) User would have to invent some sort of helper command like `git diffu` that would do something like

```
contextLines=$1
shift
git diff -U$contextLines -c dsf.newOpt=$contextLines $@
```

**Comment by scottchiefbaker** [comment]
@kambala-decapitator I think I have this working. When I went to write a unit test to capture this new (corrected) output I noticed that [three unit tests](https://github.com/so-fancy/diff-so-fancy/commit/e2d91b2147964659b72352835dbd938623ce3093) were failing. Upon closer inspection they were all using `-U0` and d-s-f has been reporting the wrong line number the entire time! 

No one noticed until now.

**Comment by kambala-decapitator** [comment]
@scottchiefbaker from short test this works correctly now! Thanks!

**Comment by scottchiefbaker** [comment]
@kambala-decapitator kick around for a week, see if anything crops off. If you give me the green light after a week I'll merge it.

**Comment by kambala-decapitator** [comment]
I was actively using -U0 today and all line numbers were correct. Same with the default 3 lines.

Will update you in a week.

**Comment by scottchiefbaker** [comment]
@kambala-decapitator it would be helpful if you could test with some other options for `-U`. I'm 99% most people will us 0 or 3, but it would be good to test with other values as well. 

I believe d-s-f should work up to 18 now.

**Comment by kambala-decapitator** [comment]
-U2 shows correct info as well

**Comment by scottchiefbaker** [comment]
I'm gonna merge this branch in to `next` and it will go live when we release the next version.
