### ISSUE TITLE
no background color when play in gitlab ci

### ISSUE THREAD

**Issue by sherlant** [so-fancy/diff-so-fancy#462]
Hello,
I play with diff-so-fancy in gitlab ci. I take a diff between two dirs with the following command :
```
git diff /dir1 /dir2 | diff-so-fancy
```
This works, but i don't have background colors in result of my job. Foreground colors work perfectly.
I have try to do the same command directly in container provisioned by ci, and background colors work.

Any idea ?

Thx

**Comment by sherlant** [comment]
Yes, i can show you.
This is a diff in local :
![image](https://github.com/so-fancy/diff-so-fancy/assets/63449800/3de1ea98-0713-4f9c-9976-f4800f93e81d)

And the same diff in gitlab-ci :
![image](https://github.com/so-fancy/diff-so-fancy/assets/63449800/5724a66f-16f5-4aee-bdad-c68c613f7d4a)

**Comment by OJFord** [comment]
This is not a dsf bug, you'd see the same on your own machine depending on terminal emulator functionality & settings; GitLab simply isn't rendering the background colour, and from my own use I don't think it out supports non-ASCII characters (can't think that I've ever seen one) such as the full-width dash used here: https://en.wikipedia.org/wiki/Box_Drawing
