### ISSUE TITLE
git diff output doesn't scroll using touchpad

### ISSUE THREAD

**Issue by ashu-tosh-kumar** [so-fancy/diff-so-fancy#468]
I installed the diff-so-fancy as specified and configured it as recommended. I also applied the settings for the improved colors for the highlighted bits.

Running the command `git diff` is showing nice diff as expected as shown in below screenshot.

However, the `git diff` output is not scrollable using touchpad that used to work using vanilla `git diff`. I can though use arrow keys to scroll up and down.

<img width="1270" alt="image" src="https://github.com/so-fancy/diff-so-fancy/assets/37182127/8fc43ba6-24d6-40ff-87cd-c9ca91685395">

Configuration:
Laptop - `Macbook Air M1 13.4`
Terminal - `iTerm2 3.4.19`
Shell - `zsh 5.9 (arm-apple-darwin22.1.0)`
Framework - `OhMyZsh master (0024107)`
OMZ theme - `powerlevel10k`
OMZ plugins - `git, zsh-autosuggestions, zsh-syntax-highlighting`

**Comment by OJFord** [comment]
This isn't related to diff-so-fancy - what are you using as the actual pager, `less`?

Basically whatever comes after diff-so-fancy (if 'nothing', the terminal) is what's controlling scroll behaviour and presenting this issue. Diff-so-fancy only modifies the text (including non-rendered text like colour codes) that's ultimately displayed, no rendering/UI/interaction behaviour.

**Comment by ashu-tosh-kumar** [comment]
Okay. Thanks for clarifying. Yes, I am not adding anything after `git diff`. Let me check out how can I change the scroll behaviour.
Will add here if I find the solution in case someone find the same issue.

**Comment by ashu-tosh-kumar** [comment]
I should have checked the already closed tickets. I only checked the open ones.

It's about the pager. Here's a solution someone mentioned in another similar ticket. Doing the same fixed the issue.

https://github.com/so-fancy/diff-so-fancy/issues/26#issuecomment-183706026
