### ISSUE TITLE
Make interactive filter respect `less -S` to avoid wrapping lines

### ISSUE THREAD

**Issue by iandunn** [so-fancy/diff-so-fancy#475]
I use `less -S` to avoid wrapping long lines. That works fine for `git diff`, but not for `git add -p`. I don't see any options to control that, is there a way?

### Reproduction Steps

1. Create a diff where the lines wrap in your terminal
1. Update your `.gitconfig` to match:
	```
	[core]
		pager = diff-so-fancy | less --tabs=4 -SRFX

	[interactive]
		diffFilter = diff-so-fancy --patch
	```
1. Run `git diff` and see that the lines don't wrap -- that's expected
1. Run `git add --patch` and see that the lines _do_ wrap -- that's _not_ expected

**Comment by OJFord** [comment]
No, and not possible either (i.e. would be a git feature request) because in interactive mode the pager isn't invoked, git handles the interactivity, dsf just modifies lines and passes them back to git for display.

**Comment by iandunn** [comment]
Thanks 👍🏻
