### ISSUE TITLE
How do I change the start path of git log output?

### ISSUE THREAD

**Issue by DanKaplanSES** [so-fancy/diff-so-fancy#477]
Hello! I'm not sure if this is a `dsf`'s feature/feature request or `less`'s, but I wanted to know if it is possible to change the start screen of `git log` by passing in an argument to it? I've explained what I mean in more detail here: https://stackoverflow.com/questions/77198186/how-do-i-change-the-path-where-git-log-output-starts Thanks!

**Comment by OJFord** [comment]
Less starts at the 'top' because it doesn't wait for EOF before starting to render anything (this is a feature).

`--reverse` will flip the order of `git log`, so less will still start at the top, but that will be what was previously the end of the input.
