### ISSUE TITLE
git add --patch shows tabs that are 8 spaces wide

### ISSUE THREAD

**Issue by MartinDelille** [so-fancy/diff-so-fancy#478]
Hi,

I have replaced some 4 spaces by tabs in my codebase and since then, `git add --patch` displays the 8 space wide tabs.

I have properly configured my `~/.gitconfig` as the README explain:

```
[core]
	pager = diff-so-fancy | less --tabs=4 -RFX
[interactive]
	diffFilter = diff-so-fancy --patch
```

I read in another issue that the pager doesn't apply when using `git add --patch`.

How can I make my tabs looks 4 spaces width then ?

**Comment by OJFord** [comment]
Can you provide a diff (code block or attachment) that reproduces this with the given configuration please?

Also please provide/verify the output from dsf (prior to less) contains 8 space characters where the input was a single tab character. (If that's not the case, and I'm afraid it seems likely, it's not dsf that's causing this behaviour.)

`--no-pager` or redirection to a file should give you the raw output without dsf; either manually piping that to dsf -
& clipboard or by editing your config will give you dsf's modifications prior to less.

**Comment by OJFord** [comment]
Oh I missed that you said `--patch` was the issue - and not noninteractive diffs? Try `echo -e '1\t2'`, same behaviour? Check your terminal config.

If less works with tab as 4sp and something else doesn't, then we know not only that the less config works but that dsf output is fine - it's outputting the tab character - `less` won't somehow assume 8 spaces were originally a tab character and so turn them back into 4 per its argument.

**Comment by MartinDelille** [comment]
Ok my bad: iTerm was indeed configured to display 8 spaces wide tabs. Fixing this settings solved diff-so-fancy output!

Thank you so much for helping me troubleshoot that!

**Comment by OJFord** [comment]
No worries, glad you sorted it.
