### ISSUE TITLE
Broken link in ZSH install instructions

### ISSUE THREAD

**Issue by jamesbraza** [so-fancy/diff-so-fancy#483]
In https://github.com/so-fancy/diff-so-fancy/tree/578bffcc5a7278e708891b224d2637c382c238da?tab=readme-ov-file#install, the `README.md` points to `diff-so-fancy/zsh-frameworks.md`, which doesn't actually exist.

Can we update the ZSH install instructions to reflect https://github.com/so-fancy/diff-so-fancy/pull/482?

Cc @unixorn

**Comment by unixorn** [comment]
Crud, fixing now
