### ISSUE TITLE
Sed error: bad flag in substitute command

### ISSUE THREAD

**Issue by jenssegers** [so-fancy/diff-so-fancy#49]
I'm getting this error when I try diff-so-fancy:

```
sed: 1: "/^((\033\[([0-9]{1,3}(;[0- ...": bad flag in substitute command: '}'
```

**Comment by stevemao** [comment]
If you downgrade to version `0.1` does it work?

**Comment by jenssegers** [comment]
Version 0.1 works yes :)

**Comment by stevemao** [comment]
Try reverting 6be25ee5508c06987cadff415f6d181e53e031a1?

**Comment by vjdhama** [comment]
Had the same issue and I think I've figured out the issue. I think @jenssegers is using a system(maybe osx) with no `gnu-sed` installed. As suggested in readme, if you're on OSX `brew install gnu-sed` might solve the issue.

**Comment by chris-erickson** [comment]
Confirmed @vjdhama 's fix.  You'll get a shadow `sed` named `gsed` using the homebrew steps and then it'll work.

**Comment by dholdren** [comment]
`brew install gnu-sed` is definitely the fix (as documented in the README)
maybe the script could detect the error and output the instructions?

**Comment by paulirish** [comment]
We'd like to remove the dependency on gnu-sed, to be honest. Would be pleasant to not have to require it.

@xixixao @aziz Can you help to make the script compatible with OSX sed? 

(The only reason it's not already is because I'm lazy and gnu-sed worked out of the box for the regex I wrote here. :)

**Comment by xixixao** [comment]
Well, OS X sed sucks. I think we could use perl instead, looks like it's even faster than sed. I'm not a shell expert to tell whether there are any drawbacks to it.

**Comment by augbog** [comment]
:+1: would be nice if GNU-sed wasn't a requirement
