### ISSUE TITLE
Suggestion: Document git config to automatically fall back to default behaviour if dsf isn't installed

### ISSUE THREAD

**Issue by Encephala** [so-fancy/diff-so-fancy#492]
I wanted to configure git such that if `diff-so-fancy` failed to load, it just used `less`. 
This was pretty straightforward for the `core.pager`:

```ini
[core]
	pager = "command -v diff-so-fancy >/dev/null 2>&1 && diff-so-fancy | less --tabs=4 -RF || less"
```

However, the same trick to make the `interactive.diffFilter` also fallback to using no filter doesn't work - something like 

```ini
[interactive]
	diffFilter = "command -v diff-so-fancy >/dev/null 2>&1 && diff-so-fancy --patch || cat"
```

doesn't work, as `command -v` doesn't echo its input.

I could only get it working by adding a helper script on my `PATH`:

```zsh
#!/usr/bin/zsh

command -v diff-so-fancy >/dev/null 2>&1

if [[ $? -eq 0 ]] 
then
        cat | diff-so-fancy --patch
else
        cat
fi
```

Then (I named the script `dsf-filter`):

```ini
[interactive]
	diffFilter = "dsf-filter"
```

This way, if `diff-so-fancy` is found on `PATH`, it is used, otherwise git transparently defaults to its normal behaviour.

I was wondering if you would like to add this to the pro-tips file or something. If so, I'm happy to open a PR, or feel free to do so yourselves!

**Comment by scottchiefbaker** [comment]
This sounds like the perfect thing for `pro-tips.md`. I'll take a PR for this. Make sure it targets the `next` branch.

**Comment by Encephala** [comment]
Added the PR, feel free to leave any comments on it 👍
