### ISSUE TITLE
Tests required

### ISSUE THREAD

**Issue by paulirish** [so-fancy/diff-so-fancy#57]
We're lacking tests for a few areas. Let's use this ticket to track them. 

* [x] diff-highlight path is resolved on a manual install
* [ ] diff-highlight path is resolved when it's already in the PATH
* [ ] diff-highlight path is resolved with a more complex symlink setup (homebrew install or nvm'd npm install)
* [x] works without extra gnu-sed dependency (requires fix: #49, #55)
* [ ] different meta color doesn't break the diff header formatting (requires fix: #12)

*Please add any others you think we'll need! Edit or leave a comment.*

**Comment by cht8687** [comment]
so after the [merge](https://github.com/so-fancy/diff-so-fancy/pull/60) the task `works without extra gnu-sed dependency` can be marked as done right?

**Comment by stevemao** [comment]
Still missing comprehensive tests for it.

**Comment by OJFord** [comment]
@paulirish Can you clarify the difference between resolving d-h when in `$PATH`, and the following item?

I'm not familiar with nvm'd npm installs, but Homebrew will complain (via `brew doctor`) if `/usr/local/bin` isn't in `$PATH`, which contains symlinks to `diff-so-fancy`, `diff-highlight`, etc. - so isn't just checking it works from `$PATH` sufficient? (c.f. #74, working on my brew install.)

**Comment by paulirish** [comment]
@OJFord I was just differentiating between the cases of 1 symlink involved vs 2+ symlinks. https://github.com/so-fancy/diff-so-fancy/pull/36 also mentions the oddness around this.

**Comment by OJFord** [comment]
Oh I see, I hadn't realised this caused problems.

**Comment by paulirish** [comment]
@OJFord well the new readlink functionality at the top of the file loops to resolve, because asking for `readlink foo` can return another symlink. so its a test for that coverage.
