### ISSUE TITLE
finish migration to `so-fancy` github org

### ISSUE THREAD

**Issue by paulirish** [so-fancy/diff-so-fancy#58]
we've moved this repo!

* [X] the all-important org logo (changes welcome! :)
* [X] teams set up. 
* [X] invites sent out
* [x] URLs updated
* [x] circle/travis badges in readme updated.
* [ ] team accounts on circle/travis set up.

**Comment by stevemao** [comment]
I have removed everyone from the Collaborator of the repo, so we only use team to manage access. Let me know if you have problems.
@paulirish @aziz @noscript

**Comment by paulirish** [comment]
I think we're good on our CI, but we'll keep an eye on it.

cheers :)
