### ISSUE TITLE
Problem on OSX

### ISSUE THREAD

**Issue by brenolf** [so-fancy/diff-so-fancy#66]
When I try `git diff --color | diff-so-fancy` I get the following error: `sed: 1: "/^((\x1B\[([0-9]{1,3}(; ...": bad flag in substitute command: '}'`.

I've just installed it globally and tried a diff.

**Comment by paulirish** [comment]
brew install gnu-sed

**Comment by brenolf** [comment]
My bad, didn't checked that out
