### ISSUE TITLE
Doesn't correct default terminal colours

### ISSUE THREAD

**Issue by dalemy** [so-fancy/diff-so-fancy#68]
Currently, it only sets the colour of particular lines. If the terminal has red or green text for example, it's impossible to tell which lines have been removed or added respectively. If the colour of "normal" text, which hasn't changed, is defaulted to black or white, then it would be much easier to see the changes.

**Comment by stevemao** [comment]
the text is default colour (without ansi). can you check your colour settings? I could set the "white" colour very close to "black".

**Comment by stevemao** [comment]
<img width="489" alt="screen shot 2016-02-16 at 9 54 57 pm" src="https://cloud.githubusercontent.com/assets/6316590/13074323/f77cc634-d4f7-11e5-9d59-41303c377bc0.png">

**Comment by dalemy** [comment]
That's my point though. I have a couple of different terminals which load different profiles and I use colour schemes to differentiate between them. One of them is a black background with green foreground. With this being the case, I can't tell when a line is added or not, since the colours are the same. Having the text default to white/black instead of the foreground colour would be a useful option.

**Comment by stevemao** [comment]
There is no way to tell your "actual" colour of your terminal. We colour the text using ansi escapes and you can actually set say what the actual colour of "Green". Your problem is your green foreground set too close to your ansi "green". Read more: https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by noscript** [comment]
`diff-so-fancy` doesn't modify the colors (except for the context line.) All the color codes come from `diff-highlight` which in turn receives them from git.

Your options are:
* post process `diff-so-fancy` output
* or configure git colors:

```shell
git config --global  color.diff.old="cyan"
git config --global  color.diff.new="yellow"
```

**Comment by stevemao** [comment]
Oh thanks @noscript :) , I thought @dalemy was asking for changing the ansi "white" in the script.

**Comment by noscript** [comment]
Actually [README](https://github.com/so-fancy/diff-so-fancy#improved-colors-for-the-highlighted-bits) describes how to alter `diff-highlight` colors.
