### ISSUE TITLE
Option to enable pesky + or - at line-start

### ISSUE THREAD

**Issue by aristidesfl** [so-fancy/diff-so-fancy#69]
Some people like myself might actually prefer to have the `+` and `-` on the left but still benefit from the other improvements. Feasible?

**Comment by stevemao** [comment]
Why not just using diff-highlight directly?

**Comment by aristidesfl** [comment]
Is the removal of `+ / -` the only difference between `diff-highlight` and `diff-so-fancy` ?

**Comment by noscript** [comment]
Looking at the screenshot, the header is formatted and few other things.

**Comment by arthurdarcet** [comment]
the removal of the +/- is also problematic when git is configured with `core.whitespace = trailing-space` (which highlights trailing spaces at the end of a line in the diff):

![capture d ecran 2016-02-18 a 11 36 32](https://cloud.githubusercontent.com/assets/973454/13140702/e5e66a0a-d633-11e5-8253-ae8bdc85eac8.png)

**Comment by aristidesfl** [comment]
Your screenshot looks like it could be highlighting empty new lines (with new line character). I don't have any trailing white-space and get those for new empty lines with `diff-so-fancy`.

I prefer to have a plus sign for new empty lines than that green rectangle.

**Comment by noscript** [comment]
As has been asked above, why do you still want to use `diff-so-fancy`?

**Comment by aristidesfl** [comment]
> [Looking at the screenshot, the header is formatted and few other things.](https://github.com/so-fancy/diff-so-fancy/issues/69#issuecomment-184662285)

**Comment by paulirish** [comment]
> problematic when git is configured with core.whitespace = trailing-space

@arthurdarcet ooh. Hadn't seen this before. Definitely a bug, so let's pick that up separately: https://github.com/so-fancy/diff-so-fancy/issues/85

**Comment by paulirish** [comment]
I think we could introduce an option to enable line annotations. Like: `diff-so-fancy --plus-signs`  Seems ok

**Comment by blueyed** [comment]
@arthurdarcet 
It's not related to a git option, but diff-so-fancy uses inverted colors to show newlines.

I find these colored blocks really distracting myself, too and would prefer to have just an underlined space there instead.
The highlighting of added newlines would not even be necessary in the middle of a hunk?!
We should probably create a new issue to track this separately?!

**Comment by aristidesfl** [comment]
Can't new lines be marked with the plus sign? Any other whitespace an empty line may contain is marked differently right?

**Comment by blueyed** [comment]
Yes, at least for empty lines a plus sign seems to be sensible by default.

And then I've noticed that it's actually pretty useful for `copy'n'paste` to have the signs, e.g. when you want to paste some patch (completely).  It seems to be easier to remove leading signs when required.

**Comment by lamchau** [comment]
@aristidesfl @blueyed -- is this what you're expecting?

via #108
![image](https://cloud.githubusercontent.com/assets/4911400/13594791/eb3f40e4-e4d4-11e5-8667-e57a89634c56.png)

**Comment by lamchau** [comment]
@paulirish guess we'll just need tests and we're good to go? :)
cc: @stevemao what do you think about this approach?

**Comment by blueyed** [comment]
@lamchau
Yes.

**Comment by aristidesfl** [comment]
looks good

**Comment by paulirish** [comment]
this is now available as of #141 

just requires some twiddling of git config params.. docs to be written (#151)

**Comment by blueyed** [comment]
For reference, the option is:

```
[diff-so-fancy]
	stripLeadingSymbols = false
```

With this, you can then also use `markEmptyLines = false`, and have a `-` there instead of a red square.

**Comment by scottchiefbaker** [comment]
Feature is implemented, docs are written, any reason to leave this issue open?

**Comment by aristidesfl** [comment]
I guess not 👍

**Comment by dliuzzi** [comment]
I have the opposite problem. I want to _remove_ the pesky `+` or `-` at line-start. The docs says this should be the default, but they always show up no matter what I do. I tried `git config --bool --global diff-so-fancy.stripLeadingSymbols true`, just to make extra sure they're stripped, but leading symbols are still included.

**Comment by blueyed** [comment]
@dliuzzi 
I think you should create a new issue for that, providing steps to reproduce it.
Might be some other diff option interfering here, so please check with Git's defaults.

**Comment by dliuzzi** [comment]
Will do. Thanks!

**Comment by fniessen** [comment]
I do have the green blocks displayed, for empty lines, with the following setting:

    whitespace = cr-at-eol

(I don't display +/- signs in front of added/removed lines, which is the default.)
