### ISSUE TITLE
Homebrew formula not found.

### ISSUE THREAD

**Issue by davidteren** [so-fancy/diff-so-fancy#71]
Install on mac results in;

`$ brew install diff-so-fancy
Error: No available formula with the name "diff-so-fancy" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.`

**Comment by DomT4** [comment]
I suspect your `brew` isn't up-to-date. Try `brew update && brew install diff-so-fancy`.

**Comment by davidteren** [comment]
Right you are. Interesting as I did  `brew update` just yesterday evening. Lesson learned thanks.

**Comment by DomT4** [comment]
It was merged ~16 hours ago, so would have needed to have updated since then :smiley:. I just merged an update to the formula, so you should be on `0.4.0` locally now.

**Comment by davidteren** [comment]
That makes sense. Thanks for the heads up. Just tried and it's great but for some layout issues I'm having. I'll log a separate issue for that. 
I'll be adding this to https://github.com/davidteren/devaura
