### ISSUE TITLE
Merge diffs formatted poorly

### ISSUE THREAD

**Issue by heftig** [so-fancy/diff-so-fancy#81]
Removal of the initial +/- interacts poorly with merge diffs, which have two initial columns of indicators.

I also suspect octopus merges can have even more.

**Comment by noscript** [comment]
What do you propose?

**Comment by heftig** [comment]
I am in favor of returning to the normal indicators (#69) for now.

**Comment by noscript** [comment]
Considering this a duplicate of #69.
