### ISSUE TITLE
NPM will not update, as it's a symlink

### ISSUE THREAD

**Issue by paulirish** [so-fancy/diff-so-fancy#82]
Just got this: 

![image](https://cloud.githubusercontent.com/assets/39191/13129327/29f8aca6-d591-11e5-8740-c78b96ecd4f1.png)

.. debugging:

![image](https://cloud.githubusercontent.com/assets/39191/13129385/7ee5bba0-d591-11e5-8958-0a18d46d6646.png)

**Comment by paulirish** [comment]
This appears to be due to the `npm link` I've setup against my development build. And NPM isn't making it easy to unlink... 

![image](https://cloud.githubusercontent.com/assets/39191/13129466/0a1ca24c-d592-11e5-851b-ddf124acdf82.png)


well... low priority as it's not user-facing.

**Comment by stevemao** [comment]
I think its probably a problem with npm itself?
