### ISSUE TITLE
So fancy patch diffs?

### ISSUE THREAD

**Issue by supercrabtree** [so-fancy/diff-so-fancy#84]
Totally loving the new diffs, making my working life much more fun 🙂️

Thing is, you've spoiled me, and I kinda want them everywhere now. I had a quick grep about but couldn't find anything. Does anyone out there know a way to modify the command that generates the patch diffs? I would be happy to implement if someone can point me in the right direction.

In case someone is reading this and thinking "What's a patch diff?" do `git commit -p` from somewhere dirty.

**Comment by stevemao** [comment]
Have you looked at #35?

**Comment by supercrabtree** [comment]
I have no idea how I missed that....
