### ISSUE TITLE
Confusing diff when removing lines that start with -- 

### ISSUE THREAD

**Issue by dideler** [so-fancy/diff-so-fancy#88]
I would expect to see the addition/removal indicator separated by a gap from the content that was changed. For example, `- --content`, but instead I see `---content`.

<img width="219" alt="screenshot 2016-02-21 03 28 38" src="https://cloud.githubusercontent.com/assets/497458/13200689/3810ee86-d84b-11e5-96b4-628f9b1ecf4a.png">

It looks like the deleted lines start with three hyphens, which is a bit misleading.

**Comment by paulirish** [comment]
@dideler we need a bit more detail here

can you run this and share it here?

`git --no-pager diff --staged | pbcopy`

**Comment by dideler** [comment]
Looks like the behaviour is the same in vanilla git diff, sorry for the noise.

```
diff --git a/.rspec b/.rspec
deleted file mode 100644
index 16f9cdb..0000000
--- a/.rspec
+++ /dev/null
@@ -1,2 +0,0 @@
---color
---format documentation
```
