### ISSUE TITLE
cli

### ISSUE THREAD

**Issue by tonekk** [so-fancy/diff-so-fancy#89]
Not sure if this is to be included into the repo, but I found that using the pipe combo is bit much of typing, so I rolled this:

https://github.com/tonekk/git-di

**Comment by noscript** [comment]
There are many ways to achieve less typing. Alias in git config, git pager in config, shell alias, script in `$PATH` (what you did).

But why only 4 parameters? You can pass all via `$@`.

**Comment by stevemao** [comment]
The readme already says

>But, you'll probably want to fancify all your diffs. Run this so git diff (and git show) will use it:
git config --global pager.diff "diff-so-fancy | less --tabs=4 -RFX"
git config --global pager.show "diff-so-fancy | less --tabs=4 -RFX"
However, if you'd prefer to do the fanciness on-demand with git dsf, drop an alias in your ~/.gitconfig:
dsf = "!git diff --color $@ | diff-so-fancy"

**Comment by tonekk** [comment]
@noscript updated, thanks!
@stevemao Reading the full Readme is always beneficial :)
