### ISSUE TITLE
Do we care about `deleted file mode`

### ISSUE THREAD

**Issue by scottchiefbaker** [so-fancy/diff-so-fancy#93]
In the interest of saving screen real-estate, can we remove `deleted file mode`. I can maybe understand showing the added file mode, but who cares about what the file mode was when it was deleted.

Should we remove this line? Or am I just complaining about nothing.

```
new file mode 100644
────────────────────────────────────────────────────────────────
added: hello.txt                                                
────────────────────────────────────────────────────────────────
@@ -0,0 +1 @@
HI THERE
deleted file mode 100644
────────────────────────────────────────────────────────────────
deleted: package.json                                           
────────────────────────────────────────────────────────────────
@@ -1,29 +0,0 @@
```

**Comment by scottchiefbaker** [comment]
Also I'd be open for discussion about the added file mode too. I've never used it, but maybe someone has?

**Comment by paulirish** [comment]
aye. i dont see much reason to keep the deleted file mode.

added can make sense for non-default modes like when +x is applied.

**Comment by scottchiefbaker** [comment]
There is no "default" mode though. I'm not sure if we really care about added mode. It seems that we only really care about the mode when it's changing?

**Comment by paulirish** [comment]
@scottchiefbaker yah. that's fine with me. lets nuke unless mode is changing

**Comment by OJFord** [comment]
I think this would break the hopefully-inbound solution to #35 (`add --patch` support)?

> I'm actually not sure whether it will work well with diff-so-fancy or
not; they change the diff header around a bit, and there's not a
complete 1:1 correspondence in the lines. _But_ I think it might work OK
in practice, because their diff header remains 4 lines long, and the
hunks themselves have 1:1 line correspondence.

**Comment by scottchiefbaker** [comment]
Closing now that #102 has landed.
