### ISSUE TITLE
New empty line deletion is swallowing non-empty lines

### ISSUE THREAD

**Issue by kergoth** [so-fancy/diff-so-fancy#94]
The top commit line in my git log was swallowed by it, for example. I had to revert to the previous version.

**Comment by paulirish** [comment]
hmmm.

@kergoth in the meantime you should make sure your pager is only for git/show. the readme was updated a bit ago.

**Comment by kergoth** [comment]
Ah! I didn't notice the readme update. It did work for `log -p`, though, even though that likely wasn't specifically intended :) I'll switch for now. Thanks.
