### ISSUE TITLE
Jumping between output segments

### ISSUE THREAD

**Issue by patspam** [so-fancy/diff-so-fancy#96]
Prior to using diff-so-fancy, I would often use /^diff or /^commit in less to jump between files/commits.

With diff-so-fancy, I've found I can pre-seed less with the search pattern (-p) which is nice because then I can immediately start hitting "n/p" to jump between matches, but I'm still trying to figure out the most useful regex to use..

Currently I'm using:

`diff-so-fancy | less --tabs=4 -RFX -p'^ -- |^commit'`

which is ok, but it would be a little nicer if I could match the line above, which is the `────` line (unfortunately, I don't think there's an easy way to distinguish it from the second `────` line which appears below the filename).

If this is the sort of thing lots of people do (and not just my own personal weirdness), then maybe diff-so-fancy should help out with making the blocks more matchable.

**Comment by stevemao** [comment]
If we make the first `----` different than the second one, you could then easily use a regex to jump between blocks right? I think it's a good idea.

**Comment by scottchiefbaker** [comment]
@patspam we're in the process of overhauling how the headers are printed. You can view the pull request and associated discussion here:

https://github.com/so-fancy/diff-so-fancy/pull/90

Once that lands you should be able to set a search pattern for "(added|removed|modified) :" and you'll be set.

**Comment by paulirish** [comment]
it's landed, so this should be easier. 

Never knew about this technique. it's pretty excellent, btw

**Comment by scottchiefbaker** [comment]
@patspam this works for me:

```
diff = diff-so-fancy | less --tabs=4 -RFX --pattern='^(added|deleted|modified): '
```

Will that work for you?

**Comment by patspam** [comment]
Sounds great, thanks!

Unfortunately less doesn't behave nicely if you always supply `--pattern` (clears the screen when no match found etc..), but probably possible to create an intermediate script that is smarter.

**Comment by scottchiefbaker** [comment]
Can we close this issue, or is there more to be done?

**Comment by paulirish** [comment]
@patspam i've added something to the readme on this. please PR it if you come up with a better solution.
