### ISSUE TITLE
using arrows navigation

### ISSUE THREAD

**Issue by kartsims** [so-fancy/diff-so-fancy#97]
Wow, after using `git diff` in the CLI for so long I must say I *really* enjoy this stuff !

One thing though that still prevents me from using it when investing large commits (and therefore using it as an alias in my git config), it seems that I can't use the arrows and space key to scroll up and down in the output provided... It just prints everything out and stops. I liked the `less`-like behavior of plein ol' `git diff`, am I missing something or is this just not the way it works ?

Any plan on supporting this or is there a technical limitation of some sort ?

**Comment by stevemao** [comment]
Did you try this:

```
git config --global pager.diff "diff-so-fancy | less --tabs=4 -RFX"
git config --global pager.show "diff-so-fancy | less --tabs=4 -RFX"
```

**Comment by kartsims** [comment]
Okkkk so sorry I read too quickly ! Thanks for the answer :)
