### ISSUE TITLE
New screenshot for readme

### ISSUE THREAD

**Issue by paulirish** [so-fancy/diff-so-fancy#98]
There's been a few changes that aren't reflected in the screenshot or summarized in the readme's text.

e.g. the header_clean, code is flush left, dim foreground on context line

Anybody wanna take a swipe at updating those?

**Comment by scottchiefbaker** [comment]
Before:
![two](https://cloud.githubusercontent.com/assets/3429760/13472896/c04d8142-e06b-11e5-9995-aa3aae7568ac.png)

After:
![one](https://cloud.githubusercontent.com/assets/3429760/13472897/c0520be0-e06b-11e5-8169-5a0ad005aa35.png)

**Comment by paulirish** [comment]
here's the side by side composite:


![image](https://cloud.githubusercontent.com/assets/39191/13478675/feb88ce0-e086-11e5-934d-fe330dbeb67e.png)


look good to folks?

**Comment by scottchiefbaker** [comment]
Actually this has my in-progress hunk code in it. We might want to hold off until #100 lands?

**Comment by paulirish** [comment]
ooooh true.

yeah lets wait for 100

**Comment by scottchiefbaker** [comment]
Do we have another other pending visual changes? Should I generate new screen shots?

**Comment by paulirish** [comment]
that's it! we're ready

**Comment by scottchiefbaker** [comment]
How about this:

![both](https://cloud.githubusercontent.com/assets/3429760/13617626/84f6b924-e534-11e5-82c6-8eae47b5722c.png)

I tried to get some code that would show off each piece of what dsf does.

**Comment by paulirish** [comment]
nice! i think this hits most of the main points yeah.

I'd slightly prefer to show another file header in there, and less of the
big green block.. but i also hate to be nitpicking on what diff to use.. :)

**Comment by scottchiefbaker** [comment]
I wonder if we shouldn't manufacture some commits just for the purposes of documentation. I looked through like 8 different repos trying to find something perfect and couldn't find anything.

**Comment by scottchiefbaker** [comment]
How about this:

![both](https://cloud.githubusercontent.com/assets/3429760/13620818/77d0ac2e-e547-11e5-90f8-bdf9a218905a.png)

I created a bogus branch "screenshot" and pushed it to the repo. We should be able to do `git show 2c24b1d` and always have the same code to generate a screen shot from. What do you think? Do we need any other "examples" in our screenshot?

**Comment by paulirish** [comment]
love it. i tweaked screenshot branch a tad more. 

and here's what i got for results:


![image](https://cloud.githubusercontent.com/assets/39191/13622719/7cc7c54c-e555-11e5-86c4-7045d91af041.png)

**Comment by scottchiefbaker** [comment]
Perfect, love it. Ship it!
